-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('Y48.2', 'Other and unspecified general anaesthetics', 'ICD10_2010', 'MIGRATION'),
('Y48.3', 'Local anaesthetics', 'ICD10_2010', 'MIGRATION'),
('Y48.4', 'Anaesthetic, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y48.5', 'Therapeutic gases', 'ICD10_2010', 'MIGRATION'),
('Y49', 'Psychotropic drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y49.0', 'Tricyclic and tetracyclic antidepressants', 'ICD10_2010', 'MIGRATION'),
('Y49.1', 'Monoamine-oxidase-inhibitor antidepressants', 'ICD10_2010', 'MIGRATION'),
('Y49.2', 'Other and unspecified antidepressants', 'ICD10_2010', 'MIGRATION'),
('Y49.3', 'Phenothiazine antipsychotics and neuroleptics', 'ICD10_2010', 'MIGRATION'),
('Y49.4', 'Butyrophenone and thioxanthene neuroleptics', 'ICD10_2010', 'MIGRATION'),
('Y49.5', 'Other antipsychotics and neuroleptics', 'ICD10_2010', 'MIGRATION'),
('Y49.6', 'Psychodysleptics [hallucinogens]', 'ICD10_2010', 'MIGRATION'),
('Y49.7', 'Psychostimulants with abuse potential', 'ICD10_2010', 'MIGRATION'),
('Y49.8', 'Other psychotropic drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y49.9', 'Psychotropic drug, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y50', 'Central nervous system stimulants, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y50.0', 'Analeptics', 'ICD10_2010', 'MIGRATION'),
('Y50.1', 'Opioid receptor antagonists', 'ICD10_2010', 'MIGRATION'),
('Y50.2', 'Methylxanthines, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y50.8', 'Other central nervous system stimulants', 'ICD10_2010', 'MIGRATION'),
('Y50.9', 'Central nervous system stimulant, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y51', 'Drugs primarily affecting the autonomic nervous system', 'ICD10_2010', 'MIGRATION'),
('Y51.0', 'Anticholinesterase agents', 'ICD10_2010', 'MIGRATION'),
('Y51.1', 'Other parasympathomimetics [cholinergics]', 'ICD10_2010', 'MIGRATION'),
('Y51.2', 'Ganglionic blocking drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.3', 'Other parasympatholytics [anticholinergics and antimuscarinics] and spasmolytics, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.4', 'Predominantly alpha-adrenoreceptor agonists, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.5', 'Predominantly beta-adrenoreceptor agonists, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.6', 'Alpha-adrenoreceptor antagonists, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.7', 'Beta-adrenoreceptor antagonists, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.8', 'Centrally acting and adrenergic-neuron-blocking agents, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y51.9', 'Other and unspecified drugs primarily affecting the autonomic nervous system', 'ICD10_2010', 'MIGRATION'),
('Y52', 'Agents primarily affecting the cardiovascular system', 'ICD10_2010', 'MIGRATION'),
('Y52.0', 'Cardiac-stimulant glycosides and drugs of similar action', 'ICD10_2010', 'MIGRATION'),
('Y52.1', 'Calcium-channel blockers', 'ICD10_2010', 'MIGRATION'),
('Y52.2', 'Other antidysrhythmic drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y52.3', 'Coronary vasodilators, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y52.4', 'Angiotensin-converting-enzyme inhibitors', 'ICD10_2010', 'MIGRATION'),
('Y52.5', 'Other antihypertensive drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y52.6', 'Antihyperlipidaemic and antiarteriosclerotic drugs', 'ICD10_2010', 'MIGRATION'),
('Y52.7', 'Peripheral vasodilators', 'ICD10_2010', 'MIGRATION'),
('Y52.8', 'Antivaricose drugs, including sclerosing agents', 'ICD10_2010', 'MIGRATION'),
('Y52.9', 'Other and unspecified agents primarily affecting the cardiovascular system', 'ICD10_2010', 'MIGRATION'),
('Y53', 'Agents primarily affecting the gastrointestinal system', 'ICD10_2010', 'MIGRATION'),
('Y53.0', 'Histamine H2-receptor antagonists', 'ICD10_2010', 'MIGRATION'),
('Y53.1', 'Other antacids and anti-gastric-secretion drugs', 'ICD10_2010', 'MIGRATION'),
('Y53.2', 'Stimulant laxatives', 'ICD10_2010', 'MIGRATION'),
('Y53.3', 'Saline and osmotic laxatives', 'ICD10_2010', 'MIGRATION'),
('Y53.4', 'Other laxatives', 'ICD10_2010', 'MIGRATION'),
('Y53.5', 'Digestants', 'ICD10_2010', 'MIGRATION'),
('Y53.6', 'Antidiarrhoeal drugs', 'ICD10_2010', 'MIGRATION'),
('Y53.7', 'Emetics', 'ICD10_2010', 'MIGRATION'),
('Y53.8', 'Other agents primarily affecting the gastrointestinal system', 'ICD10_2010', 'MIGRATION'),
('Y53.9', 'Agent primarily affecting the gastrointestinal system, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y54', 'Agents primarily affecting water-balance and mineral and uric acid metabolism', 'ICD10_2010', 'MIGRATION'),
('Y54.0', 'Mineralocorticoids', 'ICD10_2010', 'MIGRATION'),
('Y54.1', 'Mineralocorticoid antagonists [aldosterone antagonists]', 'ICD10_2010', 'MIGRATION'),
('Y54.2', 'Carbonic-anhydrase inhibitors', 'ICD10_2010', 'MIGRATION'),
('Y54.3', 'Benzothiadiazine derivatives', 'ICD10_2010', 'MIGRATION'),
('Y54.4', 'Loop [high-ceiling] diuretics', 'ICD10_2010', 'MIGRATION'),
('Y54.5', 'Other diuretics', 'ICD10_2010', 'MIGRATION'),
('Y54.6', 'Electrolytic, caloric and water-balance agents', 'ICD10_2010', 'MIGRATION'),
('Y54.7', 'Agents affecting calcification', 'ICD10_2010', 'MIGRATION'),
('Y54.8', 'Agents affecting uric acid metabolism', 'ICD10_2010', 'MIGRATION'),
('Y54.9', 'Mineral salts, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y55', 'Agents primarily acting on smooth and skeletal muscles and the respiratory system', 'ICD10_2010', 'MIGRATION'),
('Y55.0', 'Oxytocic drugs', 'ICD10_2010', 'MIGRATION'),
('Y55.1', 'Skeletal muscle relaxants [neuromuscular blocking agents]', 'ICD10_2010', 'MIGRATION'),
('Y55.2', 'Other and unspecified agents primarily acting on muscles', 'ICD10_2010', 'MIGRATION'),
('Y55.3', 'Antitussives', 'ICD10_2010', 'MIGRATION'),
('Y55.4', 'Expectorants', 'ICD10_2010', 'MIGRATION'),
('Y55.5', 'Anti-common-cold drugs', 'ICD10_2010', 'MIGRATION'),
('Y55.6', 'Antiasthmatics, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y55.7', 'Other and unspecified agents primarily acting on the respiratory system', 'ICD10_2010', 'MIGRATION'),
('Y56', 'Topical agents primarily affecting skin and mucous membrane and ophthalmological, otorhinolaryngological and dental drugs', 'ICD10_2010', 'MIGRATION'),
('Y56.0', 'Local antifungal, anti-infective and anti-inflammatory drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y56.1', 'Antipruritics', 'ICD10_2010', 'MIGRATION'),
('Y56.2', 'Local astringents and local detergents', 'ICD10_2010', 'MIGRATION'),
('Y56.3', 'Emollients, demulcents and protectants', 'ICD10_2010', 'MIGRATION'),
('Y56.4', 'Keratolytics, keratoplastics and other hair treatment drugs and preparations', 'ICD10_2010', 'MIGRATION'),
('Y56.5', 'Ophthalmological drugs and preparations', 'ICD10_2010', 'MIGRATION'),
('Y56.6', 'Otorhinolaryngological drugs and preparations', 'ICD10_2010', 'MIGRATION'),
('Y56.7', 'Dental drugs, topically applied', 'ICD10_2010', 'MIGRATION'),
('Y56.8', 'Other topical agents', 'ICD10_2010', 'MIGRATION'),
('Y56.9', 'Topical agent, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y57', 'Other and unspecified drugs and medicaments', 'ICD10_2010', 'MIGRATION'),
('Y57.0', 'Appetite depressants [anorectics]', 'ICD10_2010', 'MIGRATION'),
('Y57.1', 'Lipotropic drugs', 'ICD10_2010', 'MIGRATION'),
('Y57.2', 'Antidotes and chelating agents, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y57.3', 'Alcohol deterrents', 'ICD10_2010', 'MIGRATION'),
('Y57.4', 'Pharmaceutical excipients', 'ICD10_2010', 'MIGRATION'),
('Y57.5', 'X-ray contrast media', 'ICD10_2010', 'MIGRATION'),
('Y57.6', 'Other diagnostic agents', 'ICD10_2010', 'MIGRATION'),
('Y57.7', 'Vitamins, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y57.8', 'Other drugs and medicaments', 'ICD10_2010', 'MIGRATION'),
('Y57.9', 'Drug or medicament, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y58', 'Bacterial vaccines', 'ICD10_2010', 'MIGRATION'),
('Y58.0', 'BCG vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.1', 'Typhoid and paratyphoid vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.2', 'Cholera vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.3', 'Plague vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.4', 'Tetanus vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.5', 'Diphtheria vaccine', 'ICD10_2010', 'MIGRATION'),
('Y58.6', 'Pertussis vaccine, including combinations with a pertussis component', 'ICD10_2010', 'MIGRATION'),
('Y58.8', 'Mixed bacterial vaccines, except combinations with a pertussis component', 'ICD10_2010', 'MIGRATION'),
('Y58.9', 'Other and unspecified bacterial vaccines', 'ICD10_2010', 'MIGRATION'),
('Y59', 'Other and unspecified vaccines and biological substances', 'ICD10_2010', 'MIGRATION'),
('Y59.0', 'Viral vaccines', 'ICD10_2010', 'MIGRATION'),
('Y59.1', 'Rickettsial vaccines', 'ICD10_2010', 'MIGRATION'),
('Y59.2', 'Protozoal vaccines', 'ICD10_2010', 'MIGRATION'),
('Y59.3', 'Immunoglobulin', 'ICD10_2010', 'MIGRATION'),
('Y59.8', 'Other specified vaccines and biological substances', 'ICD10_2010', 'MIGRATION'),
('Y59.9', 'Vaccine or biological substance, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y60', 'Unintentional cut, puncture, perforation or haemorrhage during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y60.0', 'During surgical operation', 'ICD10_2010', 'MIGRATION'),
('Y60.1', 'During infusion or transfusion', 'ICD10_2010', 'MIGRATION'),
('Y60.2', 'During kidney dialysis or other perfusion', 'ICD10_2010', 'MIGRATION'),
('Y60.3', 'During injection or immunization', 'ICD10_2010', 'MIGRATION'),
('Y60.4', 'During endoscopic examination', 'ICD10_2010', 'MIGRATION'),
('Y60.5', 'During heart catheterization', 'ICD10_2010', 'MIGRATION'),
('Y60.6', 'During aspiration, puncture and other catheterization', 'ICD10_2010', 'MIGRATION'),
('Y60.7', 'During administration of enema', 'ICD10_2010', 'MIGRATION'),
('Y60.8', 'During other surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y60.9', 'During unspecified surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y61', 'Foreign object accidentally left in body during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y61.0', 'During surgical operation', 'ICD10_2010', 'MIGRATION'),
('Y61.1', 'During infusion or transfusion', 'ICD10_2010', 'MIGRATION'),
('Y61.2', 'During kidney dialysis or other perfusion', 'ICD10_2010', 'MIGRATION'),
('Y61.3', 'During injection or immunization', 'ICD10_2010', 'MIGRATION'),
('Y61.4', 'During endoscopic examination', 'ICD10_2010', 'MIGRATION'),
('Y61.5', 'During heart catheterization', 'ICD10_2010', 'MIGRATION'),
('Y61.6', 'During aspiration, puncture and other catheterization', 'ICD10_2010', 'MIGRATION'),
('Y61.7', 'During removal of catheter or packing', 'ICD10_2010', 'MIGRATION'),
('Y61.8', 'During other surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y61.9', 'During unspecified surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y62', 'Failure of sterile precautions during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y62.0', 'During surgical operation', 'ICD10_2010', 'MIGRATION'),
('Y62.1', 'During infusion or transfusion', 'ICD10_2010', 'MIGRATION'),
('Y62.2', 'During kidney dialysis or other perfusion', 'ICD10_2010', 'MIGRATION'),
('Y62.3', 'During injection or immunization', 'ICD10_2010', 'MIGRATION'),
('Y62.4', 'During endoscopic examination', 'ICD10_2010', 'MIGRATION'),
('Y62.5', 'During heart catheterization', 'ICD10_2010', 'MIGRATION'),
('Y62.6', 'During aspiration, puncture and other catheterization', 'ICD10_2010', 'MIGRATION'),
('Y62.8', 'During other surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y62.9', 'During unspecified surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y63', 'Failure in dosage during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y63.0', 'Excessive amount of blood or other fluid given during transfusion or infusion', 'ICD10_2010', 'MIGRATION'),
('Y63.1', 'Incorrect dilution of fluid used during infusion', 'ICD10_2010', 'MIGRATION'),
('Y63.2', 'Overdose of radiation given during therapy', 'ICD10_2010', 'MIGRATION'),
('Y63.3', 'Inadvertent exposure of patient to radiation during medical care', 'ICD10_2010', 'MIGRATION'),
('Y63.4', 'Failure in dosage in electroshock or insulin-shock therapy', 'ICD10_2010', 'MIGRATION'),
('Y63.5', 'Inappropriate temperature in local application and packing', 'ICD10_2010', 'MIGRATION'),
('Y63.6', 'Nonadministration of necessary drug, medicament or biological substance', 'ICD10_2010', 'MIGRATION'),
('Y63.8', 'Failure in dosage during other surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y63.9', 'Failure in dosage during unspecified surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y64', 'Contaminated medical or biological substances', 'ICD10_2010', 'MIGRATION'),
('Y64.0', 'Contaminated medical or biological substance, transfused or infused', 'ICD10_2010', 'MIGRATION'),
('Y64.1', 'Contaminated medical or biological substance, injected or used for immunization', 'ICD10_2010', 'MIGRATION'),
('Y64.8', 'Contaminated medical or biological substance administered by other means', 'ICD10_2010', 'MIGRATION'),
('Y64.9', 'Contaminated medical or biological substance administered by unspecified means', 'ICD10_2010', 'MIGRATION'),
('Y65', 'Other misadventures during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y65.0', 'Mismatched blood used in transfusion', 'ICD10_2010', 'MIGRATION'),
('Y65.1', 'Wrong fluid used in infusion', 'ICD10_2010', 'MIGRATION'),
('Y65.2', 'Failure in suture or ligature during surgical operation', 'ICD10_2010', 'MIGRATION'),
('Y65.3', 'Endotracheal tube wrongly placed during anaesthetic procedure', 'ICD10_2010', 'MIGRATION'),
('Y65.4', 'Failure to introduce or to remove other tube or instrument', 'ICD10_2010', 'MIGRATION'),
('Y65.5', 'Performance of inappropriate operation', 'ICD10_2010', 'MIGRATION'),
('Y65.8', 'Other specified misadventures during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y66', 'Nonadministration of surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y69', 'Unspecified misadventure during surgical and medical care', 'ICD10_2010', 'MIGRATION'),
('Y70', 'Anaesthesiology devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y70.0', 'Anaesthesiology devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y70.1', 'Anaesthesiology devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y70.2', 'Anaesthesiology devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y70.3', 'Anaesthesiology devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y70.8', 'Anaesthesiology devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y71', 'Cardiovascular devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y71.0', 'Cardiovascular devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y71.1', 'Cardiovascular devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y71.2', 'Cardiovascular devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y71.3', 'Cardiovascular devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y71.8', 'Cardiovascular devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y72', 'Otorhinolaryngological devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y72.0', 'Otorhinolaryngological devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y72.1', 'Otorhinolaryngological devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y72.2', 'Otorhinolaryngological devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y72.3', 'Otorhinolaryngological devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y72.8', 'Otorhinolaryngological devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y73', 'Gastroenterology and urology devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y73.0', 'Gastroenterology and urology devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y73.1', 'Gastroenterology and urology devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y73.2', 'Gastroenterology and urology devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y73.3', 'Gastroenterology and urology devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y73.8', 'Gastroenterology and urology devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y74', 'General hospital and personal-use devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y74.0', 'General hospital and personal-use devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y74.1', 'General hospital and personal-use devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y74.2', 'General hospital and personal-use devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y74.3', 'General hospital and personal-use devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y74.8', 'General hospital and personal-use devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y75', 'Neurological devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y75.0', 'Neurological devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y75.1', 'Neurological devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y75.2', 'Neurological devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y75.3', 'Neurological devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y75.8', 'Neurological devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y76', 'Obstetric and gynaecological devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y76.0', 'Obstetric and gynaecological devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y76.1', 'Obstetric and gynaecological devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y76.2', 'Obstetric and gynaecological devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y76.3', 'Obstetric and gynaecological devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y76.8', 'Obstetric and gynaecological devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y77', 'Ophthalmic devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y77.0', 'Ophthalmic devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y77.1', 'Ophthalmic devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y77.2', 'Ophthalmic devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y77.3', 'Ophthalmic devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y77.8', 'Ophthalmic devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y78', 'Radiological devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y78.0', 'Radiological devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y78.1', 'Radiological devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y78.2', 'Radiological devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y78.3', 'Radiological devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y78.8', 'Radiological devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y79', 'Orthopaedic devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y79.0', 'Orthopaedic devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y79.1', 'Orthopaedic devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y79.2', 'Orthopaedic devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y79.3', 'Orthopaedic devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y79.8', 'Orthopaedic devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y80', 'Physical medicine devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y80.0', 'Physical medicine devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y80.1', 'Physical medicine devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y80.2', 'Physical medicine devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y80.3', 'Physical medicine devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y80.8', 'Physical medicine devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y81', 'General- and plastic-surgery devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y81.0', 'General- and plastic-surgery devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y81.1', 'General- and plastic-surgery devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y81.2', 'General- and plastic-surgery devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y81.3', 'General- and plastic-surgery devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y81.8', 'General- and plastic-surgery devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y82', 'Other and unspecified medical devices associated with adverse incidents', 'ICD10_2010', 'MIGRATION'),
('Y82.0', 'Other and unspecified medical devices associated with adverse incidents: Diagnostic and monitoring devices', 'ICD10_2010', 'MIGRATION'),
('Y82.1', 'Other and unspecified medical devices associated with adverse incidents: Therapeutic (nonsurgical) and rehabilitative devices', 'ICD10_2010', 'MIGRATION'),
('Y82.2', 'Other and unspecified medical devices associated with adverse incidents: Prosthetic and other implants, materials and accessory devices', 'ICD10_2010', 'MIGRATION'),
('Y82.3', 'Other and unspecified medical devices associated with adverse incidents: Surgical instruments, materials and devices (including sutures)', 'ICD10_2010', 'MIGRATION'),
('Y82.8', 'Other and unspecified medical devices associated with adverse incidents: Miscellaneous devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y83', 'Surgical operation and other surgical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure', 'ICD10_2010', 'MIGRATION'),
('Y83.0', 'Surgical operation with transplant of whole organ', 'ICD10_2010', 'MIGRATION'),
('Y83.1', 'Surgical operation with implant of artificial internal device', 'ICD10_2010', 'MIGRATION'),
('Y83.2', 'Surgical operation with anastomosis, bypass or graft', 'ICD10_2010', 'MIGRATION'),
('Y83.3', 'Surgical operation with formation of external stoma', 'ICD10_2010', 'MIGRATION'),
('Y83.4', 'Other reconstructive surgery', 'ICD10_2010', 'MIGRATION'),
('Y83.5', 'Amputation of limb(s)', 'ICD10_2010', 'MIGRATION'),
('Y83.6', 'Removal of other organ (partial) (total)', 'ICD10_2010', 'MIGRATION'),
('Y83.8', 'Other surgical procedures', 'ICD10_2010', 'MIGRATION'),
('Y83.9', 'Surgical procedure, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y84', 'Other medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure', 'ICD10_2010', 'MIGRATION'),
('Y84.0', 'Cardiac catheterization', 'ICD10_2010', 'MIGRATION'),
('Y84.1', 'Kidney dialysis', 'ICD10_2010', 'MIGRATION'),
('Y84.2', 'Radiological procedure and radiotherapy', 'ICD10_2010', 'MIGRATION'),
('Y84.3', 'Shock therapy', 'ICD10_2010', 'MIGRATION'),
('Y84.4', 'Aspiration of fluid', 'ICD10_2010', 'MIGRATION'),
('Y84.5', 'Insertion of gastric or duodenal sound', 'ICD10_2010', 'MIGRATION'),
('Y84.6', 'Urinary catheterization', 'ICD10_2010', 'MIGRATION'),
('Y84.7', 'Blood-sampling', 'ICD10_2010', 'MIGRATION'),
('Y84.8', 'Other medical procedures', 'ICD10_2010', 'MIGRATION'),
('Y84.9', 'Medical procedure, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y85', 'Sequelae of transport accidents', 'ICD10_2010', 'MIGRATION'),
('Y85.0', 'Sequelae of motor-vehicle accident', 'ICD10_2010', 'MIGRATION'),
('Y85.9', 'Sequelae of other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('Y86', 'Sequelae of other accidents', 'ICD10_2010', 'MIGRATION'),
('Y87', 'Sequelae of intentional self-harm, assault and events of undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y87.0', 'Sequelae of intentional self-harm', 'ICD10_2010', 'MIGRATION'),
('Y87.1', 'Sequelae of assault', 'ICD10_2010', 'MIGRATION'),
('Y87.2', 'Sequelae of events of undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y88', 'Sequelae with surgical and medical care as external cause', 'ICD10_2010', 'MIGRATION'),
('Y88.0', 'Sequelae of adverse effects caused by drugs, medicaments and biological substances in therapeutic use', 'ICD10_2010', 'MIGRATION'),
('Y88.1', 'Sequelae of misadventures to patients during surgical and medical procedures', 'ICD10_2010', 'MIGRATION'),
('Y88.2', 'Sequelae of adverse incidents associated with medical devices in diagnostic and therapeutic use', 'ICD10_2010', 'MIGRATION'),
('Y88.3', 'Sequelae of surgical and medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure', 'ICD10_2010', 'MIGRATION'),
('Y89', 'Sequelae of other external causes', 'ICD10_2010', 'MIGRATION'),
('Y89.0', 'Sequelae of legal intervention', 'ICD10_2010', 'MIGRATION'),
('Y89.1', 'Sequelae of war operations', 'ICD10_2010', 'MIGRATION'),
('Y89.9', 'Sequelae of unspecified external cause', 'ICD10_2010', 'MIGRATION'),
('Y90', 'Evidence of alcohol involvement determined by blood alcohol level', 'ICD10_2010', 'MIGRATION'),
('Y90.0', 'Blood alcohol level of less than 20 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.1', 'Blood alcohol level of 20-39 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.2', 'Blood alcohol level of 40-59 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.3', 'Blood alcohol level of 60-79 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.4', 'Blood alcohol level of 80-99 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.5', 'Blood alcohol level of 100-119 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.6', 'Blood alcohol level of 120-199 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.7', 'Blood alcohol level of 200-239 mg/100 ml', 'ICD10_2010', 'MIGRATION'),
('Y90.8', 'Blood alcohol level of 240 mg/100 ml or more', 'ICD10_2010', 'MIGRATION'),
('Y90.9', 'Presence of alcohol in blood, level not specified', 'ICD10_2010', 'MIGRATION'),
('Y91', 'Evidence of alcohol involvement determined by level of intoxication', 'ICD10_2010', 'MIGRATION'),
('Y91.0', 'Mild alcohol intoxication', 'ICD10_2010', 'MIGRATION'),
('Y91.1', 'Moderate alcohol intoxication', 'ICD10_2010', 'MIGRATION'),
('Y91.2', 'Severe alcohol intoxication', 'ICD10_2010', 'MIGRATION'),
('Y91.3', 'Very severe alcohol intoxication', 'ICD10_2010', 'MIGRATION'),
('Y91.9', 'Alcohol involvement, not otherwise specified', 'ICD10_2010', 'MIGRATION'),
('Y95', 'Nosocomial condition', 'ICD10_2010', 'MIGRATION'),
('Y96', 'Work-related condition', 'ICD10_2010', 'MIGRATION'),
('Y97', 'Environmental-pollution-related condition', 'ICD10_2010', 'MIGRATION'),
('Y98', 'Lifestyle-related condition', 'ICD10_2010', 'MIGRATION'),
('Z00', 'General examination and investigation of persons without complaint and reported diagnosis', 'ICD10_2010', 'MIGRATION'),
('Z00.0', 'General medical examination', 'ICD10_2010', 'MIGRATION'),
('Z00.1', 'Routine child health examination', 'ICD10_2010', 'MIGRATION'),
('Z00.2', 'Examination for period of rapid growth in childhood', 'ICD10_2010', 'MIGRATION'),
('Z00.3', 'Examination for adolescent development state', 'ICD10_2010', 'MIGRATION'),
('Z00.4', 'General psychiatric examination, nec', 'ICD10_2010', 'MIGRATION'),
('Z00.5', 'Examination of potential donor of organ and tissue', 'ICD10_2010', 'MIGRATION'),
('Z00.6', 'Exam normal comparison and control in clin research program', 'ICD10_2010', 'MIGRATION'),
('Z00.8', 'Other general examinations', 'ICD10_2010', 'MIGRATION'),
('Z01', 'Other special examinations and investigations of persons without complaint or reported diagnosis', 'ICD10_2010', 'MIGRATION'),
('Z01.0', 'Examination of eyes and vision', 'ICD10_2010', 'MIGRATION'),
('Z01.1', 'Examination of ears and hearing', 'ICD10_2010', 'MIGRATION'),
('Z01.2', 'Dental examination', 'ICD10_2010', 'MIGRATION'),
('Z01.3', 'Examination of blood pressure', 'ICD10_2010', 'MIGRATION'),
('Z01.4', 'Gynaecological examination (general)(routine)', 'ICD10_2010', 'MIGRATION'),
('Z01.5', 'Diagnostic skin and sensitization tests', 'ICD10_2010', 'MIGRATION'),
('Z01.6', 'Radiological examination, nec', 'ICD10_2010', 'MIGRATION'),
('Z01.7', 'Laboratory examination', 'ICD10_2010', 'MIGRATION'),
('Z01.8', 'Other specified special examinations', 'ICD10_2010', 'MIGRATION'),
('Z01.9', 'Special examination, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z02', 'Examination and encounter for administrative purposes', 'ICD10_2010', 'MIGRATION'),
('Z02.0', 'Examination for admission to educational institution', 'ICD10_2010', 'MIGRATION'),
('Z02.1', 'Pre-employment examination', 'ICD10_2010', 'MIGRATION'),
('Z02.2', 'Examination for admission to residential institutions', 'ICD10_2010', 'MIGRATION'),
('Z02.3', 'Examination for recruitment to armed forces', 'ICD10_2010', 'MIGRATION'),
('Z02.4', 'Examination for driving licence', 'ICD10_2010', 'MIGRATION'),
('Z02.5', 'Examination for participation in sport', 'ICD10_2010', 'MIGRATION'),
('Z02.6', 'Examination for insurance purposes', 'ICD10_2010', 'MIGRATION'),
('Z02.7', 'Issue of medical certificate', 'ICD10_2010', 'MIGRATION'),
('Z02.8', 'Other examinations for administrative purposes', 'ICD10_2010', 'MIGRATION'),
('Z02.9', 'Examination for administrative purposes, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z03', 'Medical observation and evaluation for suspected diseases and conditions', 'ICD10_2010', 'MIGRATION'),
('Z03.0', 'Observation for suspected tuberculosis', 'ICD10_2010', 'MIGRATION'),
('Z03.1', 'Observation for suspected malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z03.2', 'Observation for suspected mental and behavioural disorders', 'ICD10_2010', 'MIGRATION'),
('Z03.3', 'Observation for suspected nervous system disorder', 'ICD10_2010', 'MIGRATION'),
('Z03.4', 'Observation for suspected myocardial infarction', 'ICD10_2010', 'MIGRATION'),
('Z03.5', 'Observation for other suspected cardiovascular diseases', 'ICD10_2010', 'MIGRATION'),
('Z03.6', 'Observation for suspected toxic effect from ingested substances', 'ICD10_2010', 'MIGRATION'),
('Z03.8', 'Observation for other suspected diseases and conditions', 'ICD10_2010', 'MIGRATION'),
('Z03.9', 'Observation for suspected disease or condition, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z04', 'Examination and observation for other reasons', 'ICD10_2010', 'MIGRATION'),
('Z04.0', 'Blood-alcohol and blood-drug test', 'ICD10_2010', 'MIGRATION'),
('Z04.1', 'Examination and observation following transport accident', 'ICD10_2010', 'MIGRATION'),
('Z04.2', 'Examination and observation following work accident', 'ICD10_2010', 'MIGRATION'),
('Z04.3', 'Examination and observation following other accident', 'ICD10_2010', 'MIGRATION'),
('Z04.4', 'Exam and observation following alleged rape and seduction', 'ICD10_2010', 'MIGRATION'),
('Z04.5', 'Examination and observation following other inflicted injury', 'ICD10_2010', 'MIGRATION'),
('Z04.6', 'General psychiatric examination, requested by authority', 'ICD10_2010', 'MIGRATION'),
('Z04.8', 'Examination and observation for other specified reasons', 'ICD10_2010', 'MIGRATION'),
('Z04.9', 'Examination and observation for unspecified reason', 'ICD10_2010', 'MIGRATION'),
('Z08', 'Follow-up examination after treatment for malignant neoplasms', 'ICD10_2010', 'MIGRATION'),
('Z08.0', 'Follow-up examination after surgery for malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z08.1', 'Follow-up examination after radiotherapy for malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z08.2', 'Follow-up examination after chemotherapy for malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z08.7', 'Follow-up examination after combined treatment for malig neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z08.8', 'Follow-up examination after other treatment for malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z08.9', 'Follow-up examination after unspecified treatment for malignant neoplasm', 'ICD10_2010', 'MIGRATION'),
('Z09', 'Follow-up examination after treatment for conditions other than malignant neoplasms', 'ICD10_2010', 'MIGRATION'),
('Z09.0', 'Follow-up examination after surgery for other conditions', 'ICD10_2010', 'MIGRATION'),
('Z09.1', 'Follow-up examination after radiotherapy for oth conditions', 'ICD10_2010', 'MIGRATION'),
('Z09.2', 'Follow-up examination after chemotherapy for oth conditions', 'ICD10_2010', 'MIGRATION'),
('Z09.3', 'Follow-up examination after psychotherapy', 'ICD10_2010', 'MIGRATION'),
('Z09.4', 'Follow-up examination after treatment of fracture', 'ICD10_2010', 'MIGRATION'),
('Z09.7', 'Follow-up exam after combined treatment for other conditions', 'ICD10_2010', 'MIGRATION'),
('Z09.8', 'Follow-up exam after other treatment for other conditions', 'ICD10_2010', 'MIGRATION'),
('Z09.9', 'Follow-up exam after unspecified treatment for other conditions', 'ICD10_2010', 'MIGRATION'),
('Z10', 'Routine general health check-up of defined subpopulation', 'ICD10_2010', 'MIGRATION'),
('Z10.0', 'Occupational health examination', 'ICD10_2010', 'MIGRATION'),
('Z10.1', 'Routine gen health check-up of inhabitants of institutions', 'ICD10_2010', 'MIGRATION'),
('Z10.2', 'Routine general health check-up of armed forces', 'ICD10_2010', 'MIGRATION'),
('Z10.3', 'Routine general health check-up of sports teams', 'ICD10_2010', 'MIGRATION'),
('Z10.8', 'Routine general health check-up of other defined subpopulations', 'ICD10_2010', 'MIGRATION'),
('Z11', 'Special screening examination for infectious and parasitic diseases', 'ICD10_2010', 'MIGRATION'),
('Z11.0', 'Special screening examination for intestinal infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z11.1', 'Special screening examination for respiratory tuberculosis', 'ICD10_2010', 'MIGRATION'),
('Z11.2', 'Special screening examination for other bacterial diseases', 'ICD10_2010', 'MIGRATION'),
('Z11.3', 'Special screening examination infection with predominantly sexual mode transmis', 'ICD10_2010', 'MIGRATION'),
('Z11.4', 'Special screening examination for human immunodeficiency virus [hiv]', 'ICD10_2010', 'MIGRATION'),
('Z11.5', 'Special screening examination for other viral diseases', 'ICD10_2010', 'MIGRATION'),
('Z11.6', 'Special screening examination for oth protozoal dis and helminthiases', 'ICD10_2010', 'MIGRATION'),
('Z11.8', 'Special screening examination for other infectious and parasitic diseases', 'ICD10_2010', 'MIGRATION'),
('Z11.9', 'Special screening examination for infectious and parasitic disease unspecified', 'ICD10_2010', 'MIGRATION'),
('Z12', 'Special screening examination for neoplasms', 'ICD10_2010', 'MIGRATION'),
('Z12.0', 'Special screening examination for neoplasm of stomach', 'ICD10_2010', 'MIGRATION'),
('Z12.1', 'Special screening examination for neoplasm of intestinal tract', 'ICD10_2010', 'MIGRATION'),
('Z12.2', 'Special screening examination for neoplasm of respiratory organs', 'ICD10_2010', 'MIGRATION'),
('Z12.3', 'Special screening examination for neoplasm of breast', 'ICD10_2010', 'MIGRATION'),
('Z12.4', 'Special screening examination for neoplasm of cervix', 'ICD10_2010', 'MIGRATION'),
('Z12.5', 'Special screening examination for neoplasm of prostate', 'ICD10_2010', 'MIGRATION'),
('Z12.6', 'Special screening examination for neoplasm of bladder', 'ICD10_2010', 'MIGRATION'),
('Z12.8', 'Special screening examination for neoplasms of other sites', 'ICD10_2010', 'MIGRATION'),
('Z12.9', 'Special screening examination for neoplasm, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z13', 'Special screening examination for other diseases and disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.0', 'Special screening examination disease blood and blood forming organs and certain disoders involving the immune mechanism', 'ICD10_2010', 'MIGRATION'),
('Z13.1', 'Special screening examination for diabetes mellitus', 'ICD10_2010', 'MIGRATION'),
('Z13.2', 'Special screening examination for nutritional disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.3', 'Special screening examination for mental and behavioural disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.4', 'Special screening examination certain development disorders in childhood', 'ICD10_2010', 'MIGRATION'),
('Z13.5', 'Special screening examination for eye and ear disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.6', 'Special screening examination for cardiovascular disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.7', 'Special screening examination for congenital malformations, deformations and chromosomal abnormalities', 'ICD10_2010', 'MIGRATION'),
('Z13.8', 'Special screening examination for other specified diseases and disorders', 'ICD10_2010', 'MIGRATION'),
('Z13.9', 'Special screening examination, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z20', 'Contact with and exposure to communicable diseases', 'ICD10_2010', 'MIGRATION'),
('Z20.0', 'Contact with and exposure to intestinal infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z20.1', 'Contact with and exposure to tuberculosis', 'ICD10_2010', 'MIGRATION'),
('Z20.2', 'Contact with and exposure infection with a predominantly sex mode transmission', 'ICD10_2010', 'MIGRATION'),
('Z20.3', 'Contact with and exposure to rabies', 'ICD10_2010', 'MIGRATION'),
('Z20.4', 'Contact with and exposure to rubella', 'ICD10_2010', 'MIGRATION'),
('Z20.5', 'Contact with and exposure to viral hepatitis', 'ICD10_2010', 'MIGRATION'),
('Z20.6', 'Contact with and exposure to human immunodefic virus [HIV]', 'ICD10_2010', 'MIGRATION'),
('Z20.7', 'Contact with and exposure pediculosis acariasis and other infestations', 'ICD10_2010', 'MIGRATION'),
('Z20.8', 'Contact with and exposure to other communicable diseases', 'ICD10_2010', 'MIGRATION'),
('Z20.9', 'Contact with and exposure to unspecified communicable disease', 'ICD10_2010', 'MIGRATION'),
('Z21', 'Asymptomatic human immunodefic virus [hiv] infect status', 'ICD10_2010', 'MIGRATION'),
('Z22', 'Carrier of infectious disease', 'ICD10_2010', 'MIGRATION'),
('Z22.0', 'Carrier of typhoid', 'ICD10_2010', 'MIGRATION'),
('Z22.1', 'Carrier of other intestinal infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z22.2', 'Carrier of diphtheria', 'ICD10_2010', 'MIGRATION'),
('Z22.3', 'Carrier of other specified bacterial diseases', 'ICD10_2010', 'MIGRATION'),
('Z22.4', 'Carrier of infections with a predom sexual mode of transmission', 'ICD10_2010', 'MIGRATION'),
('Z22.5', 'Carrier of viral hepatitis', 'ICD10_2010', 'MIGRATION'),
('Z22.6', 'Carrier of human T-lymphotropic virus type-1 [HTLV-1] infection', 'ICD10_2010', 'MIGRATION'),
('Z22.8', 'Carrier of other infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z22.9', 'Carrier of infectious disease, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z23', 'Need for immunization against single bacterial diseases', 'ICD10_2010', 'MIGRATION'),
('Z23.0', 'Need for immunization against cholera alone', 'ICD10_2010', 'MIGRATION'),
('Z23.1', 'Need for immuniz against typhoid-paratyphoid alone [TAB]', 'ICD10_2010', 'MIGRATION'),
('Z23.2', 'Need for immunization against tuberculosis [BCG]', 'ICD10_2010', 'MIGRATION'),
('Z23.3', 'Need for immunization against plague', 'ICD10_2010', 'MIGRATION'),
('Z23.4', 'Need for immunization against tularaemia', 'ICD10_2010', 'MIGRATION'),
('Z23.5', 'Need for immunization against tetanus alone', 'ICD10_2010', 'MIGRATION'),
('Z23.6', 'Need for immunization against diphtheria alone', 'ICD10_2010', 'MIGRATION'),
('Z23.7', 'Need for immunization against pertussis alone', 'ICD10_2010', 'MIGRATION'),
('Z23.8', 'Need for immunization against other single bacterial diseases', 'ICD10_2010', 'MIGRATION'),
('Z24', 'Need for immunization against certain single viral diseases', 'ICD10_2010', 'MIGRATION'),
('Z24.0', 'Need for immunization against poliomyelitis', 'ICD10_2010', 'MIGRATION'),
('Z24.1', 'Need for immunization against arthropod-borne viral encephalitis', 'ICD10_2010', 'MIGRATION'),
('Z24.2', 'Need for immunization against rabies', 'ICD10_2010', 'MIGRATION'),
('Z24.3', 'Need for immunization against yellow fever', 'ICD10_2010', 'MIGRATION'),
('Z24.4', 'Need for immunization against measles alone', 'ICD10_2010', 'MIGRATION'),
('Z24.5', 'Need for immunization against rubella alone', 'ICD10_2010', 'MIGRATION'),
('Z24.6', 'Need for immunization against viral hepatitis', 'ICD10_2010', 'MIGRATION'),
('Z25', 'Need for immunization against other single viral diseases', 'ICD10_2010', 'MIGRATION'),
('Z25.0', 'Need for immunization against mumps alone', 'ICD10_2010', 'MIGRATION'),
('Z25.1', 'Need for immunization against influenza', 'ICD10_2010', 'MIGRATION'),
('Z25.8', 'Need for immunization against oth specified single viral diseases', 'ICD10_2010', 'MIGRATION'),
('Z26', 'Need for immunization against other single infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z26.0', 'Need for immunization against leishmaniasis', 'ICD10_2010', 'MIGRATION'),
('Z26.8', 'Need for immunization against other specified single infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z26.9', 'Need for immunization against unspecified infectious disease', 'ICD10_2010', 'MIGRATION'),
('Z27', 'Need for immunization against combinations of infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z27.0', 'Need for immunization against cholera with typhoid-paratyphoid [cholera + TAB]', 'ICD10_2010', 'MIGRATION'),
('Z27.1', 'Need for immunization against diphtheria-tetanus-pertussis combined [DTP]', 'ICD10_2010', 'MIGRATION'),
('Z27.2', 'Need for immunization against diphtheria-tetanus-pertussis with typhoid-paratyph [DTP + TAB]', 'ICD10_2010', 'MIGRATION'),
('Z27.3', 'Need for immunization against diphtheria-tetanus-pertussis with poliomyelitis [DTP + polio]', 'ICD10_2010', 'MIGRATION'),
('Z27.4', 'Need for immunization against measles-mumps-rubella [MMR]', 'ICD10_2010', 'MIGRATION'),
('Z27.8', 'Need for immunization against other combinations of infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z27.9', 'Need for immunization against unspec combs of infectious diseases', 'ICD10_2010', 'MIGRATION'),
('Z28', 'Immunization not carried out', 'ICD10_2010', 'MIGRATION'),
('Z28.0', 'Immunization not carried out because of contraindication', 'ICD10_2010', 'MIGRATION'),
('Z28.1', 'Immunization not carried out because of patient''s decision for reason of belief or  group pressure', 'ICD10_2010', 'MIGRATION'),
('Z28.2', 'Immunization not carried out because patient''s decision for other unspecified reasons', 'ICD10_2010', 'MIGRATION'),
('Z28.8', 'Immunization not carried out for other reasons', 'ICD10_2010', 'MIGRATION'),
('Z28.9', 'Immunization not carried out for unspecified reason', 'ICD10_2010', 'MIGRATION'),
('Z29', 'Need for other prophylactic measures', 'ICD10_2010', 'MIGRATION'),
('Z29.0', 'Isolation', 'ICD10_2010', 'MIGRATION'),
('Z29.1', 'Prophylactic immunotherapy', 'ICD10_2010', 'MIGRATION'),
('Z29.2', 'Other prophylactic chemotherapy', 'ICD10_2010', 'MIGRATION'),
('Z29.8', 'Other specified prophylactic measures', 'ICD10_2010', 'MIGRATION'),
('Z29.9', 'Prophylactic measure, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z30', 'Contraceptive management', 'ICD10_2010', 'MIGRATION'),
('Z30.0', 'General counselling and advice on contraception', 'ICD10_2010', 'MIGRATION'),
('Z30.1', 'Insertion of (intrauterine) contraceptive device', 'ICD10_2010', 'MIGRATION'),
('Z30.2', 'Sterilization', 'ICD10_2010', 'MIGRATION'),
('Z30.3', 'Menstrual extraction', 'ICD10_2010', 'MIGRATION'),
('Z30.4', 'Surveillance of contraceptive drugs', 'ICD10_2010', 'MIGRATION'),
('Z30.5', 'Surveillance of (intrauterine) contraceptive device', 'ICD10_2010', 'MIGRATION'),
('Z30.8', 'Other contraceptive management', 'ICD10_2010', 'MIGRATION'),
('Z30.9', 'Contraceptive management, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z31', 'Procreative management', 'ICD10_2010', 'MIGRATION'),
('Z31.0', 'Tuboplasty or vasoplasty after previous sterilization', 'ICD10_2010', 'MIGRATION'),
('Z31.1', 'Artificial insemination', 'ICD10_2010', 'MIGRATION'),
('Z31.2', 'In vitro fertilization', 'ICD10_2010', 'MIGRATION'),
('Z31.3', 'Other assisted fertilization methods', 'ICD10_2010', 'MIGRATION'),
('Z31.4', 'Procreative investigation and testing', 'ICD10_2010', 'MIGRATION'),
('Z31.5', 'Genetic counselling', 'ICD10_2010', 'MIGRATION'),
('Z31.6', 'General counselling and advice on procreation', 'ICD10_2010', 'MIGRATION'),
('Z31.8', 'Other procreative management', 'ICD10_2010', 'MIGRATION'),
('Z31.9', 'Procreative management, unspecified', 'ICD10_2010', 'MIGRATION'),
('Z32', 'Pregnancy examination and test', 'ICD10_2010', 'MIGRATION'),
('Z32.0', 'Pregnancy, not (yet) confirmed', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
