-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('T84.2', 'Mechanical complication of internal fixation device of other bones', 'ICD10_2010', 'MIGRATION'),
('T84.3', 'Mechanical complication other bone devices implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T84.4', 'Mechanical complication of other internal orthopaedic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T84.5', 'Infection and inflammatory reaction due to internal joint pros', 'ICD10_2010', 'MIGRATION'),
('T84.6', 'Infection and inflammatory reaction due internal fixation device [any site]', 'ICD10_2010', 'MIGRATION'),
('T84.7', 'Infection and inflammatory reaction due to other internal orthopedic prosthetic devices, implants and  grafts', 'ICD10_2010', 'MIGRATION'),
('T84.8', 'Other complications of internal orthopaedic prosthtic devices, implants & grafts', 'ICD10_2010', 'MIGRATION'),
('T84.9', 'Unspecified complication of internal othopaedic prosthetic device, implant & graft', 'ICD10_2010', 'MIGRATION'),
('T85', 'Complications of other internal prosthetic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T85.0', 'Mechanical complication of ventricular intracranial (communicating) shunt', 'ICD10_2010', 'MIGRATION'),
('T85.1', 'Mechanical complication implanted electronic stimulator of nervous system', 'ICD10_2010', 'MIGRATION'),
('T85.2', 'Mechanical complication of intraocular lens', 'ICD10_2010', 'MIGRATION'),
('T85.3', 'Mechanical complication of other ocular prosthetic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T85.4', 'Mechanical complication of breast prosthesis and implant', 'ICD10_2010', 'MIGRATION'),
('T85.5', 'Mechanical complication of gastrointestinal prosthetic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T85.6', 'Mechanical complication of other specified internal prosthetic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T85.7', 'Infection inflammatory reaction due to other internal prosthetic devices, implants and grafts', 'ICD10_2010', 'MIGRATION'),
('T85.8', 'Other complications of internal prosthetic devices, implants and  grafts nec', 'ICD10_2010', 'MIGRATION'),
('T85.9', 'Unspecified complication of internal prosthetic device, implant and graft', 'ICD10_2010', 'MIGRATION'),
('T86', 'Failure and rejection of transplanted organs and tissues', 'ICD10_2010', 'MIGRATION'),
('T86.0', 'Bone-marrow transplant rejection', 'ICD10_2010', 'MIGRATION'),
('T86.1', 'Kidney transplant failure and rejection', 'ICD10_2010', 'MIGRATION'),
('T86.2', 'Heart transplant failure and rejection', 'ICD10_2010', 'MIGRATION'),
('T86.3', 'Heart-lung transplant failure and rejection', 'ICD10_2010', 'MIGRATION'),
('T86.4', 'Liver transplant failure and rejection', 'ICD10_2010', 'MIGRATION'),
('T86.8', 'Failure and reject of other transplanted organs and tissues', 'ICD10_2010', 'MIGRATION'),
('T86.9', 'Failure and reject of unspecified transplanted organ and tissue', 'ICD10_2010', 'MIGRATION'),
('T87', 'Complications peculiar to reattachment and amputation', 'ICD10_2010', 'MIGRATION'),
('T87.0', 'Complications of reattached (part of) upper extremity', 'ICD10_2010', 'MIGRATION'),
('T87.1', 'Complications of reattached (part of) lower extremity', 'ICD10_2010', 'MIGRATION'),
('T87.2', 'Complications of other reattached body part', 'ICD10_2010', 'MIGRATION'),
('T87.3', 'Neuroma of amputation stump', 'ICD10_2010', 'MIGRATION'),
('T87.4', 'Infection of amputation stump', 'ICD10_2010', 'MIGRATION'),
('T87.5', 'Necrosis of amputation stump', 'ICD10_2010', 'MIGRATION'),
('T87.6', 'Other and unspecified complications of amputation stump', 'ICD10_2010', 'MIGRATION'),
('T88', 'Other complications of surgical and medical care, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('T88.0', 'Infection following immunization', 'ICD10_2010', 'MIGRATION'),
('T88.1', 'Other complications following immunization nec', 'ICD10_2010', 'MIGRATION'),
('T88.2', 'Shock due to anaesthesia', 'ICD10_2010', 'MIGRATION'),
('T88.3', 'Malignant hyperthermia due to anaesthesia', 'ICD10_2010', 'MIGRATION'),
('T88.4', 'Failed or difficult intubation', 'ICD10_2010', 'MIGRATION'),
('T88.5', 'Other complications of anaesthesia', 'ICD10_2010', 'MIGRATION'),
('T88.6', 'Anaphylactic shock due adverse effect of correct drug or medicament properly administered', 'ICD10_2010', 'MIGRATION'),
('T88.7', 'Unspecified adverse effect of drug or medicament', 'ICD10_2010', 'MIGRATION'),
('T88.8', 'Other specified complications of surgical and medical care nec', 'ICD10_2010', 'MIGRATION'),
('T88.9', 'Complication of surgical and medical care, unspecified', 'ICD10_2010', 'MIGRATION'),
('T90', 'Sequelae of injuries of head', 'ICD10_2010', 'MIGRATION'),
('T90.0', 'Sequelae of superficial injury of head', 'ICD10_2010', 'MIGRATION'),
('T90.1', 'Sequelae of open wound of head', 'ICD10_2010', 'MIGRATION'),
('T90.2', 'Sequelae of fracture of skull and facial bones', 'ICD10_2010', 'MIGRATION'),
('T90.3', 'Sequelae of injury of cranial nerves', 'ICD10_2010', 'MIGRATION'),
('T90.4', 'Sequelae of injury of eye and orbit', 'ICD10_2010', 'MIGRATION'),
('T90.5', 'Sequelae of intracranial injury', 'ICD10_2010', 'MIGRATION'),
('T90.8', 'Sequelae of other specified injuries of head', 'ICD10_2010', 'MIGRATION'),
('T90.9', 'Sequelae of unspecified injury of head', 'ICD10_2010', 'MIGRATION'),
('T91', 'Sequelae of injuries of neck and trunk', 'ICD10_2010', 'MIGRATION'),
('T91.0', 'Sequelae of superficial injury and open wound of neck and trunk', 'ICD10_2010', 'MIGRATION'),
('T91.1', 'Sequelae of fracture of spine', 'ICD10_2010', 'MIGRATION'),
('T91.2', 'Sequelae of other fracture of thorax and pelvis', 'ICD10_2010', 'MIGRATION'),
('T91.3', 'Sequelae of injury of spinal cord', 'ICD10_2010', 'MIGRATION'),
('T91.4', 'Sequelae of injury of intrathoracic organs', 'ICD10_2010', 'MIGRATION'),
('T91.5', 'Sequelae of injury of intra-abdominal and pelvic organs', 'ICD10_2010', 'MIGRATION'),
('T91.8', 'Sequelae of other specified injuries of neck and trunk', 'ICD10_2010', 'MIGRATION'),
('T91.9', 'Sequelae of unspecified injury of neck and trunk', 'ICD10_2010', 'MIGRATION'),
('T92', 'Sequelae of injuries of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.0', 'Sequelae of open wound of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.1', 'Sequelae of fracture of arm', 'ICD10_2010', 'MIGRATION'),
('T92.2', 'Sequelae of fracture at wrist and hand level', 'ICD10_2010', 'MIGRATION'),
('T92.3', 'Sequelae of dislocation, sprain and strain of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.4', 'Sequelae of injury of nerve of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.5', 'Sequelae of injury of muscle and tendon of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.6', 'Sequelae of crushing injury and traumatic amputation of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.8', 'Sequelae of other specified injuries of upper limb', 'ICD10_2010', 'MIGRATION'),
('T92.9', 'Sequelae of unspecified injury of upper limb', 'ICD10_2010', 'MIGRATION'),
('T93', 'Sequelae of injuries of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.0', 'Sequelae of open wound of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.1', 'Sequelae of fracture of femur', 'ICD10_2010', 'MIGRATION'),
('T93.2', 'Sequelae of other fractures of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.3', 'Sequelae of dislocation, sprain and strain of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.4', 'Sequelae of injury of nerve of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.5', 'Sequelae of injury of muscle and tendon of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.6', 'Sequelae of crush injury and traumatic amputation of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.8', 'Sequelae of other specified injuries of lower limb', 'ICD10_2010', 'MIGRATION'),
('T93.9', 'Sequelae of unspecified injury of lower limb', 'ICD10_2010', 'MIGRATION'),
('T94', 'Sequelae of injuries involving multiple and unspecified body regions', 'ICD10_2010', 'MIGRATION'),
('T94.0', 'Sequelae of injuries involving multiple body regions', 'ICD10_2010', 'MIGRATION'),
('T94.1', 'Sequelae of injuries, not specified by body region', 'ICD10_2010', 'MIGRATION'),
('T95', 'Sequelae of burns, corrosions and frostbite', 'ICD10_2010', 'MIGRATION'),
('T95.0', 'Sequelae of burn, corrosion and frostbite of head and neck', 'ICD10_2010', 'MIGRATION'),
('T95.1', 'Sequelae of burn, corrosion and frostbite of trunk', 'ICD10_2010', 'MIGRATION'),
('T95.2', 'Sequelae of burn, corrosion and frostbite of upper limb', 'ICD10_2010', 'MIGRATION'),
('T95.3', 'Sequelae of burn, corrosion and frostbite of lower limb', 'ICD10_2010', 'MIGRATION'),
('T95.4', 'Seq burn and corros class only accord extent body surf involved', 'ICD10_2010', 'MIGRATION'),
('T95.8', 'Sequelae of other specified burn, corrosion and frostbite', 'ICD10_2010', 'MIGRATION'),
('T95.9', 'Sequelae of unspecified burn, corrosion and frostbite', 'ICD10_2010', 'MIGRATION'),
('T96', 'Sequelae of poisoning by drugs medicaments and biological substances', 'ICD10_2010', 'MIGRATION'),
('T97', 'Sequelae of toxic effects substances chiefly nonmedicinal as to source', 'ICD10_2010', 'MIGRATION'),
('T98', 'Sequelae of other and unspecified effects of external causes', 'ICD10_2010', 'MIGRATION'),
('T98.0', 'Sequelae of effects foreign body entering through natural orifice', 'ICD10_2010', 'MIGRATION'),
('T98.1', 'Sequelae of other and unspecified effects of external causes', 'ICD10_2010', 'MIGRATION'),
('T98.2', 'Sequelae of certain early complications of trauma', 'ICD10_2010', 'MIGRATION'),
('T98.3', 'Sequelae of complications of surgical and medical care nec', 'ICD10_2010', 'MIGRATION'),
('U04', 'Severe acute respiratory syndrome [SARS]', 'ICD10_2010', 'MIGRATION'),
('U04.9', 'Severe acute respiratory syndrome [SARS], unspecified', 'ICD10_2010', 'MIGRATION'),
('U80', 'Agent resistant to penicillin and related antibiotics', 'ICD10_2010', 'MIGRATION'),
('U80.0', 'Penicillin resistant agent', 'ICD10_2010', 'MIGRATION'),
('U80.1', 'Methicillin resistant agent', 'ICD10_2010', 'MIGRATION'),
('U80.8', 'Agent resistant to other penicillin-related antibiotic', 'ICD10_2010', 'MIGRATION'),
('U81', 'Agent resistant to vancomycin and related antibiotics', 'ICD10_2010', 'MIGRATION'),
('U81.0', 'Vancomycin resistant agent', 'ICD10_2010', 'MIGRATION'),
('U81.8', 'Agent resistant to other penicillin-related antibiotic', 'ICD10_2010', 'MIGRATION'),
('U88', 'Agent resistant to multiple antibiotics', 'ICD10_2010', 'MIGRATION'),
('U89', 'Agent resistant to other and unspecified antibiotics', 'ICD10_2010', 'MIGRATION'),
('U89.8', 'Agent resistant to other single specified antibiotic', 'ICD10_2010', 'MIGRATION'),
('U89.9', 'Agent resistant to unspecified antibiotic', 'ICD10_2010', 'MIGRATION'),
('V01', 'Pedestrian injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V01.0', 'Pedestrian injured in collision with pedal cycle: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V01.1', 'Pedestrian injured in collision with pedal cycle: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V01.9', 'Pedestrian injured in collision with pedal cycle: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V02', 'Pedestrian injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V02.0', 'Pedestrian injured in collision with two- or three-wheeled motor vehicle: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V02.1', 'Pedestrian injured in collision with two- or three-wheeled motor vehicle: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V02.9', 'Pedestrian injured in collision with two- or three-wheeled motor vehicle: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V03', 'Pedestrian injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V03.0', 'Pedestrian injured in collision with car, pick-up truck or van: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V03.1', 'Pedestrian injured in collision with car, pick-up truck or van: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V03.9', 'Pedestrian injured in collision with car, pick-up truck or van: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V04', 'Pedestrian injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V04.0', 'Pedestrian injured in collision with heavy transport vehicle or bus: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V04.1', 'Pedestrian injured in collision with heavy transport vehicle or bus: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V04.9', 'Pedestrian injured in collision with heavy transport vehicle or bus: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V05', 'Pedestrian injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V05.0', 'Pedestrian injured in collision with railway train or railway vehicle: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V05.1', 'Pedestrian injured in collision with railway train or railway vehicle: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V05.9', 'Pedestrian injured in collision with railway train or railway vehicle: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V06', 'Pedestrian injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V06.0', 'Pedestrian injured in collision with other nonmotor vehicle: Nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V06.1', 'Pedestrian injured in collision with other nonmotor vehicle: Traffic accident', 'ICD10_2010', 'MIGRATION'),
('V06.9', 'Pedestrian injured in collision with other nonmotor vehicle: Unspecified whether traffic or nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V09', 'Pedestrian injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V09.0', 'Pedestrian injured in nontraffic accident involving other and unspecified motor vehicles', 'ICD10_2010', 'MIGRATION'),
('V09.1', 'Pedestrian injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V09.2', 'Pedestrian injured in traffic accident involving other and unspecified motor vehicles', 'ICD10_2010', 'MIGRATION'),
('V09.3', 'Pedestrian injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V09.9', 'Pedestrian injured in unspecified transport accident', 'ICD10_2010', 'MIGRATION'),
('V10', 'Pedal cyclist injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V10.0', 'Pedal cyclist injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V10.1', 'Pedal cyclist injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V10.2', 'Pedal cyclist injured in collision with pedestrian or animal: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V10.3', 'Pedal cyclist injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V10.4', 'Pedal cyclist injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V10.5', 'Pedal cyclist injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V10.9', 'Pedal cyclist injured in collision with pedestrian or animal: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V11', 'Pedal cyclist injured in collision with other pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V11.0', 'Pedal cyclist injured in collision with other pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V11.1', 'Pedal cyclist injured in collision with other pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V11.2', 'Pedal cyclist injured in collision with other pedal cycle: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V11.3', 'Pedal cyclist injured in collision with other pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V11.4', 'Pedal cyclist injured in collision with other pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V11.5', 'Pedal cyclist injured in collision with other pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V11.9', 'Pedal cyclist injured in collision with other pedal cycle: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V12', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V12.0', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V12.1', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V12.2', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V12.3', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V12.4', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V12.5', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V12.9', 'Pedal cyclist injured in collision with two- or three-wheeled motor vehicle: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V13', 'Pedal cyclist injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V13.0', 'Pedal cyclist injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V13.1', 'Pedal cyclist injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V13.2', 'Pedal cyclist injured in collision with car, pick-up truck or van: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V13.3', 'Pedal cyclist injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V13.4', 'Pedal cyclist injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V13.5', 'Pedal cyclist injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V13.9', 'Pedal cyclist injured in collision with car, pick-up truck or van: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V14', 'Pedal cyclist injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V14.0', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V14.1', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V14.2', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V14.3', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V14.4', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V14.5', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V14.9', 'Pedal cyclist injured in collision with heavy transport vehicle or bus: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V15', 'Pedal cyclist injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V15.0', 'Pedal cyclist injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V15.1', 'Pedal cyclist injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V15.2', 'Pedal cyclist injured in collision with railway train or railway vehicle: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V15.3', 'Pedal cyclist injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V15.4', 'Pedal cyclist injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V15.5', 'Pedal cyclist injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V15.9', 'Pedal cyclist injured in collision with railway train or railway vehicle: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V16', 'Pedal cyclist injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V16.0', 'Pedal cyclist injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V16.1', 'Pedal cyclist injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V16.2', 'Pedal cyclist injured in collision with other nonmotor vehicle: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V16.3', 'Pedal cyclist injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V16.4', 'Pedal cyclist injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V16.5', 'Pedal cyclist injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V16.9', 'Pedal cyclist injured in collision with other nonmotor vehicle: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V17', 'Pedal cyclist injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V17.0', 'Pedal cyclist injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V17.1', 'Pedal cyclist injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V17.2', 'Pedal cyclist injured in collision with fixed or stationary object: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V17.3', 'Pedal cyclist injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V17.4', 'Pedal cyclist injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V17.5', 'Pedal cyclist injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V17.9', 'Pedal cyclist injured in collision with fixed or stationary object: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V18', 'Pedal cyclist injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V18.0', 'Pedal cyclist injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V18.1', 'Pedal cyclist injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V18.2', 'Pedal cyclist injured in noncollision transport accident: Unspecified pedal cyclist injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V18.3', 'Pedal cyclist injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V18.4', 'Pedal cyclist injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V18.5', 'Pedal cyclist injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V18.9', 'Pedal cyclist injured in noncollision transport accident: Unspecified pedal cyclist injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V19', 'Pedal cyclist injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V19.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.2', 'Unspecified pedal cyclist injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.3', 'Pedal cyclist [any] injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.6', 'Unspecified pedal cyclist injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V19.8', 'Pedal cyclist [any] injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V19.9', 'Pedal cyclist [any] injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V20', 'Motorcycle rider injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V20.0', 'Motorcycle rider injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V20.1', 'Motorcycle rider injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V20.2', 'Motorcycle rider injured in collision with pedestrian or animal: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V20.3', 'Motorcycle rider injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V20.4', 'Motorcycle rider injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V20.5', 'Motorcycle rider injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V20.9', 'Motorcycle rider injured in collision with pedestrian or animal: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V21', 'Motorcycle rider injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V21.0', 'Motorcycle rider injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V21.1', 'Motorcycle rider injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V21.2', 'Motorcycle rider injured in collision with pedal cycle: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V21.3', 'Motorcycle rider injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V21.4', 'Motorcycle rider injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V21.5', 'Motorcycle rider injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V21.9', 'Motorcycle rider injured in collision with pedal cycle: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V22', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V22.0', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V22.1', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V22.2', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V22.3', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V22.4', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V22.5', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V22.9', 'Motorcycle rider injured in collision with two- or three-wheeled motor vehicle: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V23', 'Motorcycle rider injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V23.0', 'Motorcycle rider injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V23.1', 'Motorcycle rider injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V23.2', 'Motorcycle rider injured in collision with car, pick-up truck or van: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V23.3', 'Motorcycle rider injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V23.4', 'Motorcycle rider injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V23.5', 'Motorcycle rider injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V23.9', 'Motorcycle rider injured in collision with car, pick-up truck or van: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V24', 'Motorcycle rider injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V24.0', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V24.1', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V24.2', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V24.3', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V24.4', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V24.5', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V24.9', 'Motorcycle rider injured in collision with heavy transport vehicle or bus: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V25', 'Motorcycle rider injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V25.0', 'Motorcycle rider injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V25.1', 'Motorcycle rider injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V25.2', 'Motorcycle rider injured in collision with railway train or railway vehicle: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V25.3', 'Motorcycle rider injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V25.4', 'Motorcycle rider injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V25.5', 'Motorcycle rider injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V25.9', 'Motorcycle rider injured in collision with railway train or railway vehicle: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V26', 'Motorcycle rider injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V26.0', 'Motorcycle rider injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V26.1', 'Motorcycle rider injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V26.2', 'Motorcycle rider injured in collision with other nonmotor vehicle: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V26.3', 'Motorcycle rider injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V26.4', 'Motorcycle rider injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V26.5', 'Motorcycle rider injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V26.9', 'Motorcycle rider injured in collision with other nonmotor vehicle: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V27', 'Motorcycle rider injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V27.0', 'Motorcycle rider injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V27.1', 'Motorcycle rider injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V27.2', 'Motorcycle rider injured in collision with fixed or stationary object: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V27.3', 'Motorcycle rider injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V27.4', 'Motorcycle rider injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V27.5', 'Motorcycle rider injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V27.9', 'Motorcycle rider injured in collision with fixed or stationary object: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V28', 'Motorcycle rider injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V28.0', 'Motorcycle rider injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V28.1', 'Motorcycle rider injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V28.2', 'Motorcycle rider injured in noncollision transport accident: Unspecified motorcycle rider injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V28.3', 'Motorcycle rider injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V28.4', 'Motorcycle rider injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V28.5', 'Motorcycle rider injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V28.9', 'Motorcycle rider injured in noncollision transport accident: Unspecified motorcycle rider injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V29', 'Motorcycle rider injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V29.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.2', 'Unspecified motorcycle rider injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.3', 'Motorcycle rider [any] injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.6', 'Unspecified motorcycle rider injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V29.8', 'Motorcycle rider [any] injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V29.9', 'Motorcycle rider [any] injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V30', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V30.0', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.1', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.2', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.3', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.4', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V30.5', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.6', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.7', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V30.9', 'Occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V31', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V31.0', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.1', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.2', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.3', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.4', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V31.5', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.6', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.7', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V31.9', 'Occupant of three-wheeled motor vehicle injured in collision with pedal cycle: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V32', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V32.0', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.1', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.2', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.3', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.4', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V32.5', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.6', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.7', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V32.9', 'Occupant of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V33', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V33.0', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.1', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.2', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.3', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.4', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V33.5', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.6', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.7', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V33.9', 'Occupant of three-wheeled motor vehicle injured in collision with car, pick-up truck or van: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V34', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V34.0', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.1', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.2', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.3', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.4', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V34.5', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.6', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.7', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V34.9', 'Occupant of three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V35', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V35.0', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.1', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.2', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.3', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.4', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V35.5', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.6', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.7', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V35.9', 'Occupant of three-wheeled motor vehicle injured in collision with railway train or railway vehicle: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V36', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V36.0', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.1', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.2', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.3', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.4', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V36.5', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.6', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.7', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V36.9', 'Occupant of three-wheeled motor vehicle injured in collision with other nonmotor vehicle: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V37', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V37.0', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.1', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.2', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.3', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.4', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V37.5', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.6', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.7', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V37.9', 'Occupant of three-wheeled motor vehicle injured in collision with fixed or stationary object: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V38', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V38.0', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.1', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.2', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.3', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Unspecified occupant of three-wheeled motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.4', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V38.5', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.6', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.7', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V38.9', 'Occupant of three-wheeled motor vehicle injured in noncollision transport accident: Unspecified occupant of three-wheeled motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V39', 'Occupant of three-wheeled motor vehicle injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V39.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.2', 'Unspecified occupant of three-wheeled motor vehicle injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.3', 'Occupant [any] of three-wheeled motor vehicle injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.6', 'Unspecified occupant of three-wheeled motor vehicle injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V39.8', 'Occupant [any] of three-wheeled motor vehicle injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V39.9', 'Occupant [any] of three-wheeled motor vehicle injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V40', 'Car occupant injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V40.0', 'Car occupant injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.1', 'Car occupant injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.2', 'Car occupant injured in collision with pedestrian or animal: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.3', 'Car occupant injured in collision with pedestrian or animal: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.4', 'Car occupant injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V40.5', 'Car occupant injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.6', 'Car occupant injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.7', 'Car occupant injured in collision with pedestrian or animal: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V40.9', 'Car occupant injured in collision with pedestrian or animal: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V41', 'Car occupant injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V41.0', 'Car occupant injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.1', 'Car occupant injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.2', 'Car occupant injured in collision with pedal cycle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.3', 'Car occupant injured in collision with pedal cycle: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.4', 'Car occupant injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V41.5', 'Car occupant injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.6', 'Car occupant injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.7', 'Car occupant injured in collision with pedal cycle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V41.9', 'Car occupant injured in collision with pedal cycle: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V42', 'Car occupant injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V42.0', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.1', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.2', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.3', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.4', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V42.5', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.6', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.7', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V42.9', 'Car occupant injured in collision with two- or three-wheeled motor vehicle: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V43', 'Car occupant injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V43.0', 'Car occupant injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.1', 'Car occupant injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.2', 'Car occupant injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.3', 'Car occupant injured in collision with car, pick-up truck or van: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.4', 'Car occupant injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V43.5', 'Car occupant injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.6', 'Car occupant injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.7', 'Car occupant injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V43.9', 'Car occupant injured in collision with car, pick-up truck or van: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V44', 'Car occupant injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V44.0', 'Car occupant injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.1', 'Car occupant injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.2', 'Car occupant injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.3', 'Car occupant injured in collision with heavy transport vehicle or bus: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.4', 'Car occupant injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V44.5', 'Car occupant injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.6', 'Car occupant injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.7', 'Car occupant injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V44.9', 'Car occupant injured in collision with heavy transport vehicle or bus: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V45', 'Car occupant injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V45.0', 'Car occupant injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.1', 'Car occupant injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.2', 'Car occupant injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.3', 'Car occupant injured in collision with railway train or railway vehicle: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.4', 'Car occupant injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V45.5', 'Car occupant injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.6', 'Car occupant injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.7', 'Car occupant injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V45.9', 'Car occupant injured in collision with railway train or railway vehicle: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V46', 'Car occupant injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V46.0', 'Car occupant injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.1', 'Car occupant injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.2', 'Car occupant injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.3', 'Car occupant injured in collision with other nonmotor vehicle: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.4', 'Car occupant injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V46.5', 'Car occupant injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.6', 'Car occupant injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.7', 'Car occupant injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V46.9', 'Car occupant injured in collision with other nonmotor vehicle: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V47', 'Car occupant injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V47.0', 'Car occupant injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.1', 'Car occupant injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.2', 'Car occupant injured in collision with fixed or stationary object: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.3', 'Car occupant injured in collision with fixed or stationary object: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.4', 'Car occupant injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V47.5', 'Car occupant injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.6', 'Car occupant injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.7', 'Car occupant injured in collision with fixed or stationary object: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V47.9', 'Car occupant injured in collision with fixed or stationary object: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V48', 'Car occupant injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V48.0', 'Car occupant injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.1', 'Car occupant injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.2', 'Car occupant injured in noncollision transport accident: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.3', 'Car occupant injured in noncollision transport accident: Unspecified car occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.4', 'Car occupant injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V48.5', 'Car occupant injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.6', 'Car occupant injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.7', 'Car occupant injured in noncollision transport accident: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V48.9', 'Car occupant injured in noncollision transport accident: Unspecified car occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V49', 'Car occupant injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
