-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('X50.5', 'Overexertion and strenuous or repetitive movements, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X50.6', 'Overexertion and strenuous or repetitive movements, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X50.7', 'Overexertion and strenuous or repetitive movements, Farm', 'ICD10_2010', 'MIGRATION'),
('X50.8', 'Overexertion and strenuous or repetitive movements, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X50.9', 'Overexertion and strenuous or repetitive movements, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X51', 'Travel and motion', 'ICD10_2010', 'MIGRATION'),
('X51.0', 'Travel and motion, Home', 'ICD10_2010', 'MIGRATION'),
('X51.1', 'Travel and motion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X51.2', 'Travel and motion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X51.3', 'Travel and motion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X51.4', 'Travel and motion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X51.5', 'Travel and motion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X51.6', 'Travel and motion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X51.7', 'Travel and motion, Farm', 'ICD10_2010', 'MIGRATION'),
('X51.8', 'Travel and motion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X51.9', 'Travel and motion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X52', 'Prolonged stay in weightless environment', 'ICD10_2010', 'MIGRATION'),
('X52.0', 'Prolonged stay in weightless environment, Home', 'ICD10_2010', 'MIGRATION'),
('X52.1', 'Prolonged stay in weightless environment, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X52.2', 'Prolonged stay in weightless environment, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X52.3', 'Prolonged stay in weightless environment, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X52.4', 'Prolonged stay in weightless environment, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X52.5', 'Prolonged stay in weightless environment, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X52.6', 'Prolonged stay in weightless environment, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X52.7', 'Prolonged stay in weightless environment, Farm', 'ICD10_2010', 'MIGRATION'),
('X52.8', 'Prolonged stay in weightless environment, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X52.9', 'Prolonged stay in weightless environment, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X53', 'Lack of food', 'ICD10_2010', 'MIGRATION'),
('X53.0', 'Lack of food, Home', 'ICD10_2010', 'MIGRATION'),
('X53.1', 'Lack of food, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X53.2', 'Lack of food, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X53.3', 'Lack of food, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X53.4', 'Lack of food, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X53.5', 'Lack of food, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X53.6', 'Lack of food, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X53.7', 'Lack of food, Farm', 'ICD10_2010', 'MIGRATION'),
('X53.8', 'Lack of food, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X53.9', 'Lack of food, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X54', 'Lack of water', 'ICD10_2010', 'MIGRATION'),
('X54.0', 'Lack of water, Home', 'ICD10_2010', 'MIGRATION'),
('X54.1', 'Lack of water, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X54.2', 'Lack of water, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X54.3', 'Lack of water, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X54.4', 'Lack of water, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X54.5', 'Lack of water, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X54.6', 'Lack of water, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X54.7', 'Lack of water, Farm', 'ICD10_2010', 'MIGRATION'),
('X54.8', 'Lack of water, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X54.9', 'Lack of water, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X57', 'Unspecified privation', 'ICD10_2010', 'MIGRATION'),
('X57.0', 'Unspecified privation, Home', 'ICD10_2010', 'MIGRATION'),
('X57.1', 'Unspecified privation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X57.2', 'Unspecified privation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X57.3', 'Unspecified privation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X57.4', 'Unspecified privation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X57.5', 'Unspecified privation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X57.6', 'Unspecified privation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X57.7', 'Unspecified privation, Farm', 'ICD10_2010', 'MIGRATION'),
('X57.8', 'Unspecified privation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X57.9', 'Unspecified privation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X58', 'Exposure to other specified factors', 'ICD10_2010', 'MIGRATION'),
('X58.0', 'Exposure to other specified factors, Home', 'ICD10_2010', 'MIGRATION'),
('X58.1', 'Exposure to other specified factors, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X58.2', 'Exposure to other specified factors, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X58.3', 'Exposure to other specified factors, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X58.4', 'Exposure to other specified factors, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X58.5', 'Exposure to other specified factors, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X58.6', 'Exposure to other specified factors, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X58.7', 'Exposure to other specified factors, Farm', 'ICD10_2010', 'MIGRATION'),
('X58.8', 'Exposure to other specified factors, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X58.9', 'Exposure to other specified factors, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X59', 'Exposure to unspecified factor', 'ICD10_2010', 'MIGRATION'),
('X59.0', 'Exposure to unspecified factor, Home', 'ICD10_2010', 'MIGRATION'),
('X59.1', 'Exposure to unspecified factor, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X59.2', 'Exposure to unspecified factor, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X59.3', 'Exposure to unspecified factor, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X59.4', 'Exposure to unspecified factor, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X59.5', 'Exposure to unspecified factor, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X59.6', 'Exposure to unspecified factor, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X59.7', 'Exposure to unspecified factor, Farm', 'ICD10_2010', 'MIGRATION'),
('X59.8', 'Exposure to unspecified factor, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X59.9', 'Exposure to unspecified factor, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X60', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics', 'ICD10_2010', 'MIGRATION'),
('X60.0', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Home', 'ICD10_2010', 'MIGRATION'),
('X60.1', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X60.2', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X60.3', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X60.4', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X60.5', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X60.6', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X60.7', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Farm', 'ICD10_2010', 'MIGRATION'),
('X60.8', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X60.9', 'Intentional self-poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X61', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('X61.0', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Home', 'ICD10_2010', 'MIGRATION'),
('X61.1', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X61.2', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X61.3', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X61.4', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X61.5', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X61.6', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X61.7', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Farm', 'ICD10_2010', 'MIGRATION'),
('X61.8', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X61.9', 'Intentional self-poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X62', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('X62.0', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Home', 'ICD10_2010', 'MIGRATION'),
('X62.1', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X62.2', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X62.3', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X62.4', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X62.5', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X62.6', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X62.7', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Farm', 'ICD10_2010', 'MIGRATION'),
('X62.8', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X62.9', 'Intentional self-poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X63', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system', 'ICD10_2010', 'MIGRATION'),
('X63.0', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Home', 'ICD10_2010', 'MIGRATION'),
('X63.1', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X63.2', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X63.3', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X63.4', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X63.5', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X63.6', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X63.7', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Farm', 'ICD10_2010', 'MIGRATION'),
('X63.8', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X63.9', 'Intentional self-poisoning by and exposure to other drugs acting on the autonomic nervous system, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X64', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances', 'ICD10_2010', 'MIGRATION'),
('X64.0', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Home', 'ICD10_2010', 'MIGRATION'),
('X64.1', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X64.2', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X64.3', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X64.4', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X64.5', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X64.6', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X64.7', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X64.8', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X64.9', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X65', 'Intentional self-poisoning by and exposure to alcohol', 'ICD10_2010', 'MIGRATION'),
('X65.0', 'Intentional self-poisoning by and exposure to alcohol, Home', 'ICD10_2010', 'MIGRATION'),
('X65.1', 'Intentional self-poisoning by and exposure to alcohol, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X65.2', 'Intentional self-poisoning by and exposure to alcohol, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X65.3', 'Intentional self-poisoning by and exposure to alcohol, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X65.4', 'Intentional self-poisoning by and exposure to alcohol, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X65.5', 'Intentional self-poisoning by and exposure to alcohol, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X65.6', 'Intentional self-poisoning by and exposure to alcohol, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X65.7', 'Intentional self-poisoning by and exposure to alcohol, Farm', 'ICD10_2010', 'MIGRATION'),
('X65.8', 'Intentional self-poisoning by and exposure to alcohol, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X65.9', 'Intentional self-poisoning by and exposure to alcohol, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X66', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours', 'ICD10_2010', 'MIGRATION'),
('X66.0', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X66.1', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X66.2', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X66.3', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X66.4', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X66.5', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X66.6', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X66.7', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X66.8', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X66.9', 'Intentional self-poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X67', 'Intentional self-poisoning by and exposure to other gases and vapours', 'ICD10_2010', 'MIGRATION'),
('X67.0', 'Intentional self-poisoning by and exposure to other gases and vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X67.1', 'Intentional self-poisoning by and exposure to other gases and vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X67.2', 'Intentional self-poisoning by and exposure to other gases and vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X67.3', 'Intentional self-poisoning by and exposure to other gases and vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X67.4', 'Intentional self-poisoning by and exposure to other gases and vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X67.5', 'Intentional self-poisoning by and exposure to other gases and vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X67.6', 'Intentional self-poisoning by and exposure to other gases and vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X67.7', 'Intentional self-poisoning by and exposure to other gases and vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X67.8', 'Intentional self-poisoning by and exposure to other gases and vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X67.9', 'Intentional self-poisoning by and exposure to other gases and vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X68', 'Intentional self-poisoning by and exposure to pesticides', 'ICD10_2010', 'MIGRATION'),
('X68.0', 'Intentional self-poisoning by and exposure to pesticides, Home', 'ICD10_2010', 'MIGRATION'),
('X68.1', 'Intentional self-poisoning by and exposure to pesticides, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X68.2', 'Intentional self-poisoning by and exposure to pesticides, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X68.3', 'Intentional self-poisoning by and exposure to pesticides, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X68.4', 'Intentional self-poisoning by and exposure to pesticides, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X68.5', 'Intentional self-poisoning by and exposure to pesticides, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X68.6', 'Intentional self-poisoning by and exposure to pesticides, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X68.7', 'Intentional self-poisoning by and exposure to pesticides, Farm', 'ICD10_2010', 'MIGRATION'),
('X68.8', 'Intentional self-poisoning by and exposure to pesticides, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X68.9', 'Intentional self-poisoning by and exposure to pesticides, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X69', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances', 'ICD10_2010', 'MIGRATION'),
('X69.0', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Home', 'ICD10_2010', 'MIGRATION'),
('X69.1', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X69.2', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X69.3', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X69.4', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X69.5', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X69.6', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X69.7', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X69.8', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X69.9', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X70', 'Intentional self-harm by hanging, strangulation and suffocation', 'ICD10_2010', 'MIGRATION'),
('X70.0', 'Intentional self-harm by hanging, strangulation and suffocation, Home', 'ICD10_2010', 'MIGRATION'),
('X70.1', 'Intentional self-harm by hanging, strangulation and suffocation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X70.2', 'Intentional self-harm by hanging, strangulation and suffocation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X70.3', 'Intentional self-harm by hanging, strangulation and suffocation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X70.4', 'Intentional self-harm by hanging, strangulation and suffocation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X70.5', 'Intentional self-harm by hanging, strangulation and suffocation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X70.6', 'Intentional self-harm by hanging, strangulation and suffocation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X70.7', 'Intentional self-harm by hanging, strangulation and suffocation, Farm', 'ICD10_2010', 'MIGRATION'),
('X70.8', 'Intentional self-harm by hanging, strangulation and suffocation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X70.9', 'Intentional self-harm by hanging, strangulation and suffocation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X71', 'Intentional self-harm by drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('X71.0', 'Intentional self-harm by drowning and submersion, Home', 'ICD10_2010', 'MIGRATION'),
('X71.1', 'Intentional self-harm by drowning and submersion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X71.2', 'Intentional self-harm by drowning and submersion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X71.3', 'Intentional self-harm by drowning and submersion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X71.4', 'Intentional self-harm by drowning and submersion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X71.5', 'Intentional self-harm by drowning and submersion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X71.6', 'Intentional self-harm by drowning and submersion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X71.7', 'Intentional self-harm by drowning and submersion, Farm', 'ICD10_2010', 'MIGRATION'),
('X71.8', 'Intentional self-harm by drowning and submersion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X71.9', 'Intentional self-harm by drowning and submersion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X72', 'Intentional self-harm by handgun discharge', 'ICD10_2010', 'MIGRATION'),
('X72.0', 'Intentional self-harm by handgun discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X72.1', 'Intentional self-harm by handgun discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X72.2', 'Intentional self-harm by handgun discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X72.3', 'Intentional self-harm by handgun discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X72.4', 'Intentional self-harm by handgun discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X72.5', 'Intentional self-harm by handgun discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X72.6', 'Intentional self-harm by handgun discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X72.7', 'Intentional self-harm by handgun discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X72.8', 'Intentional self-harm by handgun discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X72.9', 'Intentional self-harm by handgun discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X73', 'Intentional self-harm by rifle, shotgun and larger firearm discharge', 'ICD10_2010', 'MIGRATION'),
('X73.0', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X73.1', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X73.2', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X73.3', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X73.4', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X73.5', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X73.6', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X73.7', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X73.8', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X73.9', 'Intentional self-harm by rifle, shotgun and larger firearm discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X74', 'Intentional self-harm by other and unspecified firearm discharge', 'ICD10_2010', 'MIGRATION'),
('X74.0', 'Intentional self-harm by other and unspecified firearm discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X74.1', 'Intentional self-harm by other and unspecified firearm discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X74.2', 'Intentional self-harm by other and unspecified firearm discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X74.3', 'Intentional self-harm by other and unspecified firearm discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X74.4', 'Intentional self-harm by other and unspecified firearm discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X74.5', 'Intentional self-harm by other and unspecified firearm discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X74.6', 'Intentional self-harm by other and unspecified firearm discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X74.7', 'Intentional self-harm by other and unspecified firearm discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X74.8', 'Intentional self-harm by other and unspecified firearm discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X74.9', 'Intentional self-harm by other and unspecified firearm discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X75', 'Intentional self-harm by explosive material', 'ICD10_2010', 'MIGRATION'),
('X75.0', 'Intentional self-harm by explosive material, Home', 'ICD10_2010', 'MIGRATION'),
('X75.1', 'Intentional self-harm by explosive material, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X75.2', 'Intentional self-harm by explosive material, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X75.3', 'Intentional self-harm by explosive material, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X75.4', 'Intentional self-harm by explosive material, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X75.5', 'Intentional self-harm by explosive material, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X75.6', 'Intentional self-harm by explosive material, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X75.7', 'Intentional self-harm by explosive material, Farm', 'ICD10_2010', 'MIGRATION'),
('X75.8', 'Intentional self-harm by explosive material, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X75.9', 'Intentional self-harm by explosive material, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X76', 'Intentional self-harm by smoke, fire and flames', 'ICD10_2010', 'MIGRATION'),
('X76.0', 'Intentional self-harm by smoke, fire and flames, Home', 'ICD10_2010', 'MIGRATION'),
('X76.1', 'Intentional self-harm by smoke, fire and flames, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X76.2', 'Intentional self-harm by smoke, fire and flames, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X76.3', 'Intentional self-harm by smoke, fire and flames, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X76.4', 'Intentional self-harm by smoke, fire and flames, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X76.5', 'Intentional self-harm by smoke, fire and flames, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X76.6', 'Intentional self-harm by smoke, fire and flames, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X76.7', 'Intentional self-harm by smoke, fire and flames, Farm', 'ICD10_2010', 'MIGRATION'),
('X76.8', 'Intentional self-harm by smoke, fire and flames, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X76.9', 'Intentional self-harm by smoke, fire and flames, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X77', 'Intentional self-harm by steam, hot vapours and hot objects', 'ICD10_2010', 'MIGRATION'),
('X77.0', 'Intentional self-harm by steam, hot vapours and hot objects, Home', 'ICD10_2010', 'MIGRATION'),
('X77.1', 'Intentional self-harm by steam, hot vapours and hot objects, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X77.2', 'Intentional self-harm by steam, hot vapours and hot objects, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X77.3', 'Intentional self-harm by steam, hot vapours and hot objects, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X77.4', 'Intentional self-harm by steam, hot vapours and hot objects, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X77.5', 'Intentional self-harm by steam, hot vapours and hot objects, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X77.6', 'Intentional self-harm by steam, hot vapours and hot objects, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X77.7', 'Intentional self-harm by steam, hot vapours and hot objects, Farm', 'ICD10_2010', 'MIGRATION'),
('X77.8', 'Intentional self-harm by steam, hot vapours and hot objects, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X77.9', 'Intentional self-harm by steam, hot vapours and hot objects, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X78', 'Intentional self-harm by sharp object', 'ICD10_2010', 'MIGRATION'),
('X78.0', 'Intentional self-harm by sharp object, Home', 'ICD10_2010', 'MIGRATION'),
('X78.1', 'Intentional self-harm by sharp object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X78.2', 'Intentional self-harm by sharp object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X78.3', 'Intentional self-harm by sharp object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X78.4', 'Intentional self-harm by sharp object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X78.5', 'Intentional self-harm by sharp object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X78.6', 'Intentional self-harm by sharp object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X78.7', 'Intentional self-harm by sharp object, Farm', 'ICD10_2010', 'MIGRATION'),
('X78.8', 'Intentional self-harm by sharp object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X78.9', 'Intentional self-harm by sharp object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X79', 'Intentional self-harm by blunt object', 'ICD10_2010', 'MIGRATION'),
('X79.0', 'Intentional self-harm by blunt object, Home', 'ICD10_2010', 'MIGRATION'),
('X79.1', 'Intentional self-harm by blunt object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X79.2', 'Intentional self-harm by blunt object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X79.3', 'Intentional self-harm by blunt object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X79.4', 'Intentional self-harm by blunt object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X79.5', 'Intentional self-harm by blunt object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X79.6', 'Intentional self-harm by blunt object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X79.7', 'Intentional self-harm by blunt object, Farm', 'ICD10_2010', 'MIGRATION'),
('X79.8', 'Intentional self-harm by blunt object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X79.9', 'Intentional self-harm by blunt object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X80', 'Intentional self-harm by jumping from a high place', 'ICD10_2010', 'MIGRATION'),
('X80.0', 'Intentional self-harm by jumping from a high place, Home', 'ICD10_2010', 'MIGRATION'),
('X80.1', 'Intentional self-harm by jumping from a high place, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X80.2', 'Intentional self-harm by jumping from a high place, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X80.3', 'Intentional self-harm by jumping from a high place, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X80.4', 'Intentional self-harm by jumping from a high place, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X80.5', 'Intentional self-harm by jumping from a high place, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X80.6', 'Intentional self-harm by jumping from a high place, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X80.7', 'Intentional self-harm by jumping from a high place, Farm', 'ICD10_2010', 'MIGRATION'),
('X80.8', 'Intentional self-harm by jumping from a high place, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X80.9', 'Intentional self-harm by jumping from a high place, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X81', 'Intentional self-harm by jumping or lying before moving object', 'ICD10_2010', 'MIGRATION'),
('X81.0', 'Intentional self-harm by jumping or lying before moving object, Home', 'ICD10_2010', 'MIGRATION'),
('X81.1', 'Intentional self-harm by jumping or lying before moving object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X81.2', 'Intentional self-harm by jumping or lying before moving object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X81.3', 'Intentional self-harm by jumping or lying before moving object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X81.4', 'Intentional self-harm by jumping or lying before moving object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X81.5', 'Intentional self-harm by jumping or lying before moving object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X81.6', 'Intentional self-harm by jumping or lying before moving object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X81.7', 'Intentional self-harm by jumping or lying before moving object, Farm', 'ICD10_2010', 'MIGRATION'),
('X81.8', 'Intentional self-harm by jumping or lying before moving object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X81.9', 'Intentional self-harm by jumping or lying before moving object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X82', 'Intentional self-harm by crashing of motor vehicle', 'ICD10_2010', 'MIGRATION'),
('X82.0', 'Intentional self-harm by crashing of motor vehicle, Home', 'ICD10_2010', 'MIGRATION'),
('X82.1', 'Intentional self-harm by crashing of motor vehicle, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X82.2', 'Intentional self-harm by crashing of motor vehicle, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X82.3', 'Intentional self-harm by crashing of motor vehicle, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X82.4', 'Intentional self-harm by crashing of motor vehicle, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X82.5', 'Intentional self-harm by crashing of motor vehicle, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X82.6', 'Intentional self-harm by crashing of motor vehicle, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X82.7', 'Intentional self-harm by crashing of motor vehicle, Farm', 'ICD10_2010', 'MIGRATION'),
('X82.8', 'Intentional self-harm by crashing of motor vehicle, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X82.9', 'Intentional self-harm by crashing of motor vehicle, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X83', 'Intentional self-harm by other specified means', 'ICD10_2010', 'MIGRATION'),
('X83.0', 'Intentional self-harm by other specified means, Home', 'ICD10_2010', 'MIGRATION'),
('X83.1', 'Intentional self-harm by other specified means, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X83.2', 'Intentional self-harm by other specified means, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X83.3', 'Intentional self-harm by other specified means, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X83.4', 'Intentional self-harm by other specified means, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X83.5', 'Intentional self-harm by other specified means, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X83.6', 'Intentional self-harm by other specified means, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X83.7', 'Intentional self-harm by other specified means, Farm', 'ICD10_2010', 'MIGRATION'),
('X83.8', 'Intentional self-harm by other specified means, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X83.9', 'Intentional self-harm by other specified means, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X84', 'Intentional self-harm by unspecified means', 'ICD10_2010', 'MIGRATION'),
('X84.0', 'Intentional self-harm by unspecified means, Home', 'ICD10_2010', 'MIGRATION'),
('X84.1', 'Intentional self-harm by unspecified means, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X84.2', 'Intentional self-harm by unspecified means, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X84.3', 'Intentional self-harm by unspecified means, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X84.4', 'Intentional self-harm by unspecified means, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X84.5', 'Intentional self-harm by unspecified means, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X84.6', 'Intentional self-harm by unspecified means, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X84.7', 'Intentional self-harm by unspecified means, Farm', 'ICD10_2010', 'MIGRATION'),
('X84.8', 'Intentional self-harm by unspecified means, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X84.9', 'Intentional self-harm by unspecified means, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X85', 'Assault by drugs, medicaments and biological substances', 'ICD10_2010', 'MIGRATION'),
('X85.0', 'Assault by drugs, medicaments and biological substances, Home', 'ICD10_2010', 'MIGRATION'),
('X85.1', 'Assault by drugs, medicaments and biological substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X85.2', 'Assault by drugs, medicaments and biological substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X85.3', 'Assault by drugs, medicaments and biological substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X85.4', 'Assault by drugs, medicaments and biological substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X85.5', 'Assault by drugs, medicaments and biological substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X85.6', 'Assault by drugs, medicaments and biological substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X85.7', 'Assault by drugs, medicaments and biological substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X85.8', 'Assault by drugs, medicaments and biological substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X85.9', 'Assault by drugs, medicaments and biological substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X86', 'Assault by corrosive substance', 'ICD10_2010', 'MIGRATION'),
('X86.0', 'Assault by corrosive substance, Home', 'ICD10_2010', 'MIGRATION'),
('X86.1', 'Assault by corrosive substance, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X86.2', 'Assault by corrosive substance, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X86.3', 'Assault by corrosive substance, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X86.4', 'Assault by corrosive substance, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X86.5', 'Assault by corrosive substance, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X86.6', 'Assault by corrosive substance, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X86.7', 'Assault by corrosive substance, Farm', 'ICD10_2010', 'MIGRATION'),
('X86.8', 'Assault by corrosive substance, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X86.9', 'Assault by corrosive substance, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X87', 'Assault by pesticides', 'ICD10_2010', 'MIGRATION'),
('X87.0', 'Assault by pesticides, Home', 'ICD10_2010', 'MIGRATION'),
('X87.1', 'Assault by pesticides, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X87.2', 'Assault by pesticides, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X87.3', 'Assault by pesticides, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X87.4', 'Assault by pesticides, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X87.5', 'Assault by pesticides, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X87.6', 'Assault by pesticides, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X87.7', 'Assault by pesticides, Farm', 'ICD10_2010', 'MIGRATION'),
('X87.8', 'Assault by pesticides, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X87.9', 'Assault by pesticides, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X88', 'Assault by gases and vapours', 'ICD10_2010', 'MIGRATION'),
('X88.0', 'Assault by gases and vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X88.1', 'Assault by gases and vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X88.2', 'Assault by gases and vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X88.3', 'Assault by gases and vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X88.4', 'Assault by gases and vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X88.5', 'Assault by gases and vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X88.6', 'Assault by gases and vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X88.7', 'Assault by gases and vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X88.8', 'Assault by gases and vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X88.9', 'Assault by gases and vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X89', 'Assault by other specified chemicals and noxious substances', 'ICD10_2010', 'MIGRATION'),
('X89.0', 'Assault by other specified chemicals and noxious substances, Home', 'ICD10_2010', 'MIGRATION'),
('X89.1', 'Assault by other specified chemicals and noxious substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X89.2', 'Assault by other specified chemicals and noxious substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X89.3', 'Assault by other specified chemicals and noxious substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X89.4', 'Assault by other specified chemicals and noxious substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X89.5', 'Assault by other specified chemicals and noxious substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X89.6', 'Assault by other specified chemicals and noxious substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X89.7', 'Assault by other specified chemicals and noxious substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X89.8', 'Assault by other specified chemicals and noxious substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X89.9', 'Assault by other specified chemicals and noxious substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X90', 'Assault by unspecified chemical or noxious substance', 'ICD10_2010', 'MIGRATION'),
('X90.0', 'Assault by unspecified chemical or noxious substance, Home', 'ICD10_2010', 'MIGRATION'),
('X90.1', 'Assault by unspecified chemical or noxious substance, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X90.2', 'Assault by unspecified chemical or noxious substance, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X90.3', 'Assault by unspecified chemical or noxious substance, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X90.4', 'Assault by unspecified chemical or noxious substance, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X90.5', 'Assault by unspecified chemical or noxious substance, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X90.6', 'Assault by unspecified chemical or noxious substance, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X90.7', 'Assault by unspecified chemical or noxious substance, Farm', 'ICD10_2010', 'MIGRATION'),
('X90.8', 'Assault by unspecified chemical or noxious substance, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X90.9', 'Assault by unspecified chemical or noxious substance, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X91', 'Assault by hanging, strangulation and suffocation', 'ICD10_2010', 'MIGRATION'),
('X91.0', 'Assault by hanging, strangulation and suffocation, Home', 'ICD10_2010', 'MIGRATION'),
('X91.1', 'Assault by hanging, strangulation and suffocation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X91.2', 'Assault by hanging, strangulation and suffocation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X91.3', 'Assault by hanging, strangulation and suffocation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X91.4', 'Assault by hanging, strangulation and suffocation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X91.5', 'Assault by hanging, strangulation and suffocation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X91.6', 'Assault by hanging, strangulation and suffocation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X91.7', 'Assault by hanging, strangulation and suffocation, Farm', 'ICD10_2010', 'MIGRATION'),
('X91.8', 'Assault by hanging, strangulation and suffocation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X91.9', 'Assault by hanging, strangulation and suffocation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X92', 'Assault by drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('X92.0', 'Assault by drowning and submersion, Home', 'ICD10_2010', 'MIGRATION'),
('X92.1', 'Assault by drowning and submersion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X92.2', 'Assault by drowning and submersion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X92.3', 'Assault by drowning and submersion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X92.4', 'Assault by drowning and submersion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X92.5', 'Assault by drowning and submersion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X92.6', 'Assault by drowning and submersion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X92.7', 'Assault by drowning and submersion, Farm', 'ICD10_2010', 'MIGRATION'),
('X92.8', 'Assault by drowning and submersion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X92.9', 'Assault by drowning and submersion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X93', 'Assault by handgun discharge', 'ICD10_2010', 'MIGRATION'),
('X93.0', 'Assault by handgun discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X93.1', 'Assault by handgun discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X93.2', 'Assault by handgun discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X93.3', 'Assault by handgun discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X93.4', 'Assault by handgun discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X93.5', 'Assault by handgun discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X93.6', 'Assault by handgun discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X93.7', 'Assault by handgun discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X93.8', 'Assault by handgun discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X93.9', 'Assault by handgun discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X94', 'Assault by rifle, shotgun and larger firearm discharge', 'ICD10_2010', 'MIGRATION'),
('X94.0', 'Assault by rifle, shotgun and larger firearm discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X94.1', 'Assault by rifle, shotgun and larger firearm discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X94.2', 'Assault by rifle, shotgun and larger firearm discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X94.3', 'Assault by rifle, shotgun and larger firearm discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X94.4', 'Assault by rifle, shotgun and larger firearm discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X94.5', 'Assault by rifle, shotgun and larger firearm discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X94.6', 'Assault by rifle, shotgun and larger firearm discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X94.7', 'Assault by rifle, shotgun and larger firearm discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X94.8', 'Assault by rifle, shotgun and larger firearm discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X94.9', 'Assault by rifle, shotgun and larger firearm discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X95', 'Assault by other and unspecified firearm discharge', 'ICD10_2010', 'MIGRATION'),
('X95.0', 'Assault by other and unspecified firearm discharge, Home', 'ICD10_2010', 'MIGRATION'),
('X95.1', 'Assault by other and unspecified firearm discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X95.2', 'Assault by other and unspecified firearm discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X95.3', 'Assault by other and unspecified firearm discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X95.4', 'Assault by other and unspecified firearm discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X95.5', 'Assault by other and unspecified firearm discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X95.6', 'Assault by other and unspecified firearm discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X95.7', 'Assault by other and unspecified firearm discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('X95.8', 'Assault by other and unspecified firearm discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X95.9', 'Assault by other and unspecified firearm discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X96', 'Assault by explosive material', 'ICD10_2010', 'MIGRATION'),
('X96.0', 'Assault by explosive material, Home', 'ICD10_2010', 'MIGRATION'),
('X96.1', 'Assault by explosive material, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X96.2', 'Assault by explosive material, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X96.3', 'Assault by explosive material, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X96.4', 'Assault by explosive material, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X96.5', 'Assault by explosive material, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X96.6', 'Assault by explosive material, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X96.7', 'Assault by explosive material, Farm', 'ICD10_2010', 'MIGRATION'),
('X96.8', 'Assault by explosive material, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X96.9', 'Assault by explosive material, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X97', 'Assault by smoke, fire and flames', 'ICD10_2010', 'MIGRATION'),
('X97.0', 'Assault by smoke, fire and flames, Home', 'ICD10_2010', 'MIGRATION'),
('X97.1', 'Assault by smoke, fire and flames, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X97.2', 'Assault by smoke, fire and flames, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X97.3', 'Assault by smoke, fire and flames, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X97.4', 'Assault by smoke, fire and flames, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X97.5', 'Assault by smoke, fire and flames, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X97.6', 'Assault by smoke, fire and flames, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X97.7', 'Assault by smoke, fire and flames, Farm', 'ICD10_2010', 'MIGRATION'),
('X97.8', 'Assault by smoke, fire and flames, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X97.9', 'Assault by smoke, fire and flames, Unspecified Place', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
