-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('W01.1', 'Fall on same level from slipping, tripping and stumbling, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W01.2', 'Fall on same level from slipping, tripping and stumbling, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W01.3', 'Fall on same level from slipping, tripping and stumbling, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W01.4', 'Fall on same level from slipping, tripping and stumbling, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W01.5', 'Fall on same level from slipping, tripping and stumbling, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W01.6', 'Fall on same level from slipping, tripping and stumbling, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W01.7', 'Fall on same level from slipping, tripping and stumbling, Farm', 'ICD10_2010', 'MIGRATION'),
('W01.8', 'Fall on same level from slipping, tripping and stumbling, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W01.9', 'Fall on same level from slipping, tripping and stumbling, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W02', 'Fall involving ice-skates, skis, roller-skates or skateboards', 'ICD10_2010', 'MIGRATION'),
('W02.0', 'Fall involving ice-skates, skis, roller-skates or skateboards, Home', 'ICD10_2010', 'MIGRATION'),
('W02.1', 'Fall involving ice-skates, skis, roller-skates or skateboards, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W02.2', 'Fall involving ice-skates, skis, roller-skates or skateboards, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W02.3', 'Fall involving ice-skates, skis, roller-skates or skateboards, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W02.4', 'Fall involving ice-skates, skis, roller-skates or skateboards, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W02.5', 'Fall involving ice-skates, skis, roller-skates or skateboards, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W02.6', 'Fall involving ice-skates, skis, roller-skates or skateboards, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W02.7', 'Fall involving ice-skates, skis, roller-skates or skateboards, Farm', 'ICD10_2010', 'MIGRATION'),
('W02.8', 'Fall involving ice-skates, skis, roller-skates or skateboards, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W02.9', 'Fall involving ice-skates, skis, roller-skates or skateboards, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W03', 'Other fall on same level due to collision with, or pushing by, another person', 'ICD10_2010', 'MIGRATION'),
('W03.0', 'Other fall on same level due to collision with, or pushing by, another person, Home', 'ICD10_2010', 'MIGRATION'),
('W03.1', 'Other fall on same level due to collision with, or pushing by, another person, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W03.2', 'Other fall on same level due to collision with, or pushing by, another person, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W03.3', 'Other fall on same level due to collision with, or pushing by, another person, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W03.4', 'Other fall on same level due to collision with, or pushing by, another person, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W03.5', 'Other fall on same level due to collision with, or pushing by, another person, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W03.6', 'Other fall on same level due to collision with, or pushing by, another person, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W03.7', 'Other fall on same level due to collision with, or pushing by, another person, Farm', 'ICD10_2010', 'MIGRATION'),
('W03.8', 'Other fall on same level due to collision with, or pushing by, another person, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W03.9', 'Other fall on same level due to collision with, or pushing by, another person, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W04', 'Fall while being carried or supported by other persons', 'ICD10_2010', 'MIGRATION'),
('W04.0', 'Fall while being carried or supported by other persons, Home', 'ICD10_2010', 'MIGRATION'),
('W04.1', 'Fall while being carried or supported by other persons, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W04.2', 'Fall while being carried or supported by other persons, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W04.3', 'Fall while being carried or supported by other persons, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W04.4', 'Fall while being carried or supported by other persons, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W04.5', 'Fall while being carried or supported by other persons, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W04.6', 'Fall while being carried or supported by other persons, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W04.7', 'Fall while being carried or supported by other persons, Farm', 'ICD10_2010', 'MIGRATION'),
('W04.8', 'Fall while being carried or supported by other persons, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W04.9', 'Fall while being carried or supported by other persons, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W05', 'Fall involving wheelchair', 'ICD10_2010', 'MIGRATION'),
('W05.0', 'Fall involving wheelchair, Home', 'ICD10_2010', 'MIGRATION'),
('W05.1', 'Fall involving wheelchair, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W05.2', 'Fall involving wheelchair, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W05.3', 'Fall involving wheelchair, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W05.4', 'Fall involving wheelchair, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W05.5', 'Fall involving wheelchair, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W05.6', 'Fall involving wheelchair, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W05.7', 'Fall involving wheelchair, Farm', 'ICD10_2010', 'MIGRATION'),
('W05.8', 'Fall involving wheelchair, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W05.9', 'Fall involving wheelchair, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W06', 'Fall involving bed', 'ICD10_2010', 'MIGRATION'),
('W06.0', 'Fall involving bed, Home', 'ICD10_2010', 'MIGRATION'),
('W06.1', 'Fall involving bed, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W06.2', 'Fall involving bed, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W06.3', 'Fall involving bed, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W06.4', 'Fall involving bed, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W06.5', 'Fall involving bed, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W06.6', 'Fall involving bed, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W06.7', 'Fall involving bed, Farm', 'ICD10_2010', 'MIGRATION'),
('W06.8', 'Fall involving bed, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W06.9', 'Fall involving bed, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W07', 'Fall involving chair', 'ICD10_2010', 'MIGRATION'),
('W07.0', 'Fall involving chair, Home', 'ICD10_2010', 'MIGRATION'),
('W07.1', 'Fall involving chair, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W07.2', 'Fall involving chair, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W07.3', 'Fall involving chair, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W07.4', 'Fall involving chair, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W07.5', 'Fall involving chair, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W07.6', 'Fall involving chair, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W07.7', 'Fall involving chair, Farm', 'ICD10_2010', 'MIGRATION'),
('W07.8', 'Fall involving chair, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W07.9', 'Fall involving chair, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W08', 'Fall involving other furniture', 'ICD10_2010', 'MIGRATION'),
('W08.0', 'Fall involving other furniture, Home', 'ICD10_2010', 'MIGRATION'),
('W08.1', 'Fall involving other furniture, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W08.2', 'Fall involving other furniture, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W08.3', 'Fall involving other furniture, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W08.4', 'Fall involving other furniture, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W08.5', 'Fall involving other furniture, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W08.6', 'Fall involving other furniture, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W08.7', 'Fall involving other furniture, Farm', 'ICD10_2010', 'MIGRATION'),
('W08.8', 'Fall involving other furniture, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W08.9', 'Fall involving other furniture, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W09', 'Fall involving playground equipment', 'ICD10_2010', 'MIGRATION'),
('W09.0', 'Fall involving playground equipment, Home', 'ICD10_2010', 'MIGRATION'),
('W09.1', 'Fall involving playground equipment, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W09.2', 'Fall involving playground equipment, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W09.3', 'Fall involving playground equipment, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W09.4', 'Fall involving playground equipment, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W09.5', 'Fall involving playground equipment, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W09.6', 'Fall involving playground equipment, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W09.7', 'Fall involving playground equipment, Farm', 'ICD10_2010', 'MIGRATION'),
('W09.8', 'Fall involving playground equipment, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W09.9', 'Fall involving playground equipment, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W10', 'Fall on and from stairs and steps', 'ICD10_2010', 'MIGRATION'),
('W10.0', 'Fall on and from stairs and steps, Home', 'ICD10_2010', 'MIGRATION'),
('W10.1', 'Fall on and from stairs and steps, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W10.2', 'Fall on and from stairs and steps, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W10.3', 'Fall on and from stairs and steps, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W10.4', 'Fall on and from stairs and steps, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W10.5', 'Fall on and from stairs and steps, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W10.6', 'Fall on and from stairs and steps, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W10.7', 'Fall on and from stairs and steps, Farm', 'ICD10_2010', 'MIGRATION'),
('W10.8', 'Fall on and from stairs and steps, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W10.9', 'Fall on and from stairs and steps, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W11', 'Fall on and from ladder', 'ICD10_2010', 'MIGRATION'),
('W11.0', 'Fall on and from ladder, Home', 'ICD10_2010', 'MIGRATION'),
('W11.1', 'Fall on and from ladder, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W11.2', 'Fall on and from ladder, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W11.3', 'Fall on and from ladder, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W11.4', 'Fall on and from ladder, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W11.5', 'Fall on and from ladder, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W11.6', 'Fall on and from ladder, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W11.7', 'Fall on and from ladder, Farm', 'ICD10_2010', 'MIGRATION'),
('W11.8', 'Fall on and from ladder, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W11.9', 'Fall on and from ladder, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W12', 'Fall on and from scaffolding', 'ICD10_2010', 'MIGRATION'),
('W12.0', 'Fall on and from scaffolding, Home', 'ICD10_2010', 'MIGRATION'),
('W12.1', 'Fall on and from scaffolding, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W12.2', 'Fall on and from scaffolding, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W12.3', 'Fall on and from scaffolding, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W12.4', 'Fall on and from scaffolding, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W12.5', 'Fall on and from scaffolding, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W12.6', 'Fall on and from scaffolding, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W12.7', 'Fall on and from scaffolding, Farm', 'ICD10_2010', 'MIGRATION'),
('W12.8', 'Fall on and from scaffolding, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W12.9', 'Fall on and from scaffolding, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W13', 'Fall from, out of or through building or structure', 'ICD10_2010', 'MIGRATION'),
('W13.0', 'Fall from, out of or through building or structure, Home', 'ICD10_2010', 'MIGRATION'),
('W13.1', 'Fall from, out of or through building or structure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W13.2', 'Fall from, out of or through building or structure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W13.3', 'Fall from, out of or through building or structure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W13.4', 'Fall from, out of or through building or structure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W13.5', 'Fall from, out of or through building or structure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W13.6', 'Fall from, out of or through building or structure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W13.7', 'Fall from, out of or through building or structure, Farm', 'ICD10_2010', 'MIGRATION'),
('W13.8', 'Fall from, out of or through building or structure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W13.9', 'Fall from, out of or through building or structure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W14', 'Fall from tree', 'ICD10_2010', 'MIGRATION'),
('W14.0', 'Fall from tree, Home', 'ICD10_2010', 'MIGRATION'),
('W14.1', 'Fall from tree, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W14.2', 'Fall from tree, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W14.3', 'Fall from tree, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W14.4', 'Fall from tree, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W14.5', 'Fall from tree, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W14.6', 'Fall from tree, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W14.7', 'Fall from tree, Farm', 'ICD10_2010', 'MIGRATION'),
('W14.8', 'Fall from tree, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W14.9', 'Fall from tree, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W15', 'Fall from cliff', 'ICD10_2010', 'MIGRATION'),
('W15.0', 'Fall from cliff, Home', 'ICD10_2010', 'MIGRATION'),
('W15.1', 'Fall from cliff, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W15.2', 'Fall from cliff, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W15.3', 'Fall from cliff, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W15.4', 'Fall from cliff, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W15.5', 'Fall from cliff, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W15.6', 'Fall from cliff, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W15.7', 'Fall from cliff, Farm', 'ICD10_2010', 'MIGRATION'),
('W15.8', 'Fall from cliff, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W15.9', 'Fall from cliff, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W16', 'Diving or jumping into water causing injury other than drowning or submersion', 'ICD10_2010', 'MIGRATION'),
('W16.0', 'Diving or jumping into water causing injury other than drowning or submersion, Home', 'ICD10_2010', 'MIGRATION'),
('W16.1', 'Diving or jumping into water causing injury other than drowning or submersion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W16.2', 'Diving or jumping into water causing injury other than drowning or submersion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W16.3', 'Diving or jumping into water causing injury other than drowning or submersion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W16.4', 'Diving or jumping into water causing injury other than drowning or submersion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W16.5', 'Diving or jumping into water causing injury other than drowning or submersion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W16.6', 'Diving or jumping into water causing injury other than drowning or submersion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W16.7', 'Diving or jumping into water causing injury other than drowning or submersion, Farm', 'ICD10_2010', 'MIGRATION'),
('W16.8', 'Diving or jumping into water causing injury other than drowning or submersion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W16.9', 'Diving or jumping into water causing injury other than drowning or submersion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W17', 'Other fall from one level to another', 'ICD10_2010', 'MIGRATION'),
('W17.0', 'Other fall from one level to another, Home', 'ICD10_2010', 'MIGRATION'),
('W17.1', 'Other fall from one level to another, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W17.2', 'Other fall from one level to another, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W17.3', 'Other fall from one level to another, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W17.4', 'Other fall from one level to another, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W17.5', 'Other fall from one level to another, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W17.6', 'Other fall from one level to another, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W17.7', 'Other fall from one level to another, Farm', 'ICD10_2010', 'MIGRATION'),
('W17.8', 'Other fall from one level to another, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W17.9', 'Other fall from one level to another, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W18', 'Other fall on same level', 'ICD10_2010', 'MIGRATION'),
('W18.0', 'Other fall on same level, Home', 'ICD10_2010', 'MIGRATION'),
('W18.1', 'Other fall on same level, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W18.2', 'Other fall on same level, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W18.3', 'Other fall on same level, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W18.4', 'Other fall on same level, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W18.5', 'Other fall on same level, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W18.6', 'Other fall on same level, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W18.7', 'Other fall on same level, Farm', 'ICD10_2010', 'MIGRATION'),
('W18.8', 'Other fall on same level, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W18.9', 'Other fall on same level, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W19', 'Unspecified fall', 'ICD10_2010', 'MIGRATION'),
('W19.0', 'Unspecified fall, Home', 'ICD10_2010', 'MIGRATION'),
('W19.1', 'Unspecified fall, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W19.2', 'Unspecified fall, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W19.3', 'Unspecified fall, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W19.4', 'Unspecified fall, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W19.5', 'Unspecified fall, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W19.6', 'Unspecified fall, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W19.7', 'Unspecified fall, Farm', 'ICD10_2010', 'MIGRATION'),
('W19.8', 'Unspecified fall, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W19.9', 'Unspecified fall, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W20', 'Struck by thrown, projected or falling object', 'ICD10_2010', 'MIGRATION'),
('W20.0', 'Struck by thrown, projected or falling object, Home', 'ICD10_2010', 'MIGRATION'),
('W20.1', 'Struck by thrown, projected or falling object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W20.2', 'Struck by thrown, projected or falling object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W20.3', 'Struck by thrown, projected or falling object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W20.4', 'Struck by thrown, projected or falling object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W20.5', 'Struck by thrown, projected or falling object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W20.6', 'Struck by thrown, projected or falling object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W20.7', 'Struck by thrown, projected or falling object, Farm', 'ICD10_2010', 'MIGRATION'),
('W20.8', 'Struck by thrown, projected or falling object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W20.9', 'Struck by thrown, projected or falling object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W21', 'Striking against or struck by sports equipment', 'ICD10_2010', 'MIGRATION'),
('W21.0', 'Striking against or struck by sports equipment, Home', 'ICD10_2010', 'MIGRATION'),
('W21.1', 'Striking against or struck by sports equipment, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W21.2', 'Striking against or struck by sports equipment, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W21.3', 'Striking against or struck by sports equipment, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W21.4', 'Striking against or struck by sports equipment, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W21.5', 'Striking against or struck by sports equipment, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W21.6', 'Striking against or struck by sports equipment, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W21.7', 'Striking against or struck by sports equipment, Farm', 'ICD10_2010', 'MIGRATION'),
('W21.8', 'Striking against or struck by sports equipment, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W21.9', 'Striking against or struck by sports equipment, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W22', 'Striking against or struck by other objects', 'ICD10_2010', 'MIGRATION'),
('W22.0', 'Striking against or struck by other objects, Home', 'ICD10_2010', 'MIGRATION'),
('W22.1', 'Striking against or struck by other objects, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W22.2', 'Striking against or struck by other objects, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W22.3', 'Striking against or struck by other objects, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W22.4', 'Striking against or struck by other objects, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W22.5', 'Striking against or struck by other objects, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W22.6', 'Striking against or struck by other objects, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W22.7', 'Striking against or struck by other objects, Farm', 'ICD10_2010', 'MIGRATION'),
('W22.8', 'Striking against or struck by other objects, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W22.9', 'Striking against or struck by other objects, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W23', 'Caught, crushed, jammed or pinched in or between objects', 'ICD10_2010', 'MIGRATION'),
('W23.0', 'Caught, crushed, jammed or pinched in or between objects, Home', 'ICD10_2010', 'MIGRATION'),
('W23.1', 'Caught, crushed, jammed or pinched in or between objects, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W23.2', 'Caught, crushed, jammed or pinched in or between objects, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W23.3', 'Caught, crushed, jammed or pinched in or between objects, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W23.4', 'Caught, crushed, jammed or pinched in or between objects, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W23.5', 'Caught, crushed, jammed or pinched in or between objects, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W23.6', 'Caught, crushed, jammed or pinched in or between objects, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W23.7', 'Caught, crushed, jammed or pinched in or between objects, Farm', 'ICD10_2010', 'MIGRATION'),
('W23.8', 'Caught, crushed, jammed or pinched in or between objects, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W23.9', 'Caught, crushed, jammed or pinched in or between objects, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W24', 'Contact with lifting and transmission devices, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('W24.0', 'Contact with lifting and transmission devices, not elsewhere classified, Home', 'ICD10_2010', 'MIGRATION'),
('W24.1', 'Contact with lifting and transmission devices, not elsewhere classified, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W24.2', 'Contact with lifting and transmission devices, not elsewhere classified, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W24.3', 'Contact with lifting and transmission devices, not elsewhere classified, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W24.4', 'Contact with lifting and transmission devices, not elsewhere classified, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W24.5', 'Contact with lifting and transmission devices, not elsewhere classified, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W24.6', 'Contact with lifting and transmission devices, not elsewhere classified, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W24.7', 'Contact with lifting and transmission devices, not elsewhere classified, Farm', 'ICD10_2010', 'MIGRATION'),
('W24.8', 'Contact with lifting and transmission devices, not elsewhere classified, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W24.9', 'Contact with lifting and transmission devices, not elsewhere classified, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W25', 'Contact with sharp glass', 'ICD10_2010', 'MIGRATION'),
('W25.0', 'Contact with sharp glass, Home', 'ICD10_2010', 'MIGRATION'),
('W25.1', 'Contact with sharp glass, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W25.2', 'Contact with sharp glass, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W25.3', 'Contact with sharp glass, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W25.4', 'Contact with sharp glass, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W25.5', 'Contact with sharp glass, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W25.6', 'Contact with sharp glass, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W25.7', 'Contact with sharp glass, Farm', 'ICD10_2010', 'MIGRATION'),
('W25.8', 'Contact with sharp glass, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W25.9', 'Contact with sharp glass, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W26', 'Contact with knife, sword or dagger', 'ICD10_2010', 'MIGRATION'),
('W26.0', 'Contact with knife, sword or dagger, Home', 'ICD10_2010', 'MIGRATION'),
('W26.1', 'Contact with knife, sword or dagger, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W26.2', 'Contact with knife, sword or dagger, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W26.3', 'Contact with knife, sword or dagger, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W26.4', 'Contact with knife, sword or dagger, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W26.5', 'Contact with knife, sword or dagger, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W26.6', 'Contact with knife, sword or dagger, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W26.7', 'Contact with knife, sword or dagger, Farm', 'ICD10_2010', 'MIGRATION'),
('W26.8', 'Contact with knife, sword or dagger, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W26.9', 'Contact with knife, sword or dagger, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W27', 'Contact with nonpowered hand tool', 'ICD10_2010', 'MIGRATION'),
('W27.0', 'Contact with nonpowered hand tool, Home', 'ICD10_2010', 'MIGRATION'),
('W27.1', 'Contact with nonpowered hand tool, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W27.2', 'Contact with nonpowered hand tool, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W27.3', 'Contact with nonpowered hand tool, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W27.4', 'Contact with nonpowered hand tool, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W27.5', 'Contact with nonpowered hand tool, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W27.6', 'Contact with nonpowered hand tool, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W27.7', 'Contact with nonpowered hand tool, Farm', 'ICD10_2010', 'MIGRATION'),
('W27.8', 'Contact with nonpowered hand tool, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W27.9', 'Contact with nonpowered hand tool, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W28', 'Contact with powered lawnmower', 'ICD10_2010', 'MIGRATION'),
('W28.0', 'Contact with powered lawnmower, Home', 'ICD10_2010', 'MIGRATION'),
('W28.1', 'Contact with powered lawnmower, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W28.2', 'Contact with powered lawnmower, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W28.3', 'Contact with powered lawnmower, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W28.4', 'Contact with powered lawnmower, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W28.5', 'Contact with powered lawnmower, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W28.6', 'Contact with powered lawnmower, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W28.7', 'Contact with powered lawnmower, Farm', 'ICD10_2010', 'MIGRATION'),
('W28.8', 'Contact with powered lawnmower, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W28.9', 'Contact with powered lawnmower, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W29', 'Contact with other powered hand tools and household machinery', 'ICD10_2010', 'MIGRATION'),
('W29.0', 'Contact with other powered hand tools and household machinery, Home', 'ICD10_2010', 'MIGRATION'),
('W29.1', 'Contact with other powered hand tools and household machinery, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W29.2', 'Contact with other powered hand tools and household machinery, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W29.3', 'Contact with other powered hand tools and household machinery, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W29.4', 'Contact with other powered hand tools and household machinery, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W29.5', 'Contact with other powered hand tools and household machinery, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W29.6', 'Contact with other powered hand tools and household machinery, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W29.7', 'Contact with other powered hand tools and household machinery, Farm', 'ICD10_2010', 'MIGRATION'),
('W29.8', 'Contact with other powered hand tools and household machinery, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W29.9', 'Contact with other powered hand tools and household machinery, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W30', 'Contact with agricultural machinery', 'ICD10_2010', 'MIGRATION'),
('W30.0', 'Contact with agricultural machinery, Home', 'ICD10_2010', 'MIGRATION'),
('W30.1', 'Contact with agricultural machinery, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W30.2', 'Contact with agricultural machinery, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W30.3', 'Contact with agricultural machinery, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W30.4', 'Contact with agricultural machinery, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W30.5', 'Contact with agricultural machinery, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W30.6', 'Contact with agricultural machinery, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W30.7', 'Contact with agricultural machinery, Farm', 'ICD10_2010', 'MIGRATION'),
('W30.8', 'Contact with agricultural machinery, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W30.9', 'Contact with agricultural machinery, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W31', 'Contact with other and unspecified machinery', 'ICD10_2010', 'MIGRATION'),
('W31.0', 'Contact with other and unspecified machinery, Home', 'ICD10_2010', 'MIGRATION'),
('W31.1', 'Contact with other and unspecified machinery, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W31.2', 'Contact with other and unspecified machinery, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W31.3', 'Contact with other and unspecified machinery, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W31.4', 'Contact with other and unspecified machinery, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W31.5', 'Contact with other and unspecified machinery, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W31.6', 'Contact with other and unspecified machinery, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W31.7', 'Contact with other and unspecified machinery, Farm', 'ICD10_2010', 'MIGRATION'),
('W31.8', 'Contact with other and unspecified machinery, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W31.9', 'Contact with other and unspecified machinery, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W32', 'Handgun discharge', 'ICD10_2010', 'MIGRATION'),
('W32.0', 'Handgun discharge, Home', 'ICD10_2010', 'MIGRATION'),
('W32.1', 'Handgun discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W32.2', 'Handgun discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W32.3', 'Handgun discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W32.4', 'Handgun discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W32.5', 'Handgun discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W32.6', 'Handgun discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W32.7', 'Handgun discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('W32.8', 'Handgun discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W32.9', 'Handgun discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W33', 'Rifle, shotgun and larger firearm discharge', 'ICD10_2010', 'MIGRATION'),
('W33.0', 'Rifle, shotgun and larger firearm discharge, Home', 'ICD10_2010', 'MIGRATION'),
('W33.1', 'Rifle, shotgun and larger firearm discharge, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W33.2', 'Rifle, shotgun and larger firearm discharge, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W33.3', 'Rifle, shotgun and larger firearm discharge, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W33.4', 'Rifle, shotgun and larger firearm discharge, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W33.5', 'Rifle, shotgun and larger firearm discharge, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W33.6', 'Rifle, shotgun and larger firearm discharge, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W33.7', 'Rifle, shotgun and larger firearm discharge, Farm', 'ICD10_2010', 'MIGRATION'),
('W33.8', 'Rifle, shotgun and larger firearm discharge, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W33.9', 'Rifle, shotgun and larger firearm discharge, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W34', 'Discharge from other and unspecified firearms', 'ICD10_2010', 'MIGRATION'),
('W34.0', 'Discharge from other and unspecified firearms, Home', 'ICD10_2010', 'MIGRATION'),
('W34.1', 'Discharge from other and unspecified firearms, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W34.2', 'Discharge from other and unspecified firearms, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W34.3', 'Discharge from other and unspecified firearms, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W34.4', 'Discharge from other and unspecified firearms, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W34.5', 'Discharge from other and unspecified firearms, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W34.6', 'Discharge from other and unspecified firearms, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W34.7', 'Discharge from other and unspecified firearms, Farm', 'ICD10_2010', 'MIGRATION'),
('W34.8', 'Discharge from other and unspecified firearms, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W34.9', 'Discharge from other and unspecified firearms, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W35', 'Explosion and rupture of boiler', 'ICD10_2010', 'MIGRATION'),
('W35.0', 'Explosion and rupture of boiler, Home', 'ICD10_2010', 'MIGRATION'),
('W35.1', 'Explosion and rupture of boiler, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W35.2', 'Explosion and rupture of boiler, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W35.3', 'Explosion and rupture of boiler, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W35.4', 'Explosion and rupture of boiler, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W35.5', 'Explosion and rupture of boiler, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W35.6', 'Explosion and rupture of boiler, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W35.7', 'Explosion and rupture of boiler, Farm', 'ICD10_2010', 'MIGRATION'),
('W35.8', 'Explosion and rupture of boiler, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W35.9', 'Explosion and rupture of boiler, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W36', 'Explosion and rupture of gas cylinder', 'ICD10_2010', 'MIGRATION'),
('W36.0', 'Explosion and rupture of gas cylinder, Home', 'ICD10_2010', 'MIGRATION'),
('W36.1', 'Explosion and rupture of gas cylinder, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W36.2', 'Explosion and rupture of gas cylinder, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W36.3', 'Explosion and rupture of gas cylinder, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W36.4', 'Explosion and rupture of gas cylinder, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W36.5', 'Explosion and rupture of gas cylinder, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W36.6', 'Explosion and rupture of gas cylinder, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W36.7', 'Explosion and rupture of gas cylinder, Farm', 'ICD10_2010', 'MIGRATION'),
('W36.8', 'Explosion and rupture of gas cylinder, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W36.9', 'Explosion and rupture of gas cylinder, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W37', 'Explosion and rupture of pressurized tyre, pipe or hose', 'ICD10_2010', 'MIGRATION'),
('W37.0', 'Explosion and rupture of pressurized tyre, pipe or hose, Home', 'ICD10_2010', 'MIGRATION'),
('W37.1', 'Explosion and rupture of pressurized tyre, pipe or hose, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W37.2', 'Explosion and rupture of pressurized tyre, pipe or hose, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W37.3', 'Explosion and rupture of pressurized tyre, pipe or hose, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W37.4', 'Explosion and rupture of pressurized tyre, pipe or hose, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W37.5', 'Explosion and rupture of pressurized tyre, pipe or hose, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W37.6', 'Explosion and rupture of pressurized tyre, pipe or hose, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W37.7', 'Explosion and rupture of pressurized tyre, pipe or hose, Farm', 'ICD10_2010', 'MIGRATION'),
('W37.8', 'Explosion and rupture of pressurized tyre, pipe or hose, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W37.9', 'Explosion and rupture of pressurized tyre, pipe or hose, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W38', 'Explosion and rupture of other specified pressurized devices', 'ICD10_2010', 'MIGRATION'),
('W38.0', 'Explosion and rupture of other specified pressurized devices, Home', 'ICD10_2010', 'MIGRATION'),
('W38.1', 'Explosion and rupture of other specified pressurized devices, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W38.2', 'Explosion and rupture of other specified pressurized devices, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W38.3', 'Explosion and rupture of other specified pressurized devices, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W38.4', 'Explosion and rupture of other specified pressurized devices, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W38.5', 'Explosion and rupture of other specified pressurized devices, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W38.6', 'Explosion and rupture of other specified pressurized devices, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W38.7', 'Explosion and rupture of other specified pressurized devices, Farm', 'ICD10_2010', 'MIGRATION'),
('W38.8', 'Explosion and rupture of other specified pressurized devices, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W38.9', 'Explosion and rupture of other specified pressurized devices, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W39', 'Discharge of firework', 'ICD10_2010', 'MIGRATION'),
('W39.0', 'Discharge of firework, Home', 'ICD10_2010', 'MIGRATION'),
('W39.1', 'Discharge of firework, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W39.2', 'Discharge of firework, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W39.3', 'Discharge of firework, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W39.4', 'Discharge of firework, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W39.5', 'Discharge of firework, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W39.6', 'Discharge of firework, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W39.7', 'Discharge of firework, Farm', 'ICD10_2010', 'MIGRATION'),
('W39.8', 'Discharge of firework, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W39.9', 'Discharge of firework, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W40', 'Explosion of other materials', 'ICD10_2010', 'MIGRATION'),
('W40.0', 'Explosion of other materials, Home', 'ICD10_2010', 'MIGRATION'),
('W40.1', 'Explosion of other materials, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W40.2', 'Explosion of other materials, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W40.3', 'Explosion of other materials, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W40.4', 'Explosion of other materials, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W40.5', 'Explosion of other materials, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W40.6', 'Explosion of other materials, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W40.7', 'Explosion of other materials, Farm', 'ICD10_2010', 'MIGRATION'),
('W40.8', 'Explosion of other materials, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W40.9', 'Explosion of other materials, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W41', 'Exposure to high-pressure jet', 'ICD10_2010', 'MIGRATION'),
('W41.0', 'Exposure to high-pressure jet, Home', 'ICD10_2010', 'MIGRATION'),
('W41.1', 'Exposure to high-pressure jet, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W41.2', 'Exposure to high-pressure jet, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W41.3', 'Exposure to high-pressure jet, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W41.4', 'Exposure to high-pressure jet, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W41.5', 'Exposure to high-pressure jet, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W41.6', 'Exposure to high-pressure jet, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W41.7', 'Exposure to high-pressure jet, Farm', 'ICD10_2010', 'MIGRATION'),
('W41.8', 'Exposure to high-pressure jet, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W41.9', 'Exposure to high-pressure jet, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W42', 'Exposure to noise', 'ICD10_2010', 'MIGRATION'),
('W42.0', 'Exposure to noise, Home', 'ICD10_2010', 'MIGRATION'),
('W42.1', 'Exposure to noise, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W42.2', 'Exposure to noise, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W42.3', 'Exposure to noise, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W42.4', 'Exposure to noise, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W42.5', 'Exposure to noise, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W42.6', 'Exposure to noise, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W42.7', 'Exposure to noise, Farm', 'ICD10_2010', 'MIGRATION'),
('W42.8', 'Exposure to noise, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W42.9', 'Exposure to noise, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W43', 'Exposure to vibration', 'ICD10_2010', 'MIGRATION'),
('W43.0', 'Exposure to vibration, Home', 'ICD10_2010', 'MIGRATION'),
('W43.1', 'Exposure to vibration, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W43.2', 'Exposure to vibration, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W43.3', 'Exposure to vibration, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W43.4', 'Exposure to vibration, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W43.5', 'Exposure to vibration, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W43.6', 'Exposure to vibration, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W43.7', 'Exposure to vibration, Farm', 'ICD10_2010', 'MIGRATION'),
('W43.8', 'Exposure to vibration, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W43.9', 'Exposure to vibration, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W44', 'Foreign body entering into or through eye or natural orifice', 'ICD10_2010', 'MIGRATION'),
('W44.0', 'Foreign body entering into or through eye or natural orifice, Home', 'ICD10_2010', 'MIGRATION'),
('W44.1', 'Foreign body entering into or through eye or natural orifice, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W44.2', 'Foreign body entering into or through eye or natural orifice, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W44.3', 'Foreign body entering into or through eye or natural orifice, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W44.4', 'Foreign body entering into or through eye or natural orifice, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W44.5', 'Foreign body entering into or through eye or natural orifice, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W44.6', 'Foreign body entering into or through eye or natural orifice, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W44.7', 'Foreign body entering into or through eye or natural orifice, Farm', 'ICD10_2010', 'MIGRATION'),
('W44.8', 'Foreign body entering into or through eye or natural orifice, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W44.9', 'Foreign body entering into or through eye or natural orifice, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W45', 'Foreign body or object entering through skin', 'ICD10_2010', 'MIGRATION'),
('W45.0', 'Foreign body or object entering through skin, Home', 'ICD10_2010', 'MIGRATION'),
('W45.1', 'Foreign body or object entering through skin, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W45.2', 'Foreign body or object entering through skin, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W45.3', 'Foreign body or object entering through skin, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W45.4', 'Foreign body or object entering through skin, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W45.5', 'Foreign body or object entering through skin, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W45.6', 'Foreign body or object entering through skin, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W45.7', 'Foreign body or object entering through skin, Farm', 'ICD10_2010', 'MIGRATION'),
('W45.8', 'Foreign body or object entering through skin, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W45.9', 'Foreign body or object entering through skin, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W46', 'Contact with hypodermic needle', 'ICD10_2010', 'MIGRATION'),
('W46.0', 'Contact with hypodermic needle, Home', 'ICD10_2010', 'MIGRATION'),
('W46.1', 'Contact with hypodermic needle, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W46.2', 'Contact with hypodermic needle, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W46.3', 'Contact with hypodermic needle, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W46.4', 'Contact with hypodermic needle, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W46.5', 'Contact with hypodermic needle, Trade and Service Area', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
