-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('X98', 'Assault by steam, hot vapours and hot objects', 'ICD10_2010', 'MIGRATION'),
('X98.0', 'Assault by steam, hot vapours and hot objects, Home', 'ICD10_2010', 'MIGRATION'),
('X98.1', 'Assault by steam, hot vapours and hot objects, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X98.2', 'Assault by steam, hot vapours and hot objects, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X98.3', 'Assault by steam, hot vapours and hot objects, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X98.4', 'Assault by steam, hot vapours and hot objects, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X98.5', 'Assault by steam, hot vapours and hot objects, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X98.6', 'Assault by steam, hot vapours and hot objects, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X98.7', 'Assault by steam, hot vapours and hot objects, Farm', 'ICD10_2010', 'MIGRATION'),
('X98.8', 'Assault by steam, hot vapours and hot objects, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X98.9', 'Assault by steam, hot vapours and hot objects, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X99', 'Assault by sharp object', 'ICD10_2010', 'MIGRATION'),
('X99.0', 'Assault by sharp object, Home', 'ICD10_2010', 'MIGRATION'),
('X99.1', 'Assault by sharp object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X99.2', 'Assault by sharp object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X99.3', 'Assault by sharp object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X99.4', 'Assault by sharp object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X99.5', 'Assault by sharp object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X99.6', 'Assault by sharp object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X99.7', 'Assault by sharp object, Farm', 'ICD10_2010', 'MIGRATION'),
('X99.8', 'Assault by sharp object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X99.9', 'Assault by sharp object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y00', 'Assault by blunt object', 'ICD10_2010', 'MIGRATION'),
('Y00.0', 'Assault by blunt object, Home', 'ICD10_2010', 'MIGRATION'),
('Y00.1', 'Assault by blunt object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y00.2', 'Assault by blunt object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y00.3', 'Assault by blunt object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y00.4', 'Assault by blunt object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y00.5', 'Assault by blunt object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y00.6', 'Assault by blunt object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y00.7', 'Assault by blunt object, Farm', 'ICD10_2010', 'MIGRATION'),
('Y00.8', 'Assault by blunt object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y00.9', 'Assault by blunt object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y01', 'Assault by pushing from high place', 'ICD10_2010', 'MIGRATION'),
('Y01.0', 'Assault by pushing from high place, Home', 'ICD10_2010', 'MIGRATION'),
('Y01.1', 'Assault by pushing from high place, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y01.2', 'Assault by pushing from high place, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y01.3', 'Assault by pushing from high place, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y01.4', 'Assault by pushing from high place, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y01.5', 'Assault by pushing from high place, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y01.6', 'Assault by pushing from high place, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y01.7', 'Assault by pushing from high place, Farm', 'ICD10_2010', 'MIGRATION'),
('Y01.8', 'Assault by pushing from high place, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y01.9', 'Assault by pushing from high place, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y02', 'Assault by pushing or placing victim before moving object', 'ICD10_2010', 'MIGRATION'),
('Y02.0', 'Assault by pushing or placing victim before moving object, Home', 'ICD10_2010', 'MIGRATION'),
('Y02.1', 'Assault by pushing or placing victim before moving object, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y02.2', 'Assault by pushing or placing victim before moving object, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y02.3', 'Assault by pushing or placing victim before moving object, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y02.4', 'Assault by pushing or placing victim before moving object, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y02.5', 'Assault by pushing or placing victim before moving object, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y02.6', 'Assault by pushing or placing victim before moving object, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y02.7', 'Assault by pushing or placing victim before moving object, Farm', 'ICD10_2010', 'MIGRATION'),
('Y02.8', 'Assault by pushing or placing victim before moving object, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y02.9', 'Assault by pushing or placing victim before moving object, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y03', 'Assault by crashing of motor vehicle', 'ICD10_2010', 'MIGRATION'),
('Y03.0', 'Assault by crashing of motor vehicle, Home', 'ICD10_2010', 'MIGRATION'),
('Y03.1', 'Assault by crashing of motor vehicle, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y03.2', 'Assault by crashing of motor vehicle, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y03.3', 'Assault by crashing of motor vehicle, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y03.4', 'Assault by crashing of motor vehicle, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y03.5', 'Assault by crashing of motor vehicle, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y03.6', 'Assault by crashing of motor vehicle, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y03.7', 'Assault by crashing of motor vehicle, Farm', 'ICD10_2010', 'MIGRATION'),
('Y03.8', 'Assault by crashing of motor vehicle, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y03.9', 'Assault by crashing of motor vehicle, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y04', 'Assault by bodily force', 'ICD10_2010', 'MIGRATION'),
('Y04.0', 'Assault by bodily force, Home', 'ICD10_2010', 'MIGRATION'),
('Y04.1', 'Assault by bodily force, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y04.2', 'Assault by bodily force, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y04.3', 'Assault by bodily force, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y04.4', 'Assault by bodily force, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y04.5', 'Assault by bodily force, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y04.6', 'Assault by bodily force, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y04.7', 'Assault by bodily force, Farm', 'ICD10_2010', 'MIGRATION'),
('Y04.8', 'Assault by bodily force, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y04.9', 'Assault by bodily force, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y05', 'Sexual assault by bodily force', 'ICD10_2010', 'MIGRATION'),
('Y05.0', 'Sexual assault by bodily force, Home', 'ICD10_2010', 'MIGRATION'),
('Y05.1', 'Sexual assault by bodily force, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y05.2', 'Sexual assault by bodily force, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y05.3', 'Sexual assault by bodily force, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y05.4', 'Sexual assault by bodily force, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y05.5', 'Sexual assault by bodily force, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y05.6', 'Sexual assault by bodily force, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y05.7', 'Sexual assault by bodily force, Farm', 'ICD10_2010', 'MIGRATION'),
('Y05.8', 'Sexual assault by bodily force, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y05.9', 'Sexual assault by bodily force, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y06', 'Neglect and abandonment', 'ICD10_2010', 'MIGRATION'),
('Y06.0', 'By spouse or partner', 'ICD10_2010', 'MIGRATION'),
('Y06.1', 'By parent', 'ICD10_2010', 'MIGRATION'),
('Y06.2', 'By acquaintance or friend', 'ICD10_2010', 'MIGRATION'),
('Y06.8', 'By other specified persons', 'ICD10_2010', 'MIGRATION'),
('Y06.9', 'By unspecified person', 'ICD10_2010', 'MIGRATION'),
('Y07', 'Other maltreatment', 'ICD10_2010', 'MIGRATION'),
('Y07.0', 'By spouse or partner', 'ICD10_2010', 'MIGRATION'),
('Y07.1', 'By parent', 'ICD10_2010', 'MIGRATION'),
('Y07.2', 'By acquaintance or friend', 'ICD10_2010', 'MIGRATION'),
('Y07.3', 'By official authorities', 'ICD10_2010', 'MIGRATION'),
('Y07.8', 'By other specified persons', 'ICD10_2010', 'MIGRATION'),
('Y07.9', 'By unspecified person', 'ICD10_2010', 'MIGRATION'),
('Y08', 'Assault by other specified means', 'ICD10_2010', 'MIGRATION'),
('Y08.0', 'Assault by other specified means, Home', 'ICD10_2010', 'MIGRATION'),
('Y08.1', 'Assault by other specified means, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y08.2', 'Assault by other specified means, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y08.3', 'Assault by other specified means, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y08.4', 'Assault by other specified means, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y08.5', 'Assault by other specified means, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y08.6', 'Assault by other specified means, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y08.7', 'Assault by other specified means, Farm', 'ICD10_2010', 'MIGRATION'),
('Y08.8', 'Assault by other specified means, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y08.9', 'Assault by other specified means, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y09', 'Assault by unspecified means', 'ICD10_2010', 'MIGRATION'),
('Y09.0', 'Assault by unspecified means, Home', 'ICD10_2010', 'MIGRATION'),
('Y09.1', 'Assault by unspecified means, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y09.2', 'Assault by unspecified means, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y09.3', 'Assault by unspecified means, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y09.4', 'Assault by unspecified means, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y09.5', 'Assault by unspecified means, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y09.6', 'Assault by unspecified means, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y09.7', 'Assault by unspecified means, Farm', 'ICD10_2010', 'MIGRATION'),
('Y09.8', 'Assault by unspecified means, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y09.9', 'Assault by unspecified means, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y10', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y10.0', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y10.1', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y10.2', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y10.3', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y10.4', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y10.5', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y10.6', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y10.7', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y10.8', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y10.9', 'Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y11', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y11.0', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y11.1', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y11.2', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y11.3', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y11.4', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y11.5', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y11.6', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y11.7', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y11.8', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y11.9', 'Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y12', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y12.0', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y12.1', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y12.2', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y12.3', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y12.4', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y12.5', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y12.6', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y12.7', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y12.8', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y12.9', 'Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y13', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y13.0', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y13.1', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y13.2', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y13.3', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y13.4', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y13.5', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y13.6', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y13.7', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y13.8', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y13.9', 'Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y14', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y14.0', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y14.1', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y14.2', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y14.3', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y14.4', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y14.5', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y14.6', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y14.7', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y14.8', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y14.9', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y15', 'Poisoning by and exposure to alcohol, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y15.0', 'Poisoning by and exposure to alcohol, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y15.1', 'Poisoning by and exposure to alcohol, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y15.2', 'Poisoning by and exposure to alcohol, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y15.3', 'Poisoning by and exposure to alcohol, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y15.4', 'Poisoning by and exposure to alcohol, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y15.5', 'Poisoning by and exposure to alcohol, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y15.6', 'Poisoning by and exposure to alcohol, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y15.7', 'Poisoning by and exposure to alcohol, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y15.8', 'Poisoning by and exposure to alcohol, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y15.9', 'Poisoning by and exposure to alcohol, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y16', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y16.0', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y16.1', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y16.2', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y16.3', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y16.4', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y16.5', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y16.6', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y16.7', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y16.8', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y16.9', 'Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y17', 'Poisoning by and exposure to other gases and vapours, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y17.0', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y17.1', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y17.2', 'Poisoning by and exposure to other gases and vapours, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y17.3', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y17.4', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y17.5', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y17.6', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y17.7', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y17.8', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y17.9', 'Poisoning by and exposure to other gases and vapours, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y18', 'Poisoning by and exposure to pesticides, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y18.0', 'Poisoning by and exposure to pesticides, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y18.1', 'Poisoning by and exposure to pesticides, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y18.2', 'Poisoning by and exposure to pesticides, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y18.3', 'Poisoning by and exposure to pesticides, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y18.4', 'Poisoning by and exposure to pesticides, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y18.5', 'Poisoning by and exposure to pesticides, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y18.6', 'Poisoning by and exposure to pesticides, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y18.7', 'Poisoning by and exposure to pesticides, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y18.8', 'Poisoning by and exposure to pesticides, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y18.9', 'Poisoning by and exposure to pesticides, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y19', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y19.0', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y19.1', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y19.2', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y19.3', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y19.4', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y19.5', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y19.6', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y19.7', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y19.8', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y19.9', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y20', 'Hanging, strangulation and suffocation, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y20.0', 'Hanging, strangulation and suffocation, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y20.1', 'Hanging, strangulation and suffocation, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y20.2', 'Hanging, strangulation and suffocation, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y20.3', 'Hanging, strangulation and suffocation, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y20.4', 'Hanging, strangulation and suffocation, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y20.5', 'Hanging, strangulation and suffocation, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y20.6', 'Hanging, strangulation and suffocation, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y20.7', 'Hanging, strangulation and suffocation, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y20.8', 'Hanging, strangulation and suffocation, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y20.9', 'Hanging, strangulation and suffocation, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y21', 'Drowning and submersion, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y21.0', 'Drowning and submersion, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y21.1', 'Drowning and submersion, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y21.2', 'Drowning and submersion, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y21.3', 'Drowning and submersion, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y21.4', 'Drowning and submersion, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y21.5', 'Drowning and submersion, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y21.6', 'Drowning and submersion, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y21.7', 'Drowning and submersion, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y21.8', 'Drowning and submersion, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y21.9', 'Drowning and submersion, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y22', 'Handgun discharge, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y22.0', 'Handgun discharge, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y22.1', 'Handgun discharge, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y22.2', 'Handgun discharge, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y22.3', 'Handgun discharge, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y22.4', 'Handgun discharge, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y22.5', 'Handgun discharge, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y22.6', 'Handgun discharge, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y22.7', 'Handgun discharge, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y22.8', 'Handgun discharge, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y22.9', 'Handgun discharge, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y23', 'Rifle, shotgun and larger firearm discharge, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y23.0', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y23.1', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y23.2', 'Rifle, shotgun and larger firearm discharge, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y23.3', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y23.4', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y23.5', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y23.6', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y23.7', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y23.8', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y23.9', 'Rifle, shotgun and larger firearm discharge, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y24', 'Other and unspecified firearm discharge, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y24.0', 'Other and unspecified firearm discharge, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y24.1', 'Other and unspecified firearm discharge, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y24.2', 'Other and unspecified firearm discharge, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y24.3', 'Other and unspecified firearm discharge, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y24.4', 'Other and unspecified firearm discharge, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y24.5', 'Other and unspecified firearm discharge, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y24.6', 'Other and unspecified firearm discharge, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y24.7', 'Other and unspecified firearm discharge, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y24.8', 'Other and unspecified firearm discharge, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y24.9', 'Other and unspecified firearm discharge, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y25', 'Contact with explosive material, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y25.0', 'Contact with explosive material, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y25.1', 'Contact with explosive material, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y25.2', 'Contact with explosive material, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y25.3', 'Contact with explosive material, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y25.4', 'Contact with explosive material, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y25.5', 'Contact with explosive material, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y25.6', 'Contact with explosive material, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y25.7', 'Contact with explosive material, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y25.8', 'Contact with explosive material, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y25.9', 'Contact with explosive material, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y26', 'Exposure to smoke, fire and flames, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y26.0', 'Exposure to smoke, fire and flames, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y26.1', 'Exposure to smoke, fire and flames, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y26.2', 'Exposure to smoke, fire and flames, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y26.3', 'Exposure to smoke, fire and flames, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y26.4', 'Exposure to smoke, fire and flames, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y26.5', 'Exposure to smoke, fire and flames, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y26.6', 'Exposure to smoke, fire and flames, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y26.7', 'Exposure to smoke, fire and flames, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y26.8', 'Exposure to smoke, fire and flames, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y26.9', 'Exposure to smoke, fire and flames, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y27', 'Contact with steam, hot vapours and hot objects, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y27.0', 'Contact with steam, hot vapours and hot objects, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y27.1', 'Contact with steam, hot vapours and hot objects, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y27.2', 'Contact with steam, hot vapours and hot objects, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y27.3', 'Contact with steam, hot vapours and hot objects, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y27.4', 'Contact with steam, hot vapours and hot objects, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y27.5', 'Contact with steam, hot vapours and hot objects, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y27.6', 'Contact with steam, hot vapours and hot objects, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y27.7', 'Contact with steam, hot vapours and hot objects, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y27.8', 'Contact with steam, hot vapours and hot objects, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y27.9', 'Contact with steam, hot vapours and hot objects, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y28', 'Contact with sharp object, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y28.0', 'Contact with sharp object, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y28.1', 'Contact with sharp object, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y28.2', 'Contact with sharp object, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y28.3', 'Contact with sharp object, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y28.4', 'Contact with sharp object, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y28.5', 'Contact with sharp object, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y28.6', 'Contact with sharp object, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y28.7', 'Contact with sharp object, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y28.8', 'Contact with sharp object, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y28.9', 'Contact with sharp object, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y29', 'Contact with blunt object, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y29.0', 'Contact with blunt object, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y29.1', 'Contact with blunt object, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y29.2', 'Contact with blunt object, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y29.3', 'Contact with blunt object, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y29.4', 'Contact with blunt object, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y29.5', 'Contact with blunt object, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y29.6', 'Contact with blunt object, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y29.7', 'Contact with blunt object, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y29.8', 'Contact with blunt object, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y29.9', 'Contact with blunt object, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y30', 'Falling, jumping or pushed from a high place, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y30.0', 'Falling, jumping or pushed from a high place, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y30.1', 'Falling, jumping or pushed from a high place, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y30.2', 'Falling, jumping or pushed from a high place, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y30.3', 'Falling, jumping or pushed from a high place, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y30.4', 'Falling, jumping or pushed from a high place, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y30.5', 'Falling, jumping or pushed from a high place, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y30.6', 'Falling, jumping or pushed from a high place, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y30.7', 'Falling, jumping or pushed from a high place, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y30.8', 'Falling, jumping or pushed from a high place, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y30.9', 'Falling, jumping or pushed from a high place, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y31', 'Falling, lying or running before or into moving object, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y31.0', 'Falling, lying or running before or into moving object, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y31.1', 'Falling, lying or running before or into moving object, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y31.2', 'Falling, lying or running before or into moving object, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y31.3', 'Falling, lying or running before or into moving object, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y31.4', 'Falling, lying or running before or into moving object, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y31.5', 'Falling, lying or running before or into moving object, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y31.6', 'Falling, lying or running before or into moving object, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y31.7', 'Falling, lying or running before or into moving object, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y31.8', 'Falling, lying or running before or into moving object, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y31.9', 'Falling, lying or running before or into moving object, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y32', 'Crashing of motor vehicle, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y32.0', 'Crashing of motor vehicle, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y32.1', 'Crashing of motor vehicle, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y32.2', 'Crashing of motor vehicle, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y32.3', 'Crashing of motor vehicle, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y32.4', 'Crashing of motor vehicle, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y32.5', 'Crashing of motor vehicle, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y32.6', 'Crashing of motor vehicle, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y32.7', 'Crashing of motor vehicle, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y32.8', 'Crashing of motor vehicle, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y32.9', 'Crashing of motor vehicle, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y33', 'Other specified events, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y33.0', 'Other specified events, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y33.1', 'Other specified events, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y33.2', 'Other specified events, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y33.3', 'Other specified events, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y33.4', 'Other specified events, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y33.5', 'Other specified events, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y33.6', 'Other specified events, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y33.7', 'Other specified events, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y33.8', 'Other specified events, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y33.9', 'Other specified events, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y34', 'Unspecified event, undetermined intent', 'ICD10_2010', 'MIGRATION'),
('Y34.0', 'Unspecified event, undetermined intent, Home', 'ICD10_2010', 'MIGRATION'),
('Y34.1', 'Unspecified event, undetermined intent, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('Y34.2', 'Unspecified event, undetermined intent, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('Y34.3', 'Unspecified event, undetermined intent, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('Y34.4', 'Unspecified event, undetermined intent, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('Y34.5', 'Unspecified event, undetermined intent, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('Y34.6', 'Unspecified event, undetermined intent, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('Y34.7', 'Unspecified event, undetermined intent, Farm', 'ICD10_2010', 'MIGRATION'),
('Y34.8', 'Unspecified event, undetermined intent, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('Y34.9', 'Unspecified event, undetermined intent, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('Y35', 'Legal intervention', 'ICD10_2010', 'MIGRATION'),
('Y35.0', 'Legal intervention involving firearm discharge', 'ICD10_2010', 'MIGRATION'),
('Y35.1', 'Legal intervention involving explosives', 'ICD10_2010', 'MIGRATION'),
('Y35.2', 'Legal intervention involving gas', 'ICD10_2010', 'MIGRATION'),
('Y35.3', 'Legal intervention involving blunt objects', 'ICD10_2010', 'MIGRATION'),
('Y35.4', 'Legal intervention involving sharp objects', 'ICD10_2010', 'MIGRATION'),
('Y35.5', 'Legal execution', 'ICD10_2010', 'MIGRATION'),
('Y35.6', 'Legal intervention involving other specified means', 'ICD10_2010', 'MIGRATION'),
('Y35.7', 'Legal intervention, means unspecified', 'ICD10_2010', 'MIGRATION'),
('Y36', 'Operations of war', 'ICD10_2010', 'MIGRATION'),
('Y36.0', 'War operations involving explosion of marine weapons', 'ICD10_2010', 'MIGRATION'),
('Y36.1', 'War operations involving destruction of aircraft', 'ICD10_2010', 'MIGRATION'),
('Y36.2', 'War operations involving other explosions and fragments', 'ICD10_2010', 'MIGRATION'),
('Y36.3', 'War operations involving fires, conflagrations and hot substances', 'ICD10_2010', 'MIGRATION'),
('Y36.4', 'War operations involving firearm discharge and other forms of conventional warfare', 'ICD10_2010', 'MIGRATION'),
('Y36.5', 'War operations involving nuclear weapons', 'ICD10_2010', 'MIGRATION'),
('Y36.6', 'War operations involving biological weapons', 'ICD10_2010', 'MIGRATION'),
('Y36.7', 'War operations involving chemical weapons and other forms of unconventional warfare', 'ICD10_2010', 'MIGRATION'),
('Y36.8', 'War operations occurring after cessation of hostilities', 'ICD10_2010', 'MIGRATION'),
('Y36.9', 'War operations, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y40', 'Systemic antibiotics', 'ICD10_2010', 'MIGRATION'),
('Y40.0', 'Penicillins', 'ICD10_2010', 'MIGRATION'),
('Y40.1', 'Cefalosporins and other beta-lactam antibiotics', 'ICD10_2010', 'MIGRATION'),
('Y40.2', 'Chloramphenicol group', 'ICD10_2010', 'MIGRATION'),
('Y40.3', 'Macrolides', 'ICD10_2010', 'MIGRATION'),
('Y40.4', 'Tetracyclines', 'ICD10_2010', 'MIGRATION'),
('Y40.5', 'Aminoglycosides', 'ICD10_2010', 'MIGRATION'),
('Y40.6', 'Rifamycins', 'ICD10_2010', 'MIGRATION'),
('Y40.7', 'Antifungal antibiotics, systemically used', 'ICD10_2010', 'MIGRATION'),
('Y40.8', 'Other systemic antibiotics', 'ICD10_2010', 'MIGRATION'),
('Y40.9', 'Systemic antibiotic, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y41', 'Other systemic anti-infectives and antiparasitics', 'ICD10_2010', 'MIGRATION'),
('Y41.0', 'Sulfonamides', 'ICD10_2010', 'MIGRATION'),
('Y41.1', 'Antimycobacterial drugs', 'ICD10_2010', 'MIGRATION'),
('Y41.2', 'Antimalarials and drugs acting on other blood protozoa', 'ICD10_2010', 'MIGRATION'),
('Y41.3', 'Other antiprotozoal drugs', 'ICD10_2010', 'MIGRATION'),
('Y41.4', 'Anthelminthics', 'ICD10_2010', 'MIGRATION'),
('Y41.5', 'Antiviral drugs', 'ICD10_2010', 'MIGRATION'),
('Y41.8', 'Other specified systemic anti-infectives and antiparasitics', 'ICD10_2010', 'MIGRATION'),
('Y41.9', 'Systemic anti-infective and antiparasitic, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y42', 'Hormones and their synthetic substitutes and antagonists, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y42.0', 'Glucocorticoids and synthetic analogues', 'ICD10_2010', 'MIGRATION'),
('Y42.1', 'Thyroid hormones and substitutes', 'ICD10_2010', 'MIGRATION'),
('Y42.2', 'Antithyroid drugs', 'ICD10_2010', 'MIGRATION'),
('Y42.3', 'Insulin and oral hypoglycaemic [antidiabetic] drugs', 'ICD10_2010', 'MIGRATION'),
('Y42.4', 'Oral contraceptives', 'ICD10_2010', 'MIGRATION'),
('Y42.5', 'Other estrogens and progestogens', 'ICD10_2010', 'MIGRATION'),
('Y42.6', 'Antigonadotrophins, antiestrogens, antiandrogens, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y42.7', 'Androgens and anabolic congeners', 'ICD10_2010', 'MIGRATION'),
('Y42.8', 'Other and unspecified hormones and their synthetic substitutes', 'ICD10_2010', 'MIGRATION'),
('Y42.9', 'Other and unspecified hormone antagonists', 'ICD10_2010', 'MIGRATION'),
('Y43', 'Primarily systemic agents', 'ICD10_2010', 'MIGRATION'),
('Y43.0', 'Antiallergic and antiemetic drugs', 'ICD10_2010', 'MIGRATION'),
('Y43.1', 'Antineoplastic antimetabolites', 'ICD10_2010', 'MIGRATION'),
('Y43.2', 'Antineoplastic natural products', 'ICD10_2010', 'MIGRATION'),
('Y43.3', 'Other antineoplastic drugs', 'ICD10_2010', 'MIGRATION'),
('Y43.4', 'Immunosuppressive agents', 'ICD10_2010', 'MIGRATION'),
('Y43.5', 'Acidifying and alkalizing agents', 'ICD10_2010', 'MIGRATION'),
('Y43.6', 'Enzymes, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y43.8', 'Other primarily systemic agents, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y43.9', 'Primarily systemic agent, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y44', 'Agents primarily affecting blood constituents', 'ICD10_2010', 'MIGRATION'),
('Y44.0', 'Iron preparations and other anti-hypochromic-anaemia preparations', 'ICD10_2010', 'MIGRATION'),
('Y44.1', 'Vitamin B12, folic acid and other anti-megaloblastic-anaemia preparations', 'ICD10_2010', 'MIGRATION'),
('Y44.2', 'Anticoagulants', 'ICD10_2010', 'MIGRATION'),
('Y44.3', 'Anticoagulant antagonists, vitamin K and other coagulants', 'ICD10_2010', 'MIGRATION'),
('Y44.4', 'Antithrombotic drugs [platelet-aggregation inhibitors]', 'ICD10_2010', 'MIGRATION'),
('Y44.5', 'Thrombolytic drugs', 'ICD10_2010', 'MIGRATION'),
('Y44.6', 'Natural blood and blood products', 'ICD10_2010', 'MIGRATION'),
('Y44.7', 'Plasma substitutes', 'ICD10_2010', 'MIGRATION'),
('Y44.9', 'Other and unspecified agents affecting blood constituents', 'ICD10_2010', 'MIGRATION'),
('Y45', 'Analgesics, antipyretics and anti-inflammatory drugs', 'ICD10_2010', 'MIGRATION'),
('Y45.0', 'Opioids and related analgesics', 'ICD10_2010', 'MIGRATION'),
('Y45.1', 'Salicylates', 'ICD10_2010', 'MIGRATION'),
('Y45.2', 'Propionic acid derivatives', 'ICD10_2010', 'MIGRATION'),
('Y45.3', 'Other nonsteroidal anti-inflammatory drugs [NSAID]', 'ICD10_2010', 'MIGRATION'),
('Y45.4', 'Antirheumatics', 'ICD10_2010', 'MIGRATION'),
('Y45.5', '4-Aminophenol derivatives', 'ICD10_2010', 'MIGRATION'),
('Y45.8', 'Other analgesics and antipyretics', 'ICD10_2010', 'MIGRATION'),
('Y45.9', 'Analgesic, antipyretic and anti-inflammatory drug, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y46', 'Antiepileptics and antiparkinsonism drugs', 'ICD10_2010', 'MIGRATION'),
('Y46.0', 'Succinimides', 'ICD10_2010', 'MIGRATION'),
('Y46.1', 'Oxazolidinediones', 'ICD10_2010', 'MIGRATION'),
('Y46.2', 'Hydantoin derivatives', 'ICD10_2010', 'MIGRATION'),
('Y46.3', 'Deoxybarbiturates', 'ICD10_2010', 'MIGRATION'),
('Y46.4', 'Iminostilbenes', 'ICD10_2010', 'MIGRATION'),
('Y46.5', 'Valproic acid', 'ICD10_2010', 'MIGRATION'),
('Y46.6', 'Other and unspecified antiepileptics', 'ICD10_2010', 'MIGRATION'),
('Y46.7', 'Antiparkinsonism drugs', 'ICD10_2010', 'MIGRATION'),
('Y46.8', 'Antispasticity drugs', 'ICD10_2010', 'MIGRATION'),
('Y47', 'Sedatives, hypnotics and antianxiety drugs', 'ICD10_2010', 'MIGRATION'),
('Y47.0', 'Barbiturates, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y47.1', 'Benzodiazepines', 'ICD10_2010', 'MIGRATION'),
('Y47.2', 'Cloral derivatives', 'ICD10_2010', 'MIGRATION'),
('Y47.3', 'Paraldehyde', 'ICD10_2010', 'MIGRATION'),
('Y47.4', 'Bromine compounds', 'ICD10_2010', 'MIGRATION'),
('Y47.5', 'Mixed sedatives and hypnotics, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('Y47.8', 'Other sedatives, hypnotics and antianxiety drugs', 'ICD10_2010', 'MIGRATION'),
('Y47.9', 'Sedative, hypnotic and antianxiety drug, unspecified', 'ICD10_2010', 'MIGRATION'),
('Y48', 'Anaesthetics and therapeutic gases', 'ICD10_2010', 'MIGRATION'),
('Y48.0', 'Inhaled anaesthetics', 'ICD10_2010', 'MIGRATION'),
('Y48.1', 'Parenteral anaesthetics', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
