-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('V49.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.2', 'Unspecified car occupant injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.3', 'Car occupant [any] injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.6', 'Unspecified car occupant injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V49.8', 'Car occupant [any] injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V49.9', 'Car occupant [any] injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V50', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V50.0', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.1', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.2', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.3', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.4', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V50.5', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.6', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.7', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V50.9', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V51', 'Occupant of pick-up truck or van injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V51.0', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.1', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.2', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.3', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.4', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V51.5', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.6', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.7', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V51.9', 'Occupant of pick-up truck or van injured in collision with pedal cycle: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V52', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V52.0', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.1', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.2', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.3', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.4', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V52.5', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.6', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.7', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V52.9', 'Occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V53', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V53.0', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.1', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.2', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.3', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.4', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V53.5', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.6', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.7', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V53.9', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V54', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V54.0', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.1', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.2', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.3', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.4', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V54.5', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.6', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.7', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V54.9', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V55', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V55.0', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.1', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.2', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.3', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.4', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V55.5', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.6', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.7', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V55.9', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V56', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V56.0', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.1', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.2', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.3', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.4', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V56.5', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.6', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.7', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V56.9', 'Occupant of pick-up truck or van injured in collision with other nonmotor vehicle: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V57', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V57.0', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.1', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.2', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.3', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.4', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V57.5', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.6', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.7', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V57.9', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V58', 'Occupant of pick-up truck or van injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V58.0', 'Occupant of pick-up truck or van injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.1', 'Occupant of pick-up truck or van injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.2', 'Occupant of pick-up truck or van injured in noncollision transport accident: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.3', 'Occupant of pick-up truck or van injured in noncollision transport accident: Unspecified occupant of pick-up truck or van injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.4', 'Occupant of pick-up truck or van injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V58.5', 'Occupant of pick-up truck or van injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.6', 'Occupant of pick-up truck or van injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.7', 'Occupant of pick-up truck or van injured in noncollision transport accident: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V58.9', 'Occupant of pick-up truck or van injured in noncollision transport accident: Unspecified occupant of pick-up truck or van injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V59', 'Occupant of pick-up truck or van injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V59.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.2', 'Unspecified occupant of pick-up truck or van injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.3', 'Occupant [any] of pick-up truck or van injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.6', 'Unspecified occupant of pick-up truck or van injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V59.8', 'Occupant [any] of pick-up truck or van injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V59.9', 'Occupant [any] of pick-up truck or van injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V60', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V60.0', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.1', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.2', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.3', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.4', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V60.5', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.6', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.7', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V60.9', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V61', 'Occupant of heavy transport vehicle injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V61.0', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.1', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.2', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.3', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.4', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V61.5', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.6', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.7', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V61.9', 'Occupant of heavy transport vehicle injured in collision with pedal cycle: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V62', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V62.0', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.1', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.2', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.3', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.4', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V62.5', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.6', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.7', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V62.9', 'Occupant of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V63', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V63.0', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.1', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.2', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.3', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.4', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V63.5', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.6', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.7', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V63.9', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V64', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V64.0', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.1', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.2', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.3', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.4', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V64.5', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.6', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.7', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V64.9', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V65', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V65.0', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.1', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.2', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.3', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.4', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V65.5', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.6', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.7', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V65.9', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V66', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V66.0', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.1', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.2', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.3', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.4', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V66.5', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.6', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.7', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V66.9', 'Occupant of heavy transport vehicle injured in collision with other nonmotor vehicle: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V67', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V67.0', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.1', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.2', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.3', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.4', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V67.5', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.6', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.7', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V67.9', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V68', 'Occupant of heavy transport vehicle injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V68.0', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.1', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.2', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.3', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Unspecified occupant of heavy transport vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.4', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V68.5', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.6', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.7', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V68.9', 'Occupant of heavy transport vehicle injured in noncollision transport accident: Unspecified occupant of heavy transport vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V69', 'Occupant of heavy transport vehicle injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V69.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.2', 'Unspecified occupant of heavy transport vehicle injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.3', 'Occupant [any] of heavy transport vehicle injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.6', 'Unspecified occupant of heavy transport vehicle injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V69.8', 'Occupant [any] of heavy transport vehicle injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V69.9', 'Occupant [any] of heavy transport vehicle injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V70', 'Bus occupant injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V70.0', 'Bus occupant injured in collision with pedestrian or animal: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.1', 'Bus occupant injured in collision with pedestrian or animal: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.2', 'Bus occupant injured in collision with pedestrian or animal: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.3', 'Bus occupant injured in collision with pedestrian or animal: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.4', 'Bus occupant injured in collision with pedestrian or animal: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V70.5', 'Bus occupant injured in collision with pedestrian or animal: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.6', 'Bus occupant injured in collision with pedestrian or animal: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.7', 'Bus occupant injured in collision with pedestrian or animal: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V70.9', 'Bus occupant injured in collision with pedestrian or animal: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V71', 'Bus occupant injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V71.0', 'Bus occupant injured in collision with pedal cycle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.1', 'Bus occupant injured in collision with pedal cycle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.2', 'Bus occupant injured in collision with pedal cycle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.3', 'Bus occupant injured in collision with pedal cycle: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.4', 'Bus occupant injured in collision with pedal cycle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V71.5', 'Bus occupant injured in collision with pedal cycle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.6', 'Bus occupant injured in collision with pedal cycle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.7', 'Bus occupant injured in collision with pedal cycle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V71.9', 'Bus occupant injured in collision with pedal cycle: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V72', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V72.0', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.1', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.2', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.3', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.4', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V72.5', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.6', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.7', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V72.9', 'Bus occupant injured in collision with two- or three-wheeled motor vehicle: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V73', 'Bus occupant injured in collision with car, pick-up truck or van', 'ICD10_2010', 'MIGRATION'),
('V73.0', 'Bus occupant injured in collision with car, pick-up truck or van: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.1', 'Bus occupant injured in collision with car, pick-up truck or van: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.2', 'Bus occupant injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.3', 'Bus occupant injured in collision with car, pick-up truck or van: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.4', 'Bus occupant injured in collision with car, pick-up truck or van: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V73.5', 'Bus occupant injured in collision with car, pick-up truck or van: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.6', 'Bus occupant injured in collision with car, pick-up truck or van: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.7', 'Bus occupant injured in collision with car, pick-up truck or van: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V73.9', 'Bus occupant injured in collision with car, pick-up truck or van: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V74', 'Bus occupant injured in collision with heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V74.0', 'Bus occupant injured in collision with heavy transport vehicle or bus: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.1', 'Bus occupant injured in collision with heavy transport vehicle or bus: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.2', 'Bus occupant injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.3', 'Bus occupant injured in collision with heavy transport vehicle or bus: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.4', 'Bus occupant injured in collision with heavy transport vehicle or bus: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V74.5', 'Bus occupant injured in collision with heavy transport vehicle or bus: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.6', 'Bus occupant injured in collision with heavy transport vehicle or bus: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.7', 'Bus occupant injured in collision with heavy transport vehicle or bus: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V74.9', 'Bus occupant injured in collision with heavy transport vehicle or bus: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V75', 'Bus occupant injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V75.0', 'Bus occupant injured in collision with railway train or railway vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.1', 'Bus occupant injured in collision with railway train or railway vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.2', 'Bus occupant injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.3', 'Bus occupant injured in collision with railway train or railway vehicle: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.4', 'Bus occupant injured in collision with railway train or railway vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V75.5', 'Bus occupant injured in collision with railway train or railway vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.6', 'Bus occupant injured in collision with railway train or railway vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.7', 'Bus occupant injured in collision with railway train or railway vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V75.9', 'Bus occupant injured in collision with railway train or railway vehicle: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V76', 'Bus occupant injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V76.0', 'Bus occupant injured in collision with other nonmotor vehicle: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.1', 'Bus occupant injured in collision with other nonmotor vehicle: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.2', 'Bus occupant injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.3', 'Bus occupant injured in collision with other nonmotor vehicle: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.4', 'Bus occupant injured in collision with other nonmotor vehicle: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V76.5', 'Bus occupant injured in collision with other nonmotor vehicle: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.6', 'Bus occupant injured in collision with other nonmotor vehicle: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.7', 'Bus occupant injured in collision with other nonmotor vehicle: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V76.9', 'Bus occupant injured in collision with other nonmotor vehicle: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V77', 'Bus occupant injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V77.0', 'Bus occupant injured in collision with fixed or stationary object: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.1', 'Bus occupant injured in collision with fixed or stationary object: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.2', 'Bus occupant injured in collision with fixed or stationary object: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.3', 'Bus occupant injured in collision with fixed or stationary object: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.4', 'Bus occupant injured in collision with fixed or stationary object: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V77.5', 'Bus occupant injured in collision with fixed or stationary object: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.6', 'Bus occupant injured in collision with fixed or stationary object: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.7', 'Bus occupant injured in collision with fixed or stationary object: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V77.9', 'Bus occupant injured in collision with fixed or stationary object: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V78', 'Bus occupant injured in noncollision transport accident', 'ICD10_2010', 'MIGRATION'),
('V78.0', 'Bus occupant injured in noncollision transport accident: Driver injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.1', 'Bus occupant injured in noncollision transport accident: Passenger injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.2', 'Bus occupant injured in noncollision transport accident: Person on outside of vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.3', 'Bus occupant injured in noncollision transport accident: Unspecified bus occupant injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.4', 'Bus occupant injured in noncollision transport accident: Person injured while boarding or alighting', 'ICD10_2010', 'MIGRATION'),
('V78.5', 'Bus occupant injured in noncollision transport accident: Driver injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.6', 'Bus occupant injured in noncollision transport accident: Passenger injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.7', 'Bus occupant injured in noncollision transport accident: Person on outside of vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V78.9', 'Bus occupant injured in noncollision transport accident: Unspecified bus occupant injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V79', 'Bus occupant injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V79.0', 'Driver injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.1', 'Passenger injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.2', 'Unspecified bus occupant injured in collision with other and unspecified motor vehicles in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.3', 'Bus occupant [any] injured in unspecified nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.4', 'Driver injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.5', 'Passenger injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.6', 'Unspecified bus occupant injured in collision with other and unspecified motor vehicles in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V79.8', 'Bus occupant [any] injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V79.9', 'Bus occupant [any] injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V80', 'Animal-rider or occupant of animal-drawn vehicle injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V80.0', 'Rider or occupant injured by fall from or being thrown from animal or animal-drawn vehicle in noncollision accident', 'ICD10_2010', 'MIGRATION'),
('V80.1', 'Rider or occupant injured in collision with pedestrian or animal', 'ICD10_2010', 'MIGRATION'),
('V80.2', 'Rider or occupant injured in collision with pedal cycle', 'ICD10_2010', 'MIGRATION'),
('V80.3', 'Rider or occupant injured in collision with two- or three-wheeled motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V80.4', 'Rider or occupant injured in collision with car, pick-up truck, van, heavy transport vehicle or bus', 'ICD10_2010', 'MIGRATION'),
('V80.5', 'Rider or occupant injured in collision with other specified motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V80.6', 'Rider or occupant injured in collision with railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V80.7', 'Rider or occupant injured in collision with other nonmotor vehicle', 'ICD10_2010', 'MIGRATION'),
('V80.8', 'Rider or occupant injured in collision with fixed or stationary object', 'ICD10_2010', 'MIGRATION'),
('V80.9', 'Rider or occupant injured in other and unspecified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V81', 'Occupant of railway train or railway vehicle injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V81.0', 'Occupant of railway train or railway vehicle injured in collision with motor vehicle in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V81.1', 'Occupant of railway train or railway vehicle injured in collision with motor vehicle in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V81.2', 'Occupant of railway train or railway vehicle injured in collision with or hit by rolling stock', 'ICD10_2010', 'MIGRATION'),
('V81.3', 'Occupant of railway train or railway vehicle injured in collision with other object', 'ICD10_2010', 'MIGRATION'),
('V81.4', 'Person injured while boarding or alighting from railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V81.5', 'Occupant of railway train or railway vehicle injured by fall in railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V81.6', 'Occupant of railway train or railway vehicle injured by fall from railway train or railway vehicle', 'ICD10_2010', 'MIGRATION'),
('V81.7', 'Occupant of railway train or railway vehicle injured in derailment without antecedent collision', 'ICD10_2010', 'MIGRATION'),
('V81.8', 'Occupant of railway train or railway vehicle injured in other specified railway accidents', 'ICD10_2010', 'MIGRATION'),
('V81.9', 'Occupant of railway train or railway vehicle injured in unspecified railway accident', 'ICD10_2010', 'MIGRATION'),
('V82', 'Occupant of streetcar injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V82.0', 'Occupant of streetcar injured in collision with motor vehicle in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V82.1', 'Occupant of streetcar injured in collision with motor vehicle in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V82.2', 'Occupant of streetcar injured in collision with or hit by rolling stock', 'ICD10_2010', 'MIGRATION'),
('V82.3', 'Occupant of streetcar injured in collision with other object', 'ICD10_2010', 'MIGRATION'),
('V82.4', 'Person injured while boarding or alighting from streetcar', 'ICD10_2010', 'MIGRATION'),
('V82.5', 'Occupant of streetcar injured by fall in streetcar', 'ICD10_2010', 'MIGRATION'),
('V82.6', 'Occupant of streetcar injured by fall from streetcar', 'ICD10_2010', 'MIGRATION'),
('V82.7', 'Occupant of streetcar injured in derailment without antecedent collision', 'ICD10_2010', 'MIGRATION'),
('V82.8', 'Occupant of streetcar injured in other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V82.9', 'Occupant of streetcar injured in unspecified traffic accident', 'ICD10_2010', 'MIGRATION'),
('V83', 'Occupant of special vehicle mainly used on industrial premises injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V83.0', 'Driver of special industrial vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.1', 'Passenger of special industrial vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.2', 'Person on outside of special industrial vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.3', 'Unspecified occupant of special industrial vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.4', 'Person injured while boarding or alighting from special industrial vehicle', 'ICD10_2010', 'MIGRATION'),
('V83.5', 'Driver of special industrial vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.6', 'Passenger of special industrial vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.7', 'Person on outside of special industrial vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V83.9', 'Unspecified occupant of special industrial vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V84', 'Occupant of special vehicle mainly used in agriculture injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V84.0', 'Driver of special agricultural vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.1', 'Passenger of special agricultural vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.2', 'Person on outside of special agricultural vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.3', 'Unspecified occupant of special agricultural vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.4', 'Person injured while boarding or alighting from special agricultural vehicle', 'ICD10_2010', 'MIGRATION'),
('V84.5', 'Driver of special agricultural vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.6', 'Passenger of special agricultural vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.7', 'Person on outside of special agricultural vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V84.9', 'Unspecified occupant of special agricultural vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V85', 'Occupant of special construction vehicle injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V85.0', 'Driver of special construction vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.1', 'Passenger of special construction vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.2', 'Person on outside of special construction vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.3', 'Unspecified occupant of special construction vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.4', 'Person injured while boarding or alighting from special construction vehicle', 'ICD10_2010', 'MIGRATION'),
('V85.5', 'Driver of special construction vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.6', 'Passenger of special construction vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.7', 'Person on outside of special construction vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V85.9', 'Unspecified occupant of special construction vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V86', 'Occupant of special all-terrain or other motor vehicle designed primarily for off-road use, injured in transport accident', 'ICD10_2010', 'MIGRATION'),
('V86.0', 'Driver of all-terrain or other off-road motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.1', 'Passenger of all-terrain or other off-road motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.2', 'Person on outside of all-terrain or other off-road motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.3', 'Unspecified occupant of all-terrain or other off-road motor vehicle injured in traffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.4', 'Person injured while boarding or alighting from all-terrain or other off-road motor vehicle', 'ICD10_2010', 'MIGRATION'),
('V86.5', 'Driver of all-terrain or other off-road motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.6', 'Passenger of all-terrain or other off-road motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.7', 'Person on outside of all-terrain or other off-road motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V86.9', 'Unspecified occupant of all-terrain or other off-road motor vehicle injured in nontraffic accident', 'ICD10_2010', 'MIGRATION'),
('V87', 'Traffic accident of specified type but victim''s mode of transport unknown', 'ICD10_2010', 'MIGRATION'),
('V87.0', 'Person injured in collision between car and two- or three-wheeled motor vehicle (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.1', 'Person injured in collision between other motor vehicle and two- or three-wheeled motor vehicle (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.2', 'Person injured in collision between car and pick-up truck or van (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.3', 'Person injured in collision between car and bus (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.4', 'Person injured in collision between car and heavy transport vehicle (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.5', 'Person injured in collision between heavy transport vehicle and bus (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.6', 'Person injured in collision between railway train or railway vehicle and car (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.7', 'Person injured in collision between other specified motor vehicles (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.8', 'Person injured in other specified noncollision transport accidents involving motor vehicle (traffic)', 'ICD10_2010', 'MIGRATION'),
('V87.9', 'Person injured in other specified (collision)(noncollision) transport accidents involving nonmotor vehicle (traffic)', 'ICD10_2010', 'MIGRATION'),
('V88', 'Nontraffic accident of specified type but victim''s mode of transport unknown', 'ICD10_2010', 'MIGRATION'),
('V88.0', 'Person injured in collision between car and two- or three-wheeled motor vehicle, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.1', 'Person injured in collision between other motor vehicle and two- or three-wheeled motor vehicle, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.2', 'Person injured in collision between car and pick-up truck or van, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.3', 'Person injured in collision between car and bus, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.4', 'Person injured in collision between car and heavy transport vehicle, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.5', 'Person injured in collision between heavy transport vehicle and bus, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.6', 'Person injured in collision between railway train or railway vehicle and car, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.7', 'Person injured in collision between other specified motor vehicles, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.8', 'Person injured in other specified noncollision transport accidents involving motor vehicle, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V88.9', 'Person injured in other specified (collision)(noncollision) transport accidents involving nonmotor vehicle, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V89', 'Motor- or nonmotor-vehicle accident, type of vehicle unspecified', 'ICD10_2010', 'MIGRATION'),
('V89.0', 'Person injured in unspecified motor-vehicle accident, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V89.1', 'Person injured in unspecified nonmotor-vehicle accident, nontraffic', 'ICD10_2010', 'MIGRATION'),
('V89.2', 'Person injured in unspecified motor-vehicle accident, traffic', 'ICD10_2010', 'MIGRATION'),
('V89.3', 'Person injured in unspecified nonmotor-vehicle accident, traffic', 'ICD10_2010', 'MIGRATION'),
('V89.9', 'Person injured in unspecified vehicle accident', 'ICD10_2010', 'MIGRATION'),
('V90', 'Accident to watercraft causing drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('V90.0', 'Accident to watercraft causing drowning and submersion: Merchant ship', 'ICD10_2010', 'MIGRATION'),
('V90.1', 'Accident to watercraft causing drowning and submersion: Passenger ship', 'ICD10_2010', 'MIGRATION'),
('V90.2', 'Accident to watercraft causing drowning and submersion: Fishing boat', 'ICD10_2010', 'MIGRATION'),
('V90.3', 'Accident to watercraft causing drowning and submersion: Other powered watercraft', 'ICD10_2010', 'MIGRATION'),
('V90.4', 'Accident to watercraft causing drowning and submersion: Sailboat', 'ICD10_2010', 'MIGRATION'),
('V90.5', 'Accident to watercraft causing drowning and submersion: Canoe or kayak', 'ICD10_2010', 'MIGRATION'),
('V90.6', 'Accident to watercraft causing drowning and submersion: Inflatable craft (nonpowered)', 'ICD10_2010', 'MIGRATION'),
('V90.7', 'Accident to watercraft causing drowning and submersion: Water-skis', 'ICD10_2010', 'MIGRATION'),
('V90.8', 'Accident to watercraft causing drowning and submersion: Other unpowered watercraft', 'ICD10_2010', 'MIGRATION'),
('V90.9', 'Accident to watercraft causing drowning and submersion: Unspecified watercraft', 'ICD10_2010', 'MIGRATION'),
('V91', 'Accident to watercraft causing other injury', 'ICD10_2010', 'MIGRATION'),
('V91.0', 'Accident to watercraft causing other injury: Merchant ship', 'ICD10_2010', 'MIGRATION'),
('V91.1', 'Accident to watercraft causing other injury: Passenger ship', 'ICD10_2010', 'MIGRATION'),
('V91.2', 'Accident to watercraft causing other injury: Fishing boat', 'ICD10_2010', 'MIGRATION'),
('V91.3', 'Accident to watercraft causing other injury: Other powered watercraft', 'ICD10_2010', 'MIGRATION'),
('V91.4', 'Accident to watercraft causing other injury: Sailboat', 'ICD10_2010', 'MIGRATION'),
('V91.5', 'Accident to watercraft causing other injury: Canoe or kayak', 'ICD10_2010', 'MIGRATION'),
('V91.6', 'Accident to watercraft causing other injury: Inflatable craft (nonpowered)', 'ICD10_2010', 'MIGRATION'),
('V91.7', 'Accident to watercraft causing other injury: Water-skis', 'ICD10_2010', 'MIGRATION'),
('V91.8', 'Accident to watercraft causing other injury: Other unpowered watercraft', 'ICD10_2010', 'MIGRATION'),
('V91.9', 'Accident to watercraft causing other injury: Unspecified watercraft', 'ICD10_2010', 'MIGRATION'),
('V92', 'Water-transport-related drowning and submersion without accident to watercraft', 'ICD10_2010', 'MIGRATION'),
('V92.0', 'Water-transport-related drowning and submersion without accident to watercraft: Merchant ship', 'ICD10_2010', 'MIGRATION'),
('V92.1', 'Water-transport-related drowning and submersion without accident to watercraft: Passenger ship', 'ICD10_2010', 'MIGRATION'),
('V92.2', 'Water-transport-related drowning and submersion without accident to watercraft: Fishing boat', 'ICD10_2010', 'MIGRATION'),
('V92.3', 'Water-transport-related drowning and submersion without accident to watercraft: Other powered watercraft', 'ICD10_2010', 'MIGRATION'),
('V92.4', 'Water-transport-related drowning and submersion without accident to watercraft: Sailboat', 'ICD10_2010', 'MIGRATION'),
('V92.5', 'Water-transport-related drowning and submersion without accident to watercraft: Canoe or kayak', 'ICD10_2010', 'MIGRATION'),
('V92.6', 'Water-transport-related drowning and submersion without accident to watercraft: Inflatable craft (nonpowered)', 'ICD10_2010', 'MIGRATION'),
('V92.7', 'Water-transport-related drowning and submersion without accident to watercraft: Water-skis', 'ICD10_2010', 'MIGRATION'),
('V92.8', 'Water-transport-related drowning and submersion without accident to watercraft: Other unpowered watercraft', 'ICD10_2010', 'MIGRATION'),
('V92.9', 'Water-transport-related drowning and submersion without accident to watercraft: Unspecified watercraft', 'ICD10_2010', 'MIGRATION'),
('V93', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('V93.0', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Merchant ship', 'ICD10_2010', 'MIGRATION'),
('V93.1', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Passenger ship', 'ICD10_2010', 'MIGRATION'),
('V93.2', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Fishing boat', 'ICD10_2010', 'MIGRATION'),
('V93.3', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Other powered watercraft', 'ICD10_2010', 'MIGRATION'),
('V93.4', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Sailboat', 'ICD10_2010', 'MIGRATION'),
('V93.5', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Canoe or kayak', 'ICD10_2010', 'MIGRATION'),
('V93.6', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Inflatable craft (nonpowered)', 'ICD10_2010', 'MIGRATION'),
('V93.7', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Water-skis', 'ICD10_2010', 'MIGRATION'),
('V93.8', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Other unpowered watercraft', 'ICD10_2010', 'MIGRATION'),
('V93.9', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion: Unspecified watercraft', 'ICD10_2010', 'MIGRATION'),
('V94', 'Other and unspecified water transport accidents', 'ICD10_2010', 'MIGRATION'),
('V94.0', 'Other and unspecified water transport accidents: Merchant ship', 'ICD10_2010', 'MIGRATION'),
('V94.1', 'Other and unspecified water transport accidents: Passenger ship', 'ICD10_2010', 'MIGRATION'),
('V94.2', 'Other and unspecified water transport accidents: Fishing boat', 'ICD10_2010', 'MIGRATION'),
('V94.3', 'Other and unspecified water transport accidents: Other powered watercraft', 'ICD10_2010', 'MIGRATION'),
('V94.4', 'Other and unspecified water transport accidents: Sailboat', 'ICD10_2010', 'MIGRATION'),
('V94.5', 'Other and unspecified water transport accidents: Canoe or kayak', 'ICD10_2010', 'MIGRATION'),
('V94.6', 'Other and unspecified water transport accidents: Inflatable craft (nonpowered)', 'ICD10_2010', 'MIGRATION'),
('V94.7', 'Other and unspecified water transport accidents: Water-skis', 'ICD10_2010', 'MIGRATION'),
('V94.8', 'Other and unspecified water transport accidents: Other unpowered watercraft', 'ICD10_2010', 'MIGRATION'),
('V94.9', 'Other and unspecified water transport accidents: Unspecified watercraft', 'ICD10_2010', 'MIGRATION'),
('V95', 'Accident to powered aircraft causing injury to occupant', 'ICD10_2010', 'MIGRATION'),
('V95.0', 'Helicopter accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.1', 'Ultralight, microlight or powered-glider accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.2', 'Accident to other private fixed-wing aircraft, injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.3', 'Accident to commercial fixed-wing aircraft, injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.4', 'Spacecraft accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.8', 'Other aircraft accidents injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V95.9', 'Unspecified aircraft accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V96', 'Accident to nonpowered aircraft causing injury to occupant', 'ICD10_2010', 'MIGRATION'),
('V96.0', 'Balloon accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V96.1', 'Hang-glider accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V96.2', 'Glider (nonpowered) accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V96.8', 'Other nonpowered-aircraft accidents injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V96.9', 'Unspecified nonpowered-aircraft accident injuring occupant', 'ICD10_2010', 'MIGRATION'),
('V97', 'Other specified air transport accidents', 'ICD10_2010', 'MIGRATION'),
('V97.0', 'Occupant of aircraft injured in other specified air transport accidents', 'ICD10_2010', 'MIGRATION'),
('V97.1', 'Person injured while boarding or alighting from aircraft', 'ICD10_2010', 'MIGRATION'),
('V97.2', 'Parachutist injured in air transport accident', 'ICD10_2010', 'MIGRATION'),
('V97.3', 'Person on ground injured in air transport accident', 'ICD10_2010', 'MIGRATION'),
('V97.8', 'Other air transport accidents, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('V98', 'Other specified transport accidents', 'ICD10_2010', 'MIGRATION'),
('V99', 'Unspecified transport accident', 'ICD10_2010', 'MIGRATION'),
('W00', 'Fall on same level involving ice and snow', 'ICD10_2010', 'MIGRATION'),
('W00.0', 'Fall on same level involving ice and snow, Home', 'ICD10_2010', 'MIGRATION'),
('W00.1', 'Fall on same level involving ice and snow, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W00.2', 'Fall on same level involving ice and snow, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W00.3', 'Fall on same level involving ice and snow, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W00.4', 'Fall on same level involving ice and snow, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W00.5', 'Fall on same level involving ice and snow, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W00.6', 'Fall on same level involving ice and snow, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W00.7', 'Fall on same level involving ice and snow, Farm', 'ICD10_2010', 'MIGRATION'),
('W00.8', 'Fall on same level involving ice and snow, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W00.9', 'Fall on same level involving ice and snow, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W01', 'Fall on same level from slipping, tripping and stumbling', 'ICD10_2010', 'MIGRATION'),
('W01.0', 'Fall on same level from slipping, tripping and stumbling, Home', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
