-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('W46.6', 'Contact with hypodermic needle, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W46.7', 'Contact with hypodermic needle, Farm', 'ICD10_2010', 'MIGRATION'),
('W46.8', 'Contact with hypodermic needle, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W46.9', 'Contact with hypodermic needle, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W49', 'Exposure to other and unspecified inanimate mechanical forces', 'ICD10_2010', 'MIGRATION'),
('W49.0', 'Exposure to other and unspecified inanimate mechanical forces, Home', 'ICD10_2010', 'MIGRATION'),
('W49.1', 'Exposure to other and unspecified inanimate mechanical forces, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W49.2', 'Exposure to other and unspecified inanimate mechanical forces, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W49.3', 'Exposure to other and unspecified inanimate mechanical forces, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W49.4', 'Exposure to other and unspecified inanimate mechanical forces, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W49.5', 'Exposure to other and unspecified inanimate mechanical forces, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W49.6', 'Exposure to other and unspecified inanimate mechanical forces, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W49.7', 'Exposure to other and unspecified inanimate mechanical forces, Farm', 'ICD10_2010', 'MIGRATION'),
('W49.8', 'Exposure to other and unspecified inanimate mechanical forces, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W49.9', 'Exposure to other and unspecified inanimate mechanical forces, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W50', 'Hit, struck, kicked, twisted, bitten or scratched by another person', 'ICD10_2010', 'MIGRATION'),
('W50.0', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Home', 'ICD10_2010', 'MIGRATION'),
('W50.1', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W50.2', 'Hit, struck, kicked, twisted, bitten or scratched by another person, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W50.3', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W50.4', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W50.5', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W50.6', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W50.7', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Farm', 'ICD10_2010', 'MIGRATION'),
('W50.8', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W50.9', 'Hit, struck, kicked, twisted, bitten or scratched by another person, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W51', 'Striking against or bumped into by another person', 'ICD10_2010', 'MIGRATION'),
('W51.0', 'Striking against or bumped into by another person, Home', 'ICD10_2010', 'MIGRATION'),
('W51.1', 'Striking against or bumped into by another person, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W51.2', 'Striking against or bumped into by another person, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W51.3', 'Striking against or bumped into by another person, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W51.4', 'Striking against or bumped into by another person, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W51.5', 'Striking against or bumped into by another person, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W51.6', 'Striking against or bumped into by another person, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W51.7', 'Striking against or bumped into by another person, Farm', 'ICD10_2010', 'MIGRATION'),
('W51.8', 'Striking against or bumped into by another person, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W51.9', 'Striking against or bumped into by another person, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W52', 'Crushed, pushed or stepped on by crowd or human stampede', 'ICD10_2010', 'MIGRATION'),
('W52.0', 'Crushed, pushed or stepped on by crowd or human stampede, Home', 'ICD10_2010', 'MIGRATION'),
('W52.1', 'Crushed, pushed or stepped on by crowd or human stampede, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W52.2', 'Crushed, pushed or stepped on by crowd or human stampede, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W52.3', 'Crushed, pushed or stepped on by crowd or human stampede, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W52.4', 'Crushed, pushed or stepped on by crowd or human stampede, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W52.5', 'Crushed, pushed or stepped on by crowd or human stampede, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W52.6', 'Crushed, pushed or stepped on by crowd or human stampede, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W52.7', 'Crushed, pushed or stepped on by crowd or human stampede, Farm', 'ICD10_2010', 'MIGRATION'),
('W52.8', 'Crushed, pushed or stepped on by crowd or human stampede, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W52.9', 'Crushed, pushed or stepped on by crowd or human stampede, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W53', 'Bitten by rat', 'ICD10_2010', 'MIGRATION'),
('W53.0', 'Bitten by rat, Home', 'ICD10_2010', 'MIGRATION'),
('W53.1', 'Bitten by rat, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W53.2', 'Bitten by rat, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W53.3', 'Bitten by rat, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W53.4', 'Bitten by rat, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W53.5', 'Bitten by rat, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W53.6', 'Bitten by rat, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W53.7', 'Bitten by rat, Farm', 'ICD10_2010', 'MIGRATION'),
('W53.8', 'Bitten by rat, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W53.9', 'Bitten by rat, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W54', 'Bitten or struck by dog', 'ICD10_2010', 'MIGRATION'),
('W54.0', 'Bitten or struck by dog, Home', 'ICD10_2010', 'MIGRATION'),
('W54.1', 'Bitten or struck by dog, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W54.2', 'Bitten or struck by dog, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W54.3', 'Bitten or struck by dog, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W54.4', 'Bitten or struck by dog, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W54.5', 'Bitten or struck by dog, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W54.6', 'Bitten or struck by dog, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W54.7', 'Bitten or struck by dog, Farm', 'ICD10_2010', 'MIGRATION'),
('W54.8', 'Bitten or struck by dog, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W54.9', 'Bitten or struck by dog, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W55', 'Bitten or struck by other mammals', 'ICD10_2010', 'MIGRATION'),
('W55.0', 'Bitten or struck by other mammals, Home', 'ICD10_2010', 'MIGRATION'),
('W55.1', 'Bitten or struck by other mammals, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W55.2', 'Bitten or struck by other mammals, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W55.3', 'Bitten or struck by other mammals, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W55.4', 'Bitten or struck by other mammals, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W55.5', 'Bitten or struck by other mammals, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W55.6', 'Bitten or struck by other mammals, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W55.7', 'Bitten or struck by other mammals, Farm', 'ICD10_2010', 'MIGRATION'),
('W55.8', 'Bitten or struck by other mammals, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W55.9', 'Bitten or struck by other mammals, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W56', 'Contact with marine animal', 'ICD10_2010', 'MIGRATION'),
('W56.0', 'Contact with marine animal, Home', 'ICD10_2010', 'MIGRATION'),
('W56.1', 'Contact with marine animal, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W56.2', 'Contact with marine animal, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W56.3', 'Contact with marine animal, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W56.4', 'Contact with marine animal, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W56.5', 'Contact with marine animal, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W56.6', 'Contact with marine animal, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W56.7', 'Contact with marine animal, Farm', 'ICD10_2010', 'MIGRATION'),
('W56.8', 'Contact with marine animal, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W56.9', 'Contact with marine animal, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W57', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods', 'ICD10_2010', 'MIGRATION'),
('W57.0', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Home', 'ICD10_2010', 'MIGRATION'),
('W57.1', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W57.2', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W57.3', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W57.4', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W57.5', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W57.6', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W57.7', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Farm', 'ICD10_2010', 'MIGRATION'),
('W57.8', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W57.9', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W58', 'Bitten or struck by crocodile or alligator', 'ICD10_2010', 'MIGRATION'),
('W58.0', 'Bitten or struck by crocodile or alligator, Home', 'ICD10_2010', 'MIGRATION'),
('W58.1', 'Bitten or struck by crocodile or alligator, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W58.2', 'Bitten or struck by crocodile or alligator, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W58.3', 'Bitten or struck by crocodile or alligator, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W58.4', 'Bitten or struck by crocodile or alligator, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W58.5', 'Bitten or struck by crocodile or alligator, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W58.6', 'Bitten or struck by crocodile or alligator, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W58.7', 'Bitten or struck by crocodile or alligator, Farm', 'ICD10_2010', 'MIGRATION'),
('W58.8', 'Bitten or struck by crocodile or alligator, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W58.9', 'Bitten or struck by crocodile or alligator, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W59', 'Bitten or crushed by other reptiles', 'ICD10_2010', 'MIGRATION'),
('W59.0', 'Bitten or crushed by other reptiles, Home', 'ICD10_2010', 'MIGRATION'),
('W59.1', 'Bitten or crushed by other reptiles, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W59.2', 'Bitten or crushed by other reptiles, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W59.3', 'Bitten or crushed by other reptiles, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W59.4', 'Bitten or crushed by other reptiles, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W59.5', 'Bitten or crushed by other reptiles, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W59.6', 'Bitten or crushed by other reptiles, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W59.7', 'Bitten or crushed by other reptiles, Farm', 'ICD10_2010', 'MIGRATION'),
('W59.8', 'Bitten or crushed by other reptiles, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W59.9', 'Bitten or crushed by other reptiles, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W60', 'Contact with plant thorns and spines and sharp leaves', 'ICD10_2010', 'MIGRATION'),
('W60.0', 'Contact with plant thorns and spines and sharp leaves, Home', 'ICD10_2010', 'MIGRATION'),
('W60.1', 'Contact with plant thorns and spines and sharp leaves, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W60.2', 'Contact with plant thorns and spines and sharp leaves, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W60.3', 'Contact with plant thorns and spines and sharp leaves, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W60.4', 'Contact with plant thorns and spines and sharp leaves, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W60.5', 'Contact with plant thorns and spines and sharp leaves, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W60.6', 'Contact with plant thorns and spines and sharp leaves, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W60.7', 'Contact with plant thorns and spines and sharp leaves, Farm', 'ICD10_2010', 'MIGRATION'),
('W60.8', 'Contact with plant thorns and spines and sharp leaves, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W60.9', 'Contact with plant thorns and spines and sharp leaves, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W64', 'Exposure to other and unspecified animate mechanical forces', 'ICD10_2010', 'MIGRATION'),
('W64.0', 'Exposure to other and unspecified animate mechanical forces, Home', 'ICD10_2010', 'MIGRATION'),
('W64.1', 'Exposure to other and unspecified animate mechanical forces, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W64.2', 'Exposure to other and unspecified animate mechanical forces, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W64.3', 'Exposure to other and unspecified animate mechanical forces, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W64.4', 'Exposure to other and unspecified animate mechanical forces, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W64.5', 'Exposure to other and unspecified animate mechanical forces, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W64.6', 'Exposure to other and unspecified animate mechanical forces, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W64.7', 'Exposure to other and unspecified animate mechanical forces, Farm', 'ICD10_2010', 'MIGRATION'),
('W64.8', 'Exposure to other and unspecified animate mechanical forces, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W64.9', 'Exposure to other and unspecified animate mechanical forces, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W65', 'Drowning and submersion while in bath-tub', 'ICD10_2010', 'MIGRATION'),
('W65.0', 'Drowning and submersion while in bath-tub, Home', 'ICD10_2010', 'MIGRATION'),
('W65.1', 'Drowning and submersion while in bath-tub, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W65.2', 'Drowning and submersion while in bath-tub, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W65.3', 'Drowning and submersion while in bath-tub, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W65.4', 'Drowning and submersion while in bath-tub, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W65.5', 'Drowning and submersion while in bath-tub, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W65.6', 'Drowning and submersion while in bath-tub, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W65.7', 'Drowning and submersion while in bath-tub, Farm', 'ICD10_2010', 'MIGRATION'),
('W65.8', 'Drowning and submersion while in bath-tub, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W65.9', 'Drowning and submersion while in bath-tub, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W66', 'Drowning and submersion following fall into bath-tub', 'ICD10_2010', 'MIGRATION'),
('W66.0', 'Drowning and submersion following fall into bath-tub, Home', 'ICD10_2010', 'MIGRATION'),
('W66.1', 'Drowning and submersion following fall into bath-tub, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W66.2', 'Drowning and submersion following fall into bath-tub, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W66.3', 'Drowning and submersion following fall into bath-tub, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W66.4', 'Drowning and submersion following fall into bath-tub, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W66.5', 'Drowning and submersion following fall into bath-tub, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W66.6', 'Drowning and submersion following fall into bath-tub, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W66.7', 'Drowning and submersion following fall into bath-tub, Farm', 'ICD10_2010', 'MIGRATION'),
('W66.8', 'Drowning and submersion following fall into bath-tub, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W66.9', 'Drowning and submersion following fall into bath-tub, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W67', 'Drowning and submersion while in swimming-pool', 'ICD10_2010', 'MIGRATION'),
('W67.0', 'Drowning and submersion while in swimming-pool, Home', 'ICD10_2010', 'MIGRATION'),
('W67.1', 'Drowning and submersion while in swimming-pool, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W67.2', 'Drowning and submersion while in swimming-pool, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W67.3', 'Drowning and submersion while in swimming-pool, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W67.4', 'Drowning and submersion while in swimming-pool, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W67.5', 'Drowning and submersion while in swimming-pool, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W67.6', 'Drowning and submersion while in swimming-pool, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W67.7', 'Drowning and submersion while in swimming-pool, Farm', 'ICD10_2010', 'MIGRATION'),
('W67.8', 'Drowning and submersion while in swimming-pool, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W67.9', 'Drowning and submersion while in swimming-pool, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W68', 'Drowning and submersion following fall into swimming-pool', 'ICD10_2010', 'MIGRATION'),
('W68.0', 'Drowning and submersion following fall into swimming-pool, Home', 'ICD10_2010', 'MIGRATION'),
('W68.1', 'Drowning and submersion following fall into swimming-pool, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W68.2', 'Drowning and submersion following fall into swimming-pool, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W68.3', 'Drowning and submersion following fall into swimming-pool, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W68.4', 'Drowning and submersion following fall into swimming-pool, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W68.5', 'Drowning and submersion following fall into swimming-pool, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W68.6', 'Drowning and submersion following fall into swimming-pool, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W68.7', 'Drowning and submersion following fall into swimming-pool, Farm', 'ICD10_2010', 'MIGRATION'),
('W68.8', 'Drowning and submersion following fall into swimming-pool, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W68.9', 'Drowning and submersion following fall into swimming-pool, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W69', 'Drowning and submersion while in natural water', 'ICD10_2010', 'MIGRATION'),
('W69.0', 'Drowning and submersion while in natural water, Home', 'ICD10_2010', 'MIGRATION'),
('W69.1', 'Drowning and submersion while in natural water, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W69.2', 'Drowning and submersion while in natural water, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W69.3', 'Drowning and submersion while in natural water, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W69.4', 'Drowning and submersion while in natural water, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W69.5', 'Drowning and submersion while in natural water, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W69.6', 'Drowning and submersion while in natural water, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W69.7', 'Drowning and submersion while in natural water, Farm', 'ICD10_2010', 'MIGRATION'),
('W69.8', 'Drowning and submersion while in natural water, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W69.9', 'Drowning and submersion while in natural water, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W70', 'Drowning and submersion following fall into natural water', 'ICD10_2010', 'MIGRATION'),
('W70.0', 'Drowning and submersion following fall into natural water, Home', 'ICD10_2010', 'MIGRATION'),
('W70.1', 'Drowning and submersion following fall into natural water, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W70.2', 'Drowning and submersion following fall into natural water, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W70.3', 'Drowning and submersion following fall into natural water, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W70.4', 'Drowning and submersion following fall into natural water, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W70.5', 'Drowning and submersion following fall into natural water, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W70.6', 'Drowning and submersion following fall into natural water, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W70.7', 'Drowning and submersion following fall into natural water, Farm', 'ICD10_2010', 'MIGRATION'),
('W70.8', 'Drowning and submersion following fall into natural water, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W70.9', 'Drowning and submersion following fall into natural water, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W73', 'Other specified drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('W73.0', 'Other specified drowning and submersion, Home', 'ICD10_2010', 'MIGRATION'),
('W73.1', 'Other specified drowning and submersion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W73.2', 'Other specified drowning and submersion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W73.3', 'Other specified drowning and submersion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W73.4', 'Other specified drowning and submersion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W73.5', 'Other specified drowning and submersion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W73.6', 'Other specified drowning and submersion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W73.7', 'Other specified drowning and submersion, Farm', 'ICD10_2010', 'MIGRATION'),
('W73.8', 'Other specified drowning and submersion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W73.9', 'Other specified drowning and submersion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W74', 'Unspecified drowning and submersion', 'ICD10_2010', 'MIGRATION'),
('W74.0', 'Unspecified drowning and submersion, Home', 'ICD10_2010', 'MIGRATION'),
('W74.1', 'Unspecified drowning and submersion, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W74.2', 'Unspecified drowning and submersion, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W74.3', 'Unspecified drowning and submersion, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W74.4', 'Unspecified drowning and submersion, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W74.5', 'Unspecified drowning and submersion, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W74.6', 'Unspecified drowning and submersion, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W74.7', 'Unspecified drowning and submersion, Farm', 'ICD10_2010', 'MIGRATION'),
('W74.8', 'Unspecified drowning and submersion, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W74.9', 'Unspecified drowning and submersion, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W75', 'Accidental suffocation and strangulation in bed', 'ICD10_2010', 'MIGRATION'),
('W75.0', 'Accidental suffocation and strangulation in bed, Home', 'ICD10_2010', 'MIGRATION'),
('W75.1', 'Accidental suffocation and strangulation in bed, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W75.2', 'Accidental suffocation and strangulation in bed, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W75.3', 'Accidental suffocation and strangulation in bed, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W75.4', 'Accidental suffocation and strangulation in bed, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W75.5', 'Accidental suffocation and strangulation in bed, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W75.6', 'Accidental suffocation and strangulation in bed, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W75.7', 'Accidental suffocation and strangulation in bed, Farm', 'ICD10_2010', 'MIGRATION'),
('W75.8', 'Accidental suffocation and strangulation in bed, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W75.9', 'Accidental suffocation and strangulation in bed, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W76', 'Other accidental hanging and strangulation', 'ICD10_2010', 'MIGRATION'),
('W76.0', 'Other accidental hanging and strangulation, Home', 'ICD10_2010', 'MIGRATION'),
('W76.1', 'Other accidental hanging and strangulation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W76.2', 'Other accidental hanging and strangulation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W76.3', 'Other accidental hanging and strangulation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W76.4', 'Other accidental hanging and strangulation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W76.5', 'Other accidental hanging and strangulation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W76.6', 'Other accidental hanging and strangulation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W76.7', 'Other accidental hanging and strangulation, Farm', 'ICD10_2010', 'MIGRATION'),
('W76.8', 'Other accidental hanging and strangulation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W76.9', 'Other accidental hanging and strangulation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W77', 'Threat to breathing due to cave-in, falling earth and other substances', 'ICD10_2010', 'MIGRATION'),
('W77.0', 'Threat to breathing due to cave-in, falling earth and other substances, Home', 'ICD10_2010', 'MIGRATION'),
('W77.1', 'Threat to breathing due to cave-in, falling earth and other substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W77.2', 'Threat to breathing due to cave-in, falling earth and other substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W77.3', 'Threat to breathing due to cave-in, falling earth and other substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W77.4', 'Threat to breathing due to cave-in, falling earth and other substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W77.5', 'Threat to breathing due to cave-in, falling earth and other substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W77.6', 'Threat to breathing due to cave-in, falling earth and other substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W77.7', 'Threat to breathing due to cave-in, falling earth and other substances, Farm', 'ICD10_2010', 'MIGRATION'),
('W77.8', 'Threat to breathing due to cave-in, falling earth and other substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W77.9', 'Threat to breathing due to cave-in, falling earth and other substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W78', 'Inhalation of gastric contents', 'ICD10_2010', 'MIGRATION'),
('W78.0', 'Inhalation of gastric contents, Home', 'ICD10_2010', 'MIGRATION'),
('W78.1', 'Inhalation of gastric contents, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W78.2', 'Inhalation of gastric contents, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W78.3', 'Inhalation of gastric contents, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W78.4', 'Inhalation of gastric contents, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W78.5', 'Inhalation of gastric contents, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W78.6', 'Inhalation of gastric contents, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W78.7', 'Inhalation of gastric contents, Farm', 'ICD10_2010', 'MIGRATION'),
('W78.8', 'Inhalation of gastric contents, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W78.9', 'Inhalation of gastric contents, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W79', 'Inhalation and ingestion of food causing obstruction of respiratory tract', 'ICD10_2010', 'MIGRATION'),
('W79.0', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Home', 'ICD10_2010', 'MIGRATION'),
('W79.1', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W79.2', 'Inhalation and ingestion of food causing obstruction of respiratory tract, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W79.3', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W79.4', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W79.5', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W79.6', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W79.7', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Farm', 'ICD10_2010', 'MIGRATION'),
('W79.8', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W79.9', 'Inhalation and ingestion of food causing obstruction of respiratory tract, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W80', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract', 'ICD10_2010', 'MIGRATION'),
('W80.0', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Home', 'ICD10_2010', 'MIGRATION'),
('W80.1', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W80.2', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W80.3', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W80.4', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W80.5', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W80.6', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W80.7', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Farm', 'ICD10_2010', 'MIGRATION'),
('W80.8', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W80.9', 'Inhalation and ingestion of other objects causing obstruction of respiratory tract, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W81', 'Confined to or trapped in a low-oxygen environment', 'ICD10_2010', 'MIGRATION'),
('W81.0', 'Confined to or trapped in a low-oxygen environment, Home', 'ICD10_2010', 'MIGRATION'),
('W81.1', 'Confined to or trapped in a low-oxygen environment, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W81.2', 'Confined to or trapped in a low-oxygen environment, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W81.3', 'Confined to or trapped in a low-oxygen environment, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W81.4', 'Confined to or trapped in a low-oxygen environment, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W81.5', 'Confined to or trapped in a low-oxygen environment, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W81.6', 'Confined to or trapped in a low-oxygen environment, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W81.7', 'Confined to or trapped in a low-oxygen environment, Farm', 'ICD10_2010', 'MIGRATION'),
('W81.8', 'Confined to or trapped in a low-oxygen environment, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W81.9', 'Confined to or trapped in a low-oxygen environment, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W83', 'Other specified threats to breathing', 'ICD10_2010', 'MIGRATION'),
('W83.0', 'Other specified threats to breathing, Home', 'ICD10_2010', 'MIGRATION'),
('W83.1', 'Other specified threats to breathing, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W83.2', 'Other specified threats to breathing, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W83.3', 'Other specified threats to breathing, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W83.4', 'Other specified threats to breathing, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W83.5', 'Other specified threats to breathing, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W83.6', 'Other specified threats to breathing, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W83.7', 'Other specified threats to breathing, Farm', 'ICD10_2010', 'MIGRATION'),
('W83.8', 'Other specified threats to breathing, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W83.9', 'Other specified threats to breathing, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W84', 'Unspecified threat to breathing', 'ICD10_2010', 'MIGRATION'),
('W84.0', 'Unspecified threat to breathing, Home', 'ICD10_2010', 'MIGRATION'),
('W84.1', 'Unspecified threat to breathing, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W84.2', 'Unspecified threat to breathing, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W84.3', 'Unspecified threat to breathing, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W84.4', 'Unspecified threat to breathing, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W84.5', 'Unspecified threat to breathing, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W84.6', 'Unspecified threat to breathing, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W84.7', 'Unspecified threat to breathing, Farm', 'ICD10_2010', 'MIGRATION'),
('W84.8', 'Unspecified threat to breathing, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W84.9', 'Unspecified threat to breathing, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W85', 'Exposure to electric transmission lines', 'ICD10_2010', 'MIGRATION'),
('W85.0', 'Exposure to electric transmission lines, Home', 'ICD10_2010', 'MIGRATION'),
('W85.1', 'Exposure to electric transmission lines, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W85.2', 'Exposure to electric transmission lines, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W85.3', 'Exposure to electric transmission lines, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W85.4', 'Exposure to electric transmission lines, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W85.5', 'Exposure to electric transmission lines, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W85.6', 'Exposure to electric transmission lines, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W85.7', 'Exposure to electric transmission lines, Farm', 'ICD10_2010', 'MIGRATION'),
('W85.8', 'Exposure to electric transmission lines, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W85.9', 'Exposure to electric transmission lines, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W86', 'Exposure to other specified electric current', 'ICD10_2010', 'MIGRATION'),
('W86.0', 'Exposure to other specified electric current, Home', 'ICD10_2010', 'MIGRATION'),
('W86.1', 'Exposure to other specified electric current, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W86.2', 'Exposure to other specified electric current, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W86.3', 'Exposure to other specified electric current, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W86.4', 'Exposure to other specified electric current, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W86.5', 'Exposure to other specified electric current, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W86.6', 'Exposure to other specified electric current, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W86.7', 'Exposure to other specified electric current, Farm', 'ICD10_2010', 'MIGRATION'),
('W86.8', 'Exposure to other specified electric current, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W86.9', 'Exposure to other specified electric current, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W87', 'Exposure to unspecified electric current', 'ICD10_2010', 'MIGRATION'),
('W87.0', 'Exposure to unspecified electric current, Home', 'ICD10_2010', 'MIGRATION'),
('W87.1', 'Exposure to unspecified electric current, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W87.2', 'Exposure to unspecified electric current, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W87.3', 'Exposure to unspecified electric current, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W87.4', 'Exposure to unspecified electric current, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W87.5', 'Exposure to unspecified electric current, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W87.6', 'Exposure to unspecified electric current, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W87.7', 'Exposure to unspecified electric current, Farm', 'ICD10_2010', 'MIGRATION'),
('W87.8', 'Exposure to unspecified electric current, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W87.9', 'Exposure to unspecified electric current, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W88', 'Exposure to ionizing radiation', 'ICD10_2010', 'MIGRATION'),
('W88.0', 'Exposure to ionizing radiation, Home', 'ICD10_2010', 'MIGRATION'),
('W88.1', 'Exposure to ionizing radiation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W88.2', 'Exposure to ionizing radiation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W88.3', 'Exposure to ionizing radiation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W88.4', 'Exposure to ionizing radiation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W88.5', 'Exposure to ionizing radiation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W88.6', 'Exposure to ionizing radiation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W88.7', 'Exposure to ionizing radiation, Farm', 'ICD10_2010', 'MIGRATION'),
('W88.8', 'Exposure to ionizing radiation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W88.9', 'Exposure to ionizing radiation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W89', 'Exposure to man-made visible and ultraviolet light', 'ICD10_2010', 'MIGRATION'),
('W89.0', 'Exposure to man-made visible and ultraviolet light, Home', 'ICD10_2010', 'MIGRATION'),
('W89.1', 'Exposure to man-made visible and ultraviolet light, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W89.2', 'Exposure to man-made visible and ultraviolet light, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W89.3', 'Exposure to man-made visible and ultraviolet light, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W89.4', 'Exposure to man-made visible and ultraviolet light, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W89.5', 'Exposure to man-made visible and ultraviolet light, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W89.6', 'Exposure to man-made visible and ultraviolet light, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W89.7', 'Exposure to man-made visible and ultraviolet light, Farm', 'ICD10_2010', 'MIGRATION'),
('W89.8', 'Exposure to man-made visible and ultraviolet light, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W89.9', 'Exposure to man-made visible and ultraviolet light, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W90', 'Exposure to other nonionizing radiation', 'ICD10_2010', 'MIGRATION'),
('W90.0', 'Exposure to other nonionizing radiation, Home', 'ICD10_2010', 'MIGRATION'),
('W90.1', 'Exposure to other nonionizing radiation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W90.2', 'Exposure to other nonionizing radiation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W90.3', 'Exposure to other nonionizing radiation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W90.4', 'Exposure to other nonionizing radiation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W90.5', 'Exposure to other nonionizing radiation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W90.6', 'Exposure to other nonionizing radiation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W90.7', 'Exposure to other nonionizing radiation, Farm', 'ICD10_2010', 'MIGRATION'),
('W90.8', 'Exposure to other nonionizing radiation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W90.9', 'Exposure to other nonionizing radiation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W91', 'Exposure to unspecified type of radiation', 'ICD10_2010', 'MIGRATION'),
('W91.0', 'Exposure to unspecified type of radiation, Home', 'ICD10_2010', 'MIGRATION'),
('W91.1', 'Exposure to unspecified type of radiation, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W91.2', 'Exposure to unspecified type of radiation, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W91.3', 'Exposure to unspecified type of radiation, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W91.4', 'Exposure to unspecified type of radiation, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W91.5', 'Exposure to unspecified type of radiation, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W91.6', 'Exposure to unspecified type of radiation, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W91.7', 'Exposure to unspecified type of radiation, Farm', 'ICD10_2010', 'MIGRATION'),
('W91.8', 'Exposure to unspecified type of radiation, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W91.9', 'Exposure to unspecified type of radiation, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W92', 'Exposure to excessive heat of man-made origin', 'ICD10_2010', 'MIGRATION'),
('W92.0', 'Exposure to excessive heat of man-made origin, Home', 'ICD10_2010', 'MIGRATION'),
('W92.1', 'Exposure to excessive heat of man-made origin, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W92.2', 'Exposure to excessive heat of man-made origin, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W92.3', 'Exposure to excessive heat of man-made origin, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W92.4', 'Exposure to excessive heat of man-made origin, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W92.5', 'Exposure to excessive heat of man-made origin, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W92.6', 'Exposure to excessive heat of man-made origin, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W92.7', 'Exposure to excessive heat of man-made origin, Farm', 'ICD10_2010', 'MIGRATION'),
('W92.8', 'Exposure to excessive heat of man-made origin, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W92.9', 'Exposure to excessive heat of man-made origin, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W93', 'Exposure to excessive cold of man-made origin', 'ICD10_2010', 'MIGRATION'),
('W93.0', 'Exposure to excessive cold of man-made origin, Home', 'ICD10_2010', 'MIGRATION'),
('W93.1', 'Exposure to excessive cold of man-made origin, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W93.2', 'Exposure to excessive cold of man-made origin, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W93.3', 'Exposure to excessive cold of man-made origin, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W93.4', 'Exposure to excessive cold of man-made origin, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W93.5', 'Exposure to excessive cold of man-made origin, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W93.6', 'Exposure to excessive cold of man-made origin, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W93.7', 'Exposure to excessive cold of man-made origin, Farm', 'ICD10_2010', 'MIGRATION'),
('W93.8', 'Exposure to excessive cold of man-made origin, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W93.9', 'Exposure to excessive cold of man-made origin, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W94', 'Exposure to high and low air pressure and changes in air pressure', 'ICD10_2010', 'MIGRATION'),
('W94.0', 'Exposure to high and low air pressure and changes in air pressure, Home', 'ICD10_2010', 'MIGRATION'),
('W94.1', 'Exposure to high and low air pressure and changes in air pressure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W94.2', 'Exposure to high and low air pressure and changes in air pressure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W94.3', 'Exposure to high and low air pressure and changes in air pressure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W94.4', 'Exposure to high and low air pressure and changes in air pressure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W94.5', 'Exposure to high and low air pressure and changes in air pressure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W94.6', 'Exposure to high and low air pressure and changes in air pressure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W94.7', 'Exposure to high and low air pressure and changes in air pressure, Farm', 'ICD10_2010', 'MIGRATION'),
('W94.8', 'Exposure to high and low air pressure and changes in air pressure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W94.9', 'Exposure to high and low air pressure and changes in air pressure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('W99', 'Exposure to other and unspecified man-made environmental factors', 'ICD10_2010', 'MIGRATION'),
('W99.0', 'Exposure to other and unspecified man-made environmental factors, Home', 'ICD10_2010', 'MIGRATION'),
('W99.1', 'Exposure to other and unspecified man-made environmental factors, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('W99.2', 'Exposure to other and unspecified man-made environmental factors, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('W99.3', 'Exposure to other and unspecified man-made environmental factors, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('W99.4', 'Exposure to other and unspecified man-made environmental factors, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('W99.5', 'Exposure to other and unspecified man-made environmental factors, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('W99.6', 'Exposure to other and unspecified man-made environmental factors, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('W99.7', 'Exposure to other and unspecified man-made environmental factors, Farm', 'ICD10_2010', 'MIGRATION'),
('W99.8', 'Exposure to other and unspecified man-made environmental factors, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('W99.9', 'Exposure to other and unspecified man-made environmental factors, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X00', 'Exposure to uncontrolled fire in building or structure', 'ICD10_2010', 'MIGRATION'),
('X00.0', 'Exposure to uncontrolled fire in building or structure, Home', 'ICD10_2010', 'MIGRATION'),
('X00.1', 'Exposure to uncontrolled fire in building or structure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X00.2', 'Exposure to uncontrolled fire in building or structure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X00.3', 'Exposure to uncontrolled fire in building or structure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X00.4', 'Exposure to uncontrolled fire in building or structure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X00.5', 'Exposure to uncontrolled fire in building or structure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X00.6', 'Exposure to uncontrolled fire in building or structure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X00.7', 'Exposure to uncontrolled fire in building or structure, Farm', 'ICD10_2010', 'MIGRATION'),
('X00.8', 'Exposure to uncontrolled fire in building or structure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X00.9', 'Exposure to uncontrolled fire in building or structure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X01', 'Exposure to uncontrolled fire, not in building or structure', 'ICD10_2010', 'MIGRATION'),
('X01.0', 'Exposure to uncontrolled fire, not in building or structure, Home', 'ICD10_2010', 'MIGRATION'),
('X01.1', 'Exposure to uncontrolled fire, not in building or structure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X01.2', 'Exposure to uncontrolled fire, not in building or structure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X01.3', 'Exposure to uncontrolled fire, not in building or structure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X01.4', 'Exposure to uncontrolled fire, not in building or structure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X01.5', 'Exposure to uncontrolled fire, not in building or structure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X01.6', 'Exposure to uncontrolled fire, not in building or structure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X01.7', 'Exposure to uncontrolled fire, not in building or structure, Farm', 'ICD10_2010', 'MIGRATION'),
('X01.8', 'Exposure to uncontrolled fire, not in building or structure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X01.9', 'Exposure to uncontrolled fire, not in building or structure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X02', 'Exposure to controlled fire in building or structure', 'ICD10_2010', 'MIGRATION'),
('X02.0', 'Exposure to controlled fire in building or structure, Home', 'ICD10_2010', 'MIGRATION'),
('X02.1', 'Exposure to controlled fire in building or structure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X02.2', 'Exposure to controlled fire in building or structure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X02.3', 'Exposure to controlled fire in building or structure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X02.4', 'Exposure to controlled fire in building or structure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X02.5', 'Exposure to controlled fire in building or structure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X02.6', 'Exposure to controlled fire in building or structure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X02.7', 'Exposure to controlled fire in building or structure, Farm', 'ICD10_2010', 'MIGRATION'),
('X02.8', 'Exposure to controlled fire in building or structure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X02.9', 'Exposure to controlled fire in building or structure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X03', 'Exposure to controlled fire, not in building or structure', 'ICD10_2010', 'MIGRATION'),
('X03.0', 'Exposure to controlled fire, not in building or structure, Home', 'ICD10_2010', 'MIGRATION'),
('X03.1', 'Exposure to controlled fire, not in building or structure, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X03.2', 'Exposure to controlled fire, not in building or structure, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X03.3', 'Exposure to controlled fire, not in building or structure, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X03.4', 'Exposure to controlled fire, not in building or structure, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X03.5', 'Exposure to controlled fire, not in building or structure, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X03.6', 'Exposure to controlled fire, not in building or structure, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X03.7', 'Exposure to controlled fire, not in building or structure, Farm', 'ICD10_2010', 'MIGRATION'),
('X03.8', 'Exposure to controlled fire, not in building or structure, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X03.9', 'Exposure to controlled fire, not in building or structure, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X04', 'Exposure to ignition of highly flammable material', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
