-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('X04.0', 'Exposure to ignition of highly flammable material, Home', 'ICD10_2010', 'MIGRATION'),
('X04.1', 'Exposure to ignition of highly flammable material, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X04.2', 'Exposure to ignition of highly flammable material, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X04.3', 'Exposure to ignition of highly flammable material, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X04.4', 'Exposure to ignition of highly flammable material, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X04.5', 'Exposure to ignition of highly flammable material, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X04.6', 'Exposure to ignition of highly flammable material, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X04.7', 'Exposure to ignition of highly flammable material, Farm', 'ICD10_2010', 'MIGRATION'),
('X04.8', 'Exposure to ignition of highly flammable material, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X04.9', 'Exposure to ignition of highly flammable material, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X05', 'Exposure to ignition or melting of nightwear', 'ICD10_2010', 'MIGRATION'),
('X05.0', 'Exposure to ignition or melting of nightwear, Home', 'ICD10_2010', 'MIGRATION'),
('X05.1', 'Exposure to ignition or melting of nightwear, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X05.2', 'Exposure to ignition or melting of nightwear, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X05.3', 'Exposure to ignition or melting of nightwear, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X05.4', 'Exposure to ignition or melting of nightwear, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X05.5', 'Exposure to ignition or melting of nightwear, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X05.6', 'Exposure to ignition or melting of nightwear, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X05.7', 'Exposure to ignition or melting of nightwear, Farm', 'ICD10_2010', 'MIGRATION'),
('X05.8', 'Exposure to ignition or melting of nightwear, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X05.9', 'Exposure to ignition or melting of nightwear, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X06', 'Exposure to ignition or melting of other clothing and apparel', 'ICD10_2010', 'MIGRATION'),
('X06.0', 'Exposure to ignition or melting of other clothing and apparel, Home', 'ICD10_2010', 'MIGRATION'),
('X06.1', 'Exposure to ignition or melting of other clothing and apparel, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X06.2', 'Exposure to ignition or melting of other clothing and apparel, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X06.3', 'Exposure to ignition or melting of other clothing and apparel, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X06.4', 'Exposure to ignition or melting of other clothing and apparel, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X06.5', 'Exposure to ignition or melting of other clothing and apparel, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X06.6', 'Exposure to ignition or melting of other clothing and apparel, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X06.7', 'Exposure to ignition or melting of other clothing and apparel, Farm', 'ICD10_2010', 'MIGRATION'),
('X06.8', 'Exposure to ignition or melting of other clothing and apparel, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X06.9', 'Exposure to ignition or melting of other clothing and apparel, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X08', 'Exposure to other specified smoke, fire and flames', 'ICD10_2010', 'MIGRATION'),
('X08.0', 'Exposure to other specified smoke, fire and flames, Home', 'ICD10_2010', 'MIGRATION'),
('X08.1', 'Exposure to other specified smoke, fire and flames, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X08.2', 'Exposure to other specified smoke, fire and flames, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X08.3', 'Exposure to other specified smoke, fire and flames, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X08.4', 'Exposure to other specified smoke, fire and flames, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X08.5', 'Exposure to other specified smoke, fire and flames, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X08.6', 'Exposure to other specified smoke, fire and flames, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X08.7', 'Exposure to other specified smoke, fire and flames, Farm', 'ICD10_2010', 'MIGRATION'),
('X08.8', 'Exposure to other specified smoke, fire and flames, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X08.9', 'Exposure to other specified smoke, fire and flames, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X09', 'Exposure to unspecified smoke, fire and flames', 'ICD10_2010', 'MIGRATION'),
('X09.0', 'Exposure to unspecified smoke, fire and flames, Home', 'ICD10_2010', 'MIGRATION'),
('X09.1', 'Exposure to unspecified smoke, fire and flames, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X09.2', 'Exposure to unspecified smoke, fire and flames, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X09.3', 'Exposure to unspecified smoke, fire and flames, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X09.4', 'Exposure to unspecified smoke, fire and flames, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X09.5', 'Exposure to unspecified smoke, fire and flames, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X09.6', 'Exposure to unspecified smoke, fire and flames, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X09.7', 'Exposure to unspecified smoke, fire and flames, Farm', 'ICD10_2010', 'MIGRATION'),
('X09.8', 'Exposure to unspecified smoke, fire and flames, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X09.9', 'Exposure to unspecified smoke, fire and flames, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X10', 'Contact with hot drinks, food, fats and cooking oils', 'ICD10_2010', 'MIGRATION'),
('X10.0', 'Contact with hot drinks, food, fats and cooking oils, Home', 'ICD10_2010', 'MIGRATION'),
('X10.1', 'Contact with hot drinks, food, fats and cooking oils, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X10.2', 'Contact with hot drinks, food, fats and cooking oils, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X10.3', 'Contact with hot drinks, food, fats and cooking oils, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X10.4', 'Contact with hot drinks, food, fats and cooking oils, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X10.5', 'Contact with hot drinks, food, fats and cooking oils, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X10.6', 'Contact with hot drinks, food, fats and cooking oils, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X10.7', 'Contact with hot drinks, food, fats and cooking oils, Farm', 'ICD10_2010', 'MIGRATION'),
('X10.8', 'Contact with hot drinks, food, fats and cooking oils, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X10.9', 'Contact with hot drinks, food, fats and cooking oils, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X11', 'Contact with hot tap-water', 'ICD10_2010', 'MIGRATION'),
('X11.0', 'Contact with hot tap-water, Home', 'ICD10_2010', 'MIGRATION'),
('X11.1', 'Contact with hot tap-water, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X11.2', 'Contact with hot tap-water, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X11.3', 'Contact with hot tap-water, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X11.4', 'Contact with hot tap-water, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X11.5', 'Contact with hot tap-water, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X11.6', 'Contact with hot tap-water, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X11.7', 'Contact with hot tap-water, Farm', 'ICD10_2010', 'MIGRATION'),
('X11.8', 'Contact with hot tap-water, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X11.9', 'Contact with hot tap-water, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X12', 'Contact with other hot fluids', 'ICD10_2010', 'MIGRATION'),
('X12.0', 'Contact with other hot fluids, Home', 'ICD10_2010', 'MIGRATION'),
('X12.1', 'Contact with other hot fluids, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X12.2', 'Contact with other hot fluids, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X12.3', 'Contact with other hot fluids, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X12.4', 'Contact with other hot fluids, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X12.5', 'Contact with other hot fluids, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X12.6', 'Contact with other hot fluids, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X12.7', 'Contact with other hot fluids, Farm', 'ICD10_2010', 'MIGRATION'),
('X12.8', 'Contact with other hot fluids, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X12.9', 'Contact with other hot fluids, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X13', 'Contact with steam and hot vapours', 'ICD10_2010', 'MIGRATION'),
('X13.0', 'Contact with steam and hot vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X13.1', 'Contact with steam and hot vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X13.2', 'Contact with steam and hot vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X13.3', 'Contact with steam and hot vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X13.4', 'Contact with steam and hot vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X13.5', 'Contact with steam and hot vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X13.6', 'Contact with steam and hot vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X13.7', 'Contact with steam and hot vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X13.8', 'Contact with steam and hot vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X13.9', 'Contact with steam and hot vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X14', 'Contact with hot air and gases', 'ICD10_2010', 'MIGRATION'),
('X14.0', 'Contact with hot air and gases, Home', 'ICD10_2010', 'MIGRATION'),
('X14.1', 'Contact with hot air and gases, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X14.2', 'Contact with hot air and gases, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X14.3', 'Contact with hot air and gases, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X14.4', 'Contact with hot air and gases, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X14.5', 'Contact with hot air and gases, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X14.6', 'Contact with hot air and gases, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X14.7', 'Contact with hot air and gases, Farm', 'ICD10_2010', 'MIGRATION'),
('X14.8', 'Contact with hot air and gases, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X14.9', 'Contact with hot air and gases, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X15', 'Contact with hot household appliances', 'ICD10_2010', 'MIGRATION'),
('X15.0', 'Contact with hot household appliances, Home', 'ICD10_2010', 'MIGRATION'),
('X15.1', 'Contact with hot household appliances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X15.2', 'Contact with hot household appliances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X15.3', 'Contact with hot household appliances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X15.4', 'Contact with hot household appliances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X15.5', 'Contact with hot household appliances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X15.6', 'Contact with hot household appliances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X15.7', 'Contact with hot household appliances, Farm', 'ICD10_2010', 'MIGRATION'),
('X15.8', 'Contact with hot household appliances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X15.9', 'Contact with hot household appliances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X16', 'Contact with hot heating appliances, radiators and pipes', 'ICD10_2010', 'MIGRATION'),
('X16.0', 'Contact with hot heating appliances, radiators and pipes, Home', 'ICD10_2010', 'MIGRATION'),
('X16.1', 'Contact with hot heating appliances, radiators and pipes, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X16.2', 'Contact with hot heating appliances, radiators and pipes, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X16.3', 'Contact with hot heating appliances, radiators and pipes, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X16.4', 'Contact with hot heating appliances, radiators and pipes, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X16.5', 'Contact with hot heating appliances, radiators and pipes, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X16.6', 'Contact with hot heating appliances, radiators and pipes, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X16.7', 'Contact with hot heating appliances, radiators and pipes, Farm', 'ICD10_2010', 'MIGRATION'),
('X16.8', 'Contact with hot heating appliances, radiators and pipes, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X16.9', 'Contact with hot heating appliances, radiators and pipes, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X17', 'Contact with hot engines, machinery and tools', 'ICD10_2010', 'MIGRATION'),
('X17.0', 'Contact with hot engines, machinery and tools, Home', 'ICD10_2010', 'MIGRATION'),
('X17.1', 'Contact with hot engines, machinery and tools, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X17.2', 'Contact with hot engines, machinery and tools, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X17.3', 'Contact with hot engines, machinery and tools, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X17.4', 'Contact with hot engines, machinery and tools, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X17.5', 'Contact with hot engines, machinery and tools, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X17.6', 'Contact with hot engines, machinery and tools, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X17.7', 'Contact with hot engines, machinery and tools, Farm', 'ICD10_2010', 'MIGRATION'),
('X17.8', 'Contact with hot engines, machinery and tools, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X17.9', 'Contact with hot engines, machinery and tools, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X18', 'Contact with other hot metals', 'ICD10_2010', 'MIGRATION'),
('X18.0', 'Contact with other hot metals, Home', 'ICD10_2010', 'MIGRATION'),
('X18.1', 'Contact with other hot metals, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X18.2', 'Contact with other hot metals, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X18.3', 'Contact with other hot metals, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X18.4', 'Contact with other hot metals, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X18.5', 'Contact with other hot metals, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X18.6', 'Contact with other hot metals, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X18.7', 'Contact with other hot metals, Farm', 'ICD10_2010', 'MIGRATION'),
('X18.8', 'Contact with other hot metals, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X18.9', 'Contact with other hot metals, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X19', 'Contact with other and unspecified heat and hot substances', 'ICD10_2010', 'MIGRATION'),
('X19.0', 'Contact with other and unspecified heat and hot substances, Home', 'ICD10_2010', 'MIGRATION'),
('X19.1', 'Contact with other and unspecified heat and hot substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X19.2', 'Contact with other and unspecified heat and hot substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X19.3', 'Contact with other and unspecified heat and hot substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X19.4', 'Contact with other and unspecified heat and hot substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X19.5', 'Contact with other and unspecified heat and hot substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X19.6', 'Contact with other and unspecified heat and hot substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X19.7', 'Contact with other and unspecified heat and hot substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X19.8', 'Contact with other and unspecified heat and hot substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X19.9', 'Contact with other and unspecified heat and hot substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X20', 'Contact with venomous snakes and lizards', 'ICD10_2010', 'MIGRATION'),
('X20.0', 'Contact with venomous snakes and lizards, Home', 'ICD10_2010', 'MIGRATION'),
('X20.1', 'Contact with venomous snakes and lizards, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X20.2', 'Contact with venomous snakes and lizards, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X20.3', 'Contact with venomous snakes and lizards, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X20.4', 'Contact with venomous snakes and lizards, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X20.5', 'Contact with venomous snakes and lizards, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X20.6', 'Contact with venomous snakes and lizards, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X20.7', 'Contact with venomous snakes and lizards, Farm', 'ICD10_2010', 'MIGRATION'),
('X20.8', 'Contact with venomous snakes and lizards, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X20.9', 'Contact with venomous snakes and lizards, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X21', 'Contact with venomous spiders', 'ICD10_2010', 'MIGRATION'),
('X21.0', 'Contact with venomous spiders, Home', 'ICD10_2010', 'MIGRATION'),
('X21.1', 'Contact with venomous spiders, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X21.2', 'Contact with venomous spiders, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X21.3', 'Contact with venomous spiders, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X21.4', 'Contact with venomous spiders, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X21.5', 'Contact with venomous spiders, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X21.6', 'Contact with venomous spiders, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X21.7', 'Contact with venomous spiders, Farm', 'ICD10_2010', 'MIGRATION'),
('X21.8', 'Contact with venomous spiders, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X21.9', 'Contact with venomous spiders, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X22', 'Contact with scorpions', 'ICD10_2010', 'MIGRATION'),
('X22.0', 'Contact with scorpions, Home', 'ICD10_2010', 'MIGRATION'),
('X22.1', 'Contact with scorpions, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X22.2', 'Contact with scorpions, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X22.3', 'Contact with scorpions, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X22.4', 'Contact with scorpions, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X22.5', 'Contact with scorpions, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X22.6', 'Contact with scorpions, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X22.7', 'Contact with scorpions, Farm', 'ICD10_2010', 'MIGRATION'),
('X22.8', 'Contact with scorpions, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X22.9', 'Contact with scorpions, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X23', 'Contact with hornets, wasps and bees', 'ICD10_2010', 'MIGRATION'),
('X23.0', 'Contact with hornets, wasps and bees, Home', 'ICD10_2010', 'MIGRATION'),
('X23.1', 'Contact with hornets, wasps and bees, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X23.2', 'Contact with hornets, wasps and bees, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X23.3', 'Contact with hornets, wasps and bees, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X23.4', 'Contact with hornets, wasps and bees, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X23.5', 'Contact with hornets, wasps and bees, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X23.6', 'Contact with hornets, wasps and bees, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X23.7', 'Contact with hornets, wasps and bees, Farm', 'ICD10_2010', 'MIGRATION'),
('X23.8', 'Contact with hornets, wasps and bees, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X23.9', 'Contact with hornets, wasps and bees, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X24', 'Contact with centipedes and venomous millipedes (tropical)', 'ICD10_2010', 'MIGRATION'),
('X24.0', 'Contact with centipedes and venomous millipedes (tropical), Home', 'ICD10_2010', 'MIGRATION'),
('X24.1', 'Contact with centipedes and venomous millipedes (tropical), Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X24.2', 'Contact with centipedes and venomous millipedes (tropical), School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X24.3', 'Contact with centipedes and venomous millipedes (tropical), Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X24.4', 'Contact with centipedes and venomous millipedes (tropical), Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X24.5', 'Contact with centipedes and venomous millipedes (tropical), Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X24.6', 'Contact with centipedes and venomous millipedes (tropical), Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X24.7', 'Contact with centipedes and venomous millipedes (tropical), Farm', 'ICD10_2010', 'MIGRATION'),
('X24.8', 'Contact with centipedes and venomous millipedes (tropical), Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X24.9', 'Contact with centipedes and venomous millipedes (tropical), Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X25', 'Contact with other venomous arthropods', 'ICD10_2010', 'MIGRATION'),
('X25.0', 'Contact with other venomous arthropods, Home', 'ICD10_2010', 'MIGRATION'),
('X25.1', 'Contact with other venomous arthropods, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X25.2', 'Contact with other venomous arthropods, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X25.3', 'Contact with other venomous arthropods, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X25.4', 'Contact with other venomous arthropods, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X25.5', 'Contact with other venomous arthropods, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X25.6', 'Contact with other venomous arthropods, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X25.7', 'Contact with other venomous arthropods, Farm', 'ICD10_2010', 'MIGRATION'),
('X25.8', 'Contact with other venomous arthropods, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X25.9', 'Contact with other venomous arthropods, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X26', 'Contact with venomous marine animals and plants', 'ICD10_2010', 'MIGRATION'),
('X26.0', 'Contact with venomous marine animals and plants, Home', 'ICD10_2010', 'MIGRATION'),
('X26.1', 'Contact with venomous marine animals and plants, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X26.2', 'Contact with venomous marine animals and plants, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X26.3', 'Contact with venomous marine animals and plants, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X26.4', 'Contact with venomous marine animals and plants, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X26.5', 'Contact with venomous marine animals and plants, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X26.6', 'Contact with venomous marine animals and plants, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X26.7', 'Contact with venomous marine animals and plants, Farm', 'ICD10_2010', 'MIGRATION'),
('X26.8', 'Contact with venomous marine animals and plants, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X26.9', 'Contact with venomous marine animals and plants, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X27', 'Contact with other specified venomous animals', 'ICD10_2010', 'MIGRATION'),
('X27.0', 'Contact with other specified venomous animals, Home', 'ICD10_2010', 'MIGRATION'),
('X27.1', 'Contact with other specified venomous animals, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X27.2', 'Contact with other specified venomous animals, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X27.3', 'Contact with other specified venomous animals, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X27.4', 'Contact with other specified venomous animals, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X27.5', 'Contact with other specified venomous animals, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X27.6', 'Contact with other specified venomous animals, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X27.7', 'Contact with other specified venomous animals, Farm', 'ICD10_2010', 'MIGRATION'),
('X27.8', 'Contact with other specified venomous animals, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X27.9', 'Contact with other specified venomous animals, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X28', 'Contact with other specified venomous plants', 'ICD10_2010', 'MIGRATION'),
('X28.0', 'Contact with other specified venomous plants, Home', 'ICD10_2010', 'MIGRATION'),
('X28.1', 'Contact with other specified venomous plants, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X28.2', 'Contact with other specified venomous plants, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X28.3', 'Contact with other specified venomous plants, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X28.4', 'Contact with other specified venomous plants, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X28.5', 'Contact with other specified venomous plants, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X28.6', 'Contact with other specified venomous plants, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X28.7', 'Contact with other specified venomous plants, Farm', 'ICD10_2010', 'MIGRATION'),
('X28.8', 'Contact with other specified venomous plants, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X28.9', 'Contact with other specified venomous plants, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X29', 'Contact with unspecified venomous animal or plant', 'ICD10_2010', 'MIGRATION'),
('X29.0', 'Contact with unspecified venomous animal or plant, Home', 'ICD10_2010', 'MIGRATION'),
('X29.1', 'Contact with unspecified venomous animal or plant, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X29.2', 'Contact with unspecified venomous animal or plant, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X29.3', 'Contact with unspecified venomous animal or plant, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X29.4', 'Contact with unspecified venomous animal or plant, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X29.5', 'Contact with unspecified venomous animal or plant, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X29.6', 'Contact with unspecified venomous animal or plant, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X29.7', 'Contact with unspecified venomous animal or plant, Farm', 'ICD10_2010', 'MIGRATION'),
('X29.8', 'Contact with unspecified venomous animal or plant, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X29.9', 'Contact with unspecified venomous animal or plant, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X30', 'Exposure to excessive natural heat', 'ICD10_2010', 'MIGRATION'),
('X30.0', 'Exposure to excessive natural heat, Home', 'ICD10_2010', 'MIGRATION'),
('X30.1', 'Exposure to excessive natural heat, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X30.2', 'Exposure to excessive natural heat, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X30.3', 'Exposure to excessive natural heat, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X30.4', 'Exposure to excessive natural heat, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X30.5', 'Exposure to excessive natural heat, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X30.6', 'Exposure to excessive natural heat, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X30.7', 'Exposure to excessive natural heat, Farm', 'ICD10_2010', 'MIGRATION'),
('X30.8', 'Exposure to excessive natural heat, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X30.9', 'Exposure to excessive natural heat, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X31', 'Exposure to excessive natural cold', 'ICD10_2010', 'MIGRATION'),
('X31.0', 'Exposure to excessive natural cold, Home', 'ICD10_2010', 'MIGRATION'),
('X31.1', 'Exposure to excessive natural cold, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X31.2', 'Exposure to excessive natural cold, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X31.3', 'Exposure to excessive natural cold, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X31.4', 'Exposure to excessive natural cold, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X31.5', 'Exposure to excessive natural cold, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X31.6', 'Exposure to excessive natural cold, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X31.7', 'Exposure to excessive natural cold, Farm', 'ICD10_2010', 'MIGRATION'),
('X31.8', 'Exposure to excessive natural cold, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X31.9', 'Exposure to excessive natural cold, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X32', 'Exposure to sunlight', 'ICD10_2010', 'MIGRATION'),
('X32.0', 'Exposure to sunlight, Home', 'ICD10_2010', 'MIGRATION'),
('X32.1', 'Exposure to sunlight, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X32.2', 'Exposure to sunlight, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X32.3', 'Exposure to sunlight, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X32.4', 'Exposure to sunlight, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X32.5', 'Exposure to sunlight, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X32.6', 'Exposure to sunlight, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X32.7', 'Exposure to sunlight, Farm', 'ICD10_2010', 'MIGRATION'),
('X32.8', 'Exposure to sunlight, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X32.9', 'Exposure to sunlight, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X33', 'Victim of lightning', 'ICD10_2010', 'MIGRATION'),
('X33.0', 'Victim of lightning, Home', 'ICD10_2010', 'MIGRATION'),
('X33.1', 'Victim of lightning, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X33.2', 'Victim of lightning, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X33.3', 'Victim of lightning, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X33.4', 'Victim of lightning, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X33.5', 'Victim of lightning, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X33.6', 'Victim of lightning, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X33.7', 'Victim of lightning, Farm', 'ICD10_2010', 'MIGRATION'),
('X33.8', 'Victim of lightning, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X33.9', 'Victim of lightning, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X34', 'Victim of earthquake', 'ICD10_2010', 'MIGRATION'),
('X34.0', 'Victim of earthquake, Home', 'ICD10_2010', 'MIGRATION'),
('X34.1', 'Victim of earthquake, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X34.2', 'Victim of earthquake, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X34.3', 'Victim of earthquake, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X34.4', 'Victim of earthquake, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X34.5', 'Victim of earthquake, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X34.6', 'Victim of earthquake, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X34.7', 'Victim of earthquake, Farm', 'ICD10_2010', 'MIGRATION'),
('X34.8', 'Victim of earthquake, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X34.9', 'Victim of earthquake, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X35', 'Victim of volcanic eruption', 'ICD10_2010', 'MIGRATION'),
('X35.0', 'Victim of volcanic eruption, Home', 'ICD10_2010', 'MIGRATION'),
('X35.1', 'Victim of volcanic eruption, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X35.2', 'Victim of volcanic eruption, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X35.3', 'Victim of volcanic eruption, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X35.4', 'Victim of volcanic eruption, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X35.5', 'Victim of volcanic eruption, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X35.6', 'Victim of volcanic eruption, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X35.7', 'Victim of volcanic eruption, Farm', 'ICD10_2010', 'MIGRATION'),
('X35.8', 'Victim of volcanic eruption, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X35.9', 'Victim of volcanic eruption, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X36', 'Victim of avalanche, landslide and other earth movements', 'ICD10_2010', 'MIGRATION'),
('X36.0', 'Victim of avalanche, landslide and other earth movements, Home', 'ICD10_2010', 'MIGRATION'),
('X36.1', 'Victim of avalanche, landslide and other earth movements, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X36.2', 'Victim of avalanche, landslide and other earth movements, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X36.3', 'Victim of avalanche, landslide and other earth movements, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X36.4', 'Victim of avalanche, landslide and other earth movements, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X36.5', 'Victim of avalanche, landslide and other earth movements, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X36.6', 'Victim of avalanche, landslide and other earth movements, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X36.7', 'Victim of avalanche, landslide and other earth movements, Farm', 'ICD10_2010', 'MIGRATION'),
('X36.8', 'Victim of avalanche, landslide and other earth movements, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X36.9', 'Victim of avalanche, landslide and other earth movements, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X37', 'Victim of cataclysmic storm', 'ICD10_2010', 'MIGRATION'),
('X37.0', 'Victim of cataclysmic storm, Home', 'ICD10_2010', 'MIGRATION'),
('X37.1', 'Victim of cataclysmic storm, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X37.2', 'Victim of cataclysmic storm, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X37.3', 'Victim of cataclysmic storm, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X37.4', 'Victim of cataclysmic storm, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X37.5', 'Victim of cataclysmic storm, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X37.6', 'Victim of cataclysmic storm, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X37.7', 'Victim of cataclysmic storm, Farm', 'ICD10_2010', 'MIGRATION'),
('X37.8', 'Victim of cataclysmic storm, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X37.9', 'Victim of cataclysmic storm, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X38', 'Victim of flood', 'ICD10_2010', 'MIGRATION'),
('X38.0', 'Victim of flood, Home', 'ICD10_2010', 'MIGRATION'),
('X38.1', 'Victim of flood, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X38.2', 'Victim of flood, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X38.3', 'Victim of flood, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X38.4', 'Victim of flood, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X38.5', 'Victim of flood, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X38.6', 'Victim of flood, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X38.7', 'Victim of flood, Farm', 'ICD10_2010', 'MIGRATION'),
('X38.8', 'Victim of flood, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X38.9', 'Victim of flood, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X39', 'Exposure to other and unspecified forces of nature', 'ICD10_2010', 'MIGRATION'),
('X39.0', 'Exposure to other and unspecified forces of nature, Home', 'ICD10_2010', 'MIGRATION'),
('X39.1', 'Exposure to other and unspecified forces of nature, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X39.2', 'Exposure to other and unspecified forces of nature, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X39.3', 'Exposure to other and unspecified forces of nature, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X39.4', 'Exposure to other and unspecified forces of nature, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X39.5', 'Exposure to other and unspecified forces of nature, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X39.6', 'Exposure to other and unspecified forces of nature, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X39.7', 'Exposure to other and unspecified forces of nature, Farm', 'ICD10_2010', 'MIGRATION'),
('X39.8', 'Exposure to other and unspecified forces of nature, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X39.9', 'Exposure to other and unspecified forces of nature, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X40', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics', 'ICD10_2010', 'MIGRATION'),
('X40.0', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Home', 'ICD10_2010', 'MIGRATION'),
('X40.1', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X40.2', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X40.3', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X40.4', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X40.5', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X40.6', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X40.7', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Farm', 'ICD10_2010', 'MIGRATION'),
('X40.8', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X40.9', 'Accidental poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X41', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('X41.0', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Home', 'ICD10_2010', 'MIGRATION'),
('X41.1', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X41.2', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X41.3', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X41.4', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X41.5', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X41.6', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X41.7', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Farm', 'ICD10_2010', 'MIGRATION'),
('X41.8', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X41.9', 'Accidental poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X42', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('X42.0', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Home', 'ICD10_2010', 'MIGRATION'),
('X42.1', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X42.2', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X42.3', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X42.4', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X42.5', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X42.6', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X42.7', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Farm', 'ICD10_2010', 'MIGRATION'),
('X42.8', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X42.9', 'Accidental poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X43', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system', 'ICD10_2010', 'MIGRATION'),
('X43.0', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Home', 'ICD10_2010', 'MIGRATION'),
('X43.1', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X43.2', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X43.3', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X43.4', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X43.5', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X43.6', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X43.7', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Farm', 'ICD10_2010', 'MIGRATION'),
('X43.8', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X43.9', 'Accidental poisoning by and exposure to other drugs acting on the autonomic nervous system, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X44', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances', 'ICD10_2010', 'MIGRATION'),
('X44.0', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Home', 'ICD10_2010', 'MIGRATION'),
('X44.1', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X44.2', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X44.3', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X44.4', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X44.5', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X44.6', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X44.7', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X44.8', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X44.9', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X45', 'Accidental poisoning by and exposure to alcohol', 'ICD10_2010', 'MIGRATION'),
('X45.0', 'Accidental poisoning by and exposure to alcohol, Home', 'ICD10_2010', 'MIGRATION'),
('X45.1', 'Accidental poisoning by and exposure to alcohol, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X45.2', 'Accidental poisoning by and exposure to alcohol, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X45.3', 'Accidental poisoning by and exposure to alcohol, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X45.4', 'Accidental poisoning by and exposure to alcohol, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X45.5', 'Accidental poisoning by and exposure to alcohol, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X45.6', 'Accidental poisoning by and exposure to alcohol, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X45.7', 'Accidental poisoning by and exposure to alcohol, Farm', 'ICD10_2010', 'MIGRATION'),
('X45.8', 'Accidental poisoning by and exposure to alcohol, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X45.9', 'Accidental poisoning by and exposure to alcohol, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X46', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours', 'ICD10_2010', 'MIGRATION'),
('X46.0', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X46.1', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X46.2', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X46.3', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X46.4', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X46.5', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X46.6', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X46.7', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X46.8', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X46.9', 'Accidental poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X47', 'Accidental poisoning by and exposure to other gases and vapours', 'ICD10_2010', 'MIGRATION'),
('X47.0', 'Accidental poisoning by and exposure to other gases and vapours, Home', 'ICD10_2010', 'MIGRATION'),
('X47.1', 'Accidental poisoning by and exposure to other gases and vapours, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X47.2', 'Accidental poisoning by and exposure to other gases and vapours, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X47.3', 'Accidental poisoning by and exposure to other gases and vapours, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X47.4', 'Accidental poisoning by and exposure to other gases and vapours, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X47.5', 'Accidental poisoning by and exposure to other gases and vapours, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X47.6', 'Accidental poisoning by and exposure to other gases and vapours, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X47.7', 'Accidental poisoning by and exposure to other gases and vapours, Farm', 'ICD10_2010', 'MIGRATION'),
('X47.8', 'Accidental poisoning by and exposure to other gases and vapours, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X47.9', 'Accidental poisoning by and exposure to other gases and vapours, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X48', 'Accidental poisoning by and exposure to pesticides', 'ICD10_2010', 'MIGRATION'),
('X48.0', 'Accidental poisoning by and exposure to pesticides, Home', 'ICD10_2010', 'MIGRATION'),
('X48.1', 'Accidental poisoning by and exposure to pesticides, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X48.2', 'Accidental poisoning by and exposure to pesticides, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X48.3', 'Accidental poisoning by and exposure to pesticides, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X48.4', 'Accidental poisoning by and exposure to pesticides, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X48.5', 'Accidental poisoning by and exposure to pesticides, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X48.6', 'Accidental poisoning by and exposure to pesticides, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X48.7', 'Accidental poisoning by and exposure to pesticides, Farm', 'ICD10_2010', 'MIGRATION'),
('X48.8', 'Accidental poisoning by and exposure to pesticides, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X48.9', 'Accidental poisoning by and exposure to pesticides, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X49', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances', 'ICD10_2010', 'MIGRATION'),
('X49.0', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Home', 'ICD10_2010', 'MIGRATION'),
('X49.1', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X49.2', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X49.3', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X49.4', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Street and Highway', 'ICD10_2010', 'MIGRATION'),
('X49.5', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Trade and Service Area', 'ICD10_2010', 'MIGRATION'),
('X49.6', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Industrial and Construction Area', 'ICD10_2010', 'MIGRATION'),
('X49.7', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Farm', 'ICD10_2010', 'MIGRATION'),
('X49.8', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Other Specified Area', 'ICD10_2010', 'MIGRATION'),
('X49.9', 'Accidental poisoning by and exposure to other and unspecified chemicals and noxious substances, Unspecified Place', 'ICD10_2010', 'MIGRATION'),
('X50', 'Overexertion and strenuous or repetitive movements', 'ICD10_2010', 'MIGRATION'),
('X50.0', 'Overexertion and strenuous or repetitive movements, Home', 'ICD10_2010', 'MIGRATION'),
('X50.1', 'Overexertion and strenuous or repetitive movements, Residential Institution', 'ICD10_2010', 'MIGRATION'),
('X50.2', 'Overexertion and strenuous or repetitive movements, School, Other Institution and Public Admimistration Area', 'ICD10_2010', 'MIGRATION'),
('X50.3', 'Overexertion and strenuous or repetitive movements, Sports and Athletic Areas', 'ICD10_2010', 'MIGRATION'),
('X50.4', 'Overexertion and strenuous or repetitive movements, Street and Highway', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
