-- +migrate Up
INSERT INTO diagnosa (kode_icd10, nama_diagnosa, deskripsi, created_by) VALUES
('O26.6', 'Liver disorders in pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O26.7', 'Subluxation of symphysis pubis in  pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O26.8', 'Other specified pregnancy-related conditions', 'ICD10_2010', 'MIGRATION'),
('O26.9', 'Pregnancy-related condition, unspecified', 'ICD10_2010', 'MIGRATION'),
('O28', 'Abnormal findings on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.0', 'Abnormal haematological  finding on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.1', 'Abnormal biochemical finding on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.2', 'Abnormal cytological finding on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.3', 'Abnormal ultrasonic finding on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.4', 'Abnormal radiological find on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.5', 'Abnormal chromosomal and genetic finding antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.8', 'Other abnormal findings on antenatal screening of mother', 'ICD10_2010', 'MIGRATION'),
('O28.9', 'Abnormal finding on antenatal screening of mother, unspecified', 'ICD10_2010', 'MIGRATION'),
('O29', 'Complications of anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.0', 'Pulmonary complications of anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.1', 'Cardiac complications of anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.2', 'Central nervous system complications of anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.3', 'Toxic reaction to local anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.4', 'Spinal and epidural anaesthesia-induced headache during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.5', 'Other complications of spinal and epidural anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.6', 'Failed or difficult intubation during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.8', 'Other complications of anaesthesia during pregnancy', 'ICD10_2010', 'MIGRATION'),
('O29.9', 'Complication of anaesthesia during pregnancy, unspecified', 'ICD10_2010', 'MIGRATION'),
('O30', 'Multiple gestation', 'ICD10_2010', 'MIGRATION'),
('O30.0', 'Twin pregnancy', 'ICD10_2010', 'MIGRATION'),
('O30.1', 'Triplet pregnancy', 'ICD10_2010', 'MIGRATION'),
('O30.2', 'Quadruplet pregnancy', 'ICD10_2010', 'MIGRATION'),
('O30.8', 'Other multiple gestation', 'ICD10_2010', 'MIGRATION'),
('O30.9', 'Multiple gestation, unspecified', 'ICD10_2010', 'MIGRATION'),
('O31', 'Complications specific to multiple gestation', 'ICD10_2010', 'MIGRATION'),
('O31.0', 'Papyraceous fetus', 'ICD10_2010', 'MIGRATION'),
('O31.1', 'Continuing pregnancy after abortion of one fetus or more', 'ICD10_2010', 'MIGRATION'),
('O31.2', 'Continuing pregnancy after intrauterine death of one fetus or more', 'ICD10_2010', 'MIGRATION'),
('O31.8', 'Other complications specific to multiple gestation', 'ICD10_2010', 'MIGRATION'),
('O32', 'Maternal care for known or suspected malpresentation of fetus', 'ICD10_2010', 'MIGRATION'),
('O32.0', 'Maternal care for unstable lie', 'ICD10_2010', 'MIGRATION'),
('O32.1', 'Maternal care for breech presentation', 'ICD10_2010', 'MIGRATION'),
('O32.2', 'Maternal care for transverse and oblique lie', 'ICD10_2010', 'MIGRATION'),
('O32.3', 'Maternal care for face, brow and chin presentation', 'ICD10_2010', 'MIGRATION'),
('O32.4', 'Maternal care for high head at term', 'ICD10_2010', 'MIGRATION'),
('O32.5', 'Maternal care for multiple gestation with malpresentation of one fetus or more', 'ICD10_2010', 'MIGRATION'),
('O32.6', 'Maternal care for compound presentation', 'ICD10_2010', 'MIGRATION'),
('O32.8', 'Maternal care for other malpresentation of fetus', 'ICD10_2010', 'MIGRATION'),
('O32.9', 'Maternal care for malpresentation of fetus, unspecified', 'ICD10_2010', 'MIGRATION'),
('O33', 'Maternal care for known or suspected disproportion', 'ICD10_2010', 'MIGRATION'),
('O33.0', 'Maternal care for disproportion due to deformity of maternal pelvic bones', 'ICD10_2010', 'MIGRATION'),
('O33.1', 'Maternal care for disproportion due to generally contracted pelvis', 'ICD10_2010', 'MIGRATION'),
('O33.2', 'Maternal care for disproportion due to inlet contraction of pelvis', 'ICD10_2010', 'MIGRATION'),
('O33.3', 'Maternalcare for disproportion due to outlet contract of pelvis', 'ICD10_2010', 'MIGRATION'),
('O33.4', 'Maternal care for disproportion of mixed maternal and fetal origin', 'ICD10_2010', 'MIGRATION'),
('O33.5', 'Maternal care for disproportion due to unusually large fetus', 'ICD10_2010', 'MIGRATION'),
('O33.6', 'Maternal care for disproportion due to hydrocephalic fetus', 'ICD10_2010', 'MIGRATION'),
('O33.7', 'Maternal care for disproportion due to other fetal deformities', 'ICD10_2010', 'MIGRATION'),
('O33.8', 'Maternal care for disproportion of other origin', 'ICD10_2010', 'MIGRATION'),
('O33.9', 'Maternal care for disproportion, unspecified', 'ICD10_2010', 'MIGRATION'),
('O34', 'Maternal care for known or suspected abnormality of pelvic organs', 'ICD10_2010', 'MIGRATION'),
('O34.0', 'Maternal care for congenital malformation of uterus', 'ICD10_2010', 'MIGRATION'),
('O34.1', 'Maternal care for tumour of corpus uteri', 'ICD10_2010', 'MIGRATION'),
('O34.2', 'Maternal care due to uterine scar from previous surgery', 'ICD10_2010', 'MIGRATION'),
('O34.3', 'Maternal care for cervical incompetence', 'ICD10_2010', 'MIGRATION'),
('O34.4', 'Maternal care for other abnormalities of cervix', 'ICD10_2010', 'MIGRATION'),
('O34.5', 'Maternal care for other abnormalities of gravid uterus', 'ICD10_2010', 'MIGRATION'),
('O34.6', 'Maternal care for abnormality of vagina', 'ICD10_2010', 'MIGRATION'),
('O34.7', 'Maternal care for abnormality of vulva and perineum', 'ICD10_2010', 'MIGRATION'),
('O34.8', 'Maternal care for other abnormalities of pelvic organs', 'ICD10_2010', 'MIGRATION'),
('O34.9', 'Maternal care for abnormality of pelvic organ, unspecified', 'ICD10_2010', 'MIGRATION'),
('O35', 'Maternal care for known or suspected fetal abnormality and damage', 'ICD10_2010', 'MIGRATION'),
('O35.0', 'Maternal care for suspected central nervous system malformation in fetus', 'ICD10_2010', 'MIGRATION'),
('O35.1', 'Maternal care for suspected chromosomal abnormality in fetus', 'ICD10_2010', 'MIGRATION'),
('O35.2', 'Maternal care for suspected hereditary disease in fetus', 'ICD10_2010', 'MIGRATION'),
('O35.3', 'Maternal care for suspected damage to fetus from viral disease in mother', 'ICD10_2010', 'MIGRATION'),
('O35.4', 'Maternal care for suspected damage to fetus from alcohol', 'ICD10_2010', 'MIGRATION'),
('O35.5', 'Maternal care for suspected damage to fetus by drugs', 'ICD10_2010', 'MIGRATION'),
('O35.6', 'Maternal care for suspected damage to fetus by radiation', 'ICD10_2010', 'MIGRATION'),
('O35.7', 'Maternal care for suspected damage to fetus by other medical procedures', 'ICD10_2010', 'MIGRATION'),
('O35.8', 'Maternal care for other suspected fetal abnormality and damage', 'ICD10_2010', 'MIGRATION'),
('O35.9', 'Maternal care for suspected fetal abnormality and damage, unspecified', 'ICD10_2010', 'MIGRATION'),
('O36', 'Maternal care for other known or suspected fetal problems', 'ICD10_2010', 'MIGRATION'),
('O36.0', 'Maternal care for rhesus isoimmunization', 'ICD10_2010', 'MIGRATION'),
('O36.1', 'Maternal care for other isoimmunization', 'ICD10_2010', 'MIGRATION'),
('O36.2', 'Maternal care for hydrops fetalis', 'ICD10_2010', 'MIGRATION'),
('O36.3', 'Maternal care for signs of fetal hypoxia', 'ICD10_2010', 'MIGRATION'),
('O36.4', 'Maternal care for intrauterine death', 'ICD10_2010', 'MIGRATION'),
('O36.5', 'Maternal care for poor fetal growth', 'ICD10_2010', 'MIGRATION'),
('O36.6', 'Maternal care for excessive fetal growth', 'ICD10_2010', 'MIGRATION'),
('O36.7', 'Maternal care for viable fetus in abdominal pregnancy', 'ICD10_2010', 'MIGRATION'),
('O36.8', 'Maternal care for other specified fetal problems', 'ICD10_2010', 'MIGRATION'),
('O36.9', 'Maternal care for fetal problem, unspecified', 'ICD10_2010', 'MIGRATION'),
('O40', 'Polyhydramnios', 'ICD10_2010', 'MIGRATION'),
('O41', 'Other disorders of amniotic fluid and membranes', 'ICD10_2010', 'MIGRATION'),
('O41.0', 'Oligohydramnios', 'ICD10_2010', 'MIGRATION'),
('O41.1', 'Infection of amniotic sac and membranes', 'ICD10_2010', 'MIGRATION'),
('O41.8', 'Other specified disorders of amniotic fluid and membranes', 'ICD10_2010', 'MIGRATION'),
('O41.9', 'Disorder of amniotic fluid and membranes, unspecified', 'ICD10_2010', 'MIGRATION'),
('O42', 'Premature rupture of membranes', 'ICD10_2010', 'MIGRATION'),
('O42.0', 'Premature rupture of membranes, onset of labour within 24 hours', 'ICD10_2010', 'MIGRATION'),
('O42.1', 'Premature rupture of membranes, onset of labour after 24 hours', 'ICD10_2010', 'MIGRATION'),
('O42.2', 'Premature rupture of membranes, labour delayed by therapy', 'ICD10_2010', 'MIGRATION'),
('O42.9', 'Premature rupture of membranes, unspecified', 'ICD10_2010', 'MIGRATION'),
('O43', 'Placental disorders', 'ICD10_2010', 'MIGRATION'),
('O43.0', 'Placental transfusion syndromes', 'ICD10_2010', 'MIGRATION'),
('O43.1', 'Malformation of placenta', 'ICD10_2010', 'MIGRATION'),
('O43.2', 'Morbidly adherent placenta', 'ICD10_2010', 'MIGRATION'),
('O43.8', 'Other placental disorders', 'ICD10_2010', 'MIGRATION'),
('O43.9', 'Placental disorder, unspecified', 'ICD10_2010', 'MIGRATION'),
('O44', 'Placenta praevia', 'ICD10_2010', 'MIGRATION'),
('O44.0', 'Placenta praevia specified as without haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O44.1', 'Placenta praevia with haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O45', 'Premature separation of placenta [abruptio placentae]', 'ICD10_2010', 'MIGRATION'),
('O45.0', 'Premature separation of placenta with coagulation defect', 'ICD10_2010', 'MIGRATION'),
('O45.8', 'Other premature separation of placenta', 'ICD10_2010', 'MIGRATION'),
('O45.9', 'Premature separation of placenta, unspecified', 'ICD10_2010', 'MIGRATION'),
('O46', 'Antepartum haemorrhage, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O46.0', 'Antepartum haemorrhage with coagulation defect', 'ICD10_2010', 'MIGRATION'),
('O46.8', 'Other antepartum haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O46.9', 'Antepartum haemorrhage, unspecified', 'ICD10_2010', 'MIGRATION'),
('O47', 'False labour', 'ICD10_2010', 'MIGRATION'),
('O47.0', 'False labour before 37 completed weeks of gestation', 'ICD10_2010', 'MIGRATION'),
('O47.1', 'False labour at or after 37 completed weeks of gestation', 'ICD10_2010', 'MIGRATION'),
('O47.9', 'False labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O48', 'Prolonged pregnancy', 'ICD10_2010', 'MIGRATION'),
('O60', 'Preterm labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O60.0', 'Preterm labour without delivery', 'ICD10_2010', 'MIGRATION'),
('O60.1', 'Preterm labour with preterm delivery', 'ICD10_2010', 'MIGRATION'),
('O60.2', 'Preterm labour with term delivery', 'ICD10_2010', 'MIGRATION'),
('O60.3', 'Preterm delivery without spontaneous labour', 'ICD10_2010', 'MIGRATION'),
('O61', 'Failed induction of labour', 'ICD10_2010', 'MIGRATION'),
('O61.0', 'Failed medical induction of labour', 'ICD10_2010', 'MIGRATION'),
('O61.1', 'Failed instrumental induction of labour', 'ICD10_2010', 'MIGRATION'),
('O61.8', 'Other failed induction of labour', 'ICD10_2010', 'MIGRATION'),
('O61.9', 'Failed induction of labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O62', 'Abnormalities of forces of labour', 'ICD10_2010', 'MIGRATION'),
('O62.0', 'Primary inadequate contractions', 'ICD10_2010', 'MIGRATION'),
('O62.1', 'Secondary uterine inertia', 'ICD10_2010', 'MIGRATION'),
('O62.2', 'Other uterine inertia', 'ICD10_2010', 'MIGRATION'),
('O62.3', 'Precipitate labour', 'ICD10_2010', 'MIGRATION'),
('O62.4', 'Hypertonic, incoordinate, and prolonged uterine contractions', 'ICD10_2010', 'MIGRATION'),
('O62.8', 'Other abnormalities of forces of labour', 'ICD10_2010', 'MIGRATION'),
('O62.9', 'Abnormality of forces of labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O63', 'Long labour', 'ICD10_2010', 'MIGRATION'),
('O63.0', 'Prolonged first stage of labour', 'ICD10_2010', 'MIGRATION'),
('O63.1', 'Prolonged second stage of labour', 'ICD10_2010', 'MIGRATION'),
('O63.2', 'Delayed delivery of second twin, triplet, etc', 'ICD10_2010', 'MIGRATION'),
('O63.9', 'Long labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O64', 'Obstructed labour due to malposition and malpresentation of fetus', 'ICD10_2010', 'MIGRATION'),
('O64.0', 'Obstructed labour due to incomplete rotation of fetal head', 'ICD10_2010', 'MIGRATION'),
('O64.1', 'Obstructed labour due to breech presentation', 'ICD10_2010', 'MIGRATION'),
('O64.2', 'Obstructed labour due to face presentation', 'ICD10_2010', 'MIGRATION'),
('O64.3', 'Obstructed labour due to brow presentation', 'ICD10_2010', 'MIGRATION'),
('O64.4', 'Obstructed labour due to shoulder presentation', 'ICD10_2010', 'MIGRATION'),
('O64.5', 'Obstructed labour due to compound presentation', 'ICD10_2010', 'MIGRATION'),
('O64.8', 'Obstructed labour due other malposition and malpresentation', 'ICD10_2010', 'MIGRATION'),
('O64.9', 'Obstructed labour due malposition and malpresentation, unspecified', 'ICD10_2010', 'MIGRATION'),
('O65', 'Obstructed labour due to maternal pelvic abnormality', 'ICD10_2010', 'MIGRATION'),
('O65.0', 'Obstructed labour due to deformed pelvis', 'ICD10_2010', 'MIGRATION'),
('O65.1', 'Obstructed labour due to generally contracted pelvis', 'ICD10_2010', 'MIGRATION'),
('O65.2', 'Obstructed labour due to pelvic inlet contraction', 'ICD10_2010', 'MIGRATION'),
('O65.3', 'Obstructed labour due pelvic outlet and mid-cavity contraction', 'ICD10_2010', 'MIGRATION'),
('O65.4', 'Obstructed labour due to fetopelvic disproportion, unspecified', 'ICD10_2010', 'MIGRATION'),
('O65.5', 'Obstructed labour due abnormality of maternal pelvic organs', 'ICD10_2010', 'MIGRATION'),
('O65.8', 'Obstructed labour due to other maternal pelvic abnormalities', 'ICD10_2010', 'MIGRATION'),
('O65.9', 'Obstructed labour due to maternal pelvic abnormality, unspecified', 'ICD10_2010', 'MIGRATION'),
('O66', 'Other obstructed labour', 'ICD10_2010', 'MIGRATION'),
('O66.0', 'Obstructed labour due to shoulder dystocia', 'ICD10_2010', 'MIGRATION'),
('O66.1', 'Obstructed labour due to locked twins', 'ICD10_2010', 'MIGRATION'),
('O66.2', 'Obstructed labour due to unusually large fetus', 'ICD10_2010', 'MIGRATION'),
('O66.3', 'Obstructed labour due to other abnormalities of fetus', 'ICD10_2010', 'MIGRATION'),
('O66.4', 'Failed trial of labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O66.5', 'Failed application of vacuum extractor and forceps, unspecified', 'ICD10_2010', 'MIGRATION'),
('O66.8', 'Other specified obstructed labour', 'ICD10_2010', 'MIGRATION'),
('O66.9', 'Obstructed labour, unspecified', 'ICD10_2010', 'MIGRATION'),
('O67', 'Labour and delivery complicated by intrapartum haemorrhage, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O67.0', 'Intrapartum haemorrhage with coagulation defect', 'ICD10_2010', 'MIGRATION'),
('O67.8', 'Other intrapartum haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O67.9', 'Intrapartum haemorrhage, unspecified', 'ICD10_2010', 'MIGRATION'),
('O68', 'Labour and delivery complicated by fetal stress [distress]', 'ICD10_2010', 'MIGRATION'),
('O68.0', 'Labour and delivery complicated by fetal heart rate anomaly', 'ICD10_2010', 'MIGRATION'),
('O68.1', 'Labour and delivery complicated by meconium in amniotic fluid', 'ICD10_2010', 'MIGRATION'),
('O68.2', 'Labour and delivery complicated fetal heart rate anomaly with meconium in amniot fluid', 'ICD10_2010', 'MIGRATION'),
('O68.3', 'Labour and delivery complicated by biochemical evidence of fetal stress', 'ICD10_2010', 'MIGRATION'),
('O68.8', 'Labour and delivery complicated by other evidence of fetal stress', 'ICD10_2010', 'MIGRATION'),
('O68.9', 'Labour and delivery complicated by fetal stress, unspecified', 'ICD10_2010', 'MIGRATION'),
('O69', 'Labour and delivery complicated by umbilical cord complications', 'ICD10_2010', 'MIGRATION'),
('O69.0', 'Labour and delivery complicated by prolapse of cord', 'ICD10_2010', 'MIGRATION'),
('O69.1', 'Labour and delivery complicated cord around neck, with compression', 'ICD10_2010', 'MIGRATION'),
('O69.2', 'Labour and delivery complicated by other cord entanglement', 'ICD10_2010', 'MIGRATION'),
('O69.3', 'Labour and delivery complicated by short cord', 'ICD10_2010', 'MIGRATION'),
('O69.4', 'Labour and delivery complicated by vasa praevia', 'ICD10_2010', 'MIGRATION'),
('O69.5', 'Labour and delivery complicated by vascular lesion of cord', 'ICD10_2010', 'MIGRATION'),
('O69.8', 'Labour and delivery complicated by other cord complications', 'ICD10_2010', 'MIGRATION'),
('O69.9', 'Labour and delivery complicated by cord complication, unspecified', 'ICD10_2010', 'MIGRATION'),
('O70', 'Perineal laceration during delivery', 'ICD10_2010', 'MIGRATION'),
('O70.0', 'First degree perineal laceration during delivery', 'ICD10_2010', 'MIGRATION'),
('O70.1', 'Second degree perineal laceration during delivery', 'ICD10_2010', 'MIGRATION'),
('O70.2', 'Third degree perineal laceration during delivery', 'ICD10_2010', 'MIGRATION'),
('O70.3', 'Fourth degree perineal laceration during delivery', 'ICD10_2010', 'MIGRATION'),
('O70.9', 'Perineal laceration during delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O71', 'Other obstetric trauma', 'ICD10_2010', 'MIGRATION'),
('O71.0', 'Rupture of uterus before onset of labour', 'ICD10_2010', 'MIGRATION'),
('O71.1', 'Rupture of uterus during labour', 'ICD10_2010', 'MIGRATION'),
('O71.2', 'Postpartum inversion of uterus', 'ICD10_2010', 'MIGRATION'),
('O71.3', 'Obstetric laceration of cervix', 'ICD10_2010', 'MIGRATION'),
('O71.4', 'Obstetric high vaginal laceration alone', 'ICD10_2010', 'MIGRATION'),
('O71.5', 'Other obstetric injury to pelvic organs', 'ICD10_2010', 'MIGRATION'),
('O71.6', 'Obstetric damage to pelvic joints and ligaments', 'ICD10_2010', 'MIGRATION'),
('O71.7', 'Obstetric haematoma of pelvis', 'ICD10_2010', 'MIGRATION'),
('O71.8', 'Other specified obstetric trauma', 'ICD10_2010', 'MIGRATION'),
('O71.9', 'Obstetric trauma, unspecified', 'ICD10_2010', 'MIGRATION'),
('O72', 'Postpartum haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O72.0', 'Third-stage haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O72.1', 'Other immediate postpartum haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O72.2', 'Delayed and secondary postpartum haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O72.3', 'Postpartum coagulation defects', 'ICD10_2010', 'MIGRATION'),
('O73', 'Retained placenta and membranes, without haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O73.0', 'Retained placenta without haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O73.1', 'Retained portions of placenta and membranes, without haemorrhage', 'ICD10_2010', 'MIGRATION'),
('O74', 'Complications of anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.0', 'Aspiration pneumonitis due to anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.1', 'Other pulmonary complications anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.2', 'Cardiac complications of anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.3', 'Central nervous system complications of anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.4', 'Toxic reaction to local anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.5', 'Spinal and epidural anaesthesia-induced headache during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.6', 'Other complications of spinal and epidural anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.7', 'Failed or difficult intubation during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.8', 'Other complications of anaesthesia during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O74.9', 'Complication of anaesthesia during labour and delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O75', 'Other complications of labour and delivery, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O75.0', 'Maternal distress during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O75.1', 'Shock during or following labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O75.2', 'Pyrexia during labour, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O75.3', 'Other infection during labour', 'ICD10_2010', 'MIGRATION'),
('O75.4', 'Other complications of obstetric surgery and procedures', 'ICD10_2010', 'MIGRATION'),
('O75.5', 'Delayed delivery after artificial rupture of membranes', 'ICD10_2010', 'MIGRATION'),
('O75.6', 'Delayed delivery after spontaneous or unspecified rupture of membranes', 'ICD10_2010', 'MIGRATION'),
('O75.7', 'Vaginal delivery following previous caesarean section', 'ICD10_2010', 'MIGRATION'),
('O75.8', 'Other specified complications of labour and delivery', 'ICD10_2010', 'MIGRATION'),
('O75.9', 'Complication of labour and delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O80', 'Single spontaneous delivery', 'ICD10_2010', 'MIGRATION'),
('O80.0', 'Spontaneous vertex delivery', 'ICD10_2010', 'MIGRATION'),
('O80.1', 'Spontaneous breech delivery', 'ICD10_2010', 'MIGRATION'),
('O80.8', 'Other single spontaneous delivery', 'ICD10_2010', 'MIGRATION'),
('O80.9', 'Single spontaneous delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O81', 'Single delivery by forceps and vacuum extractor', 'ICD10_2010', 'MIGRATION'),
('O81.0', 'Low forceps delivery', 'ICD10_2010', 'MIGRATION'),
('O81.1', 'Mid-cavity forceps delivery', 'ICD10_2010', 'MIGRATION'),
('O81.2', 'Mid-cavity forceps with rotation', 'ICD10_2010', 'MIGRATION'),
('O81.3', 'Other and unspecified forceps delivery', 'ICD10_2010', 'MIGRATION'),
('O81.4', 'Vacuum extractor delivery', 'ICD10_2010', 'MIGRATION'),
('O81.5', 'Delivery by combination of forceps and vacuum extractor', 'ICD10_2010', 'MIGRATION'),
('O82', 'Single delivery by caesarean section', 'ICD10_2010', 'MIGRATION'),
('O82.0', 'Delivery by elective caesarean section', 'ICD10_2010', 'MIGRATION'),
('O82.1', 'Delivery by emergency caesarean section', 'ICD10_2010', 'MIGRATION'),
('O82.2', 'Delivery by caesarean hysterectomy', 'ICD10_2010', 'MIGRATION'),
('O82.8', 'Other single delivery by caesarean section', 'ICD10_2010', 'MIGRATION'),
('O82.9', 'Delivery by caesarean section, unspecified', 'ICD10_2010', 'MIGRATION'),
('O83', 'Other assisted single delivery', 'ICD10_2010', 'MIGRATION'),
('O83.0', 'Breech extraction', 'ICD10_2010', 'MIGRATION'),
('O83.1', 'Other assisted breech delivery', 'ICD10_2010', 'MIGRATION'),
('O83.2', 'Other manipulation-assisted delivery', 'ICD10_2010', 'MIGRATION'),
('O83.3', 'Delivery of viable fetus in abdominal pregnancy', 'ICD10_2010', 'MIGRATION'),
('O83.4', 'Destructive operation for delivery', 'ICD10_2010', 'MIGRATION'),
('O83.8', 'Other specified assisted single delivery', 'ICD10_2010', 'MIGRATION'),
('O83.9', 'Assisted single delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O84', 'Multiple delivery', 'ICD10_2010', 'MIGRATION'),
('O84.0', 'Multiple delivery, all spontaneous', 'ICD10_2010', 'MIGRATION'),
('O84.1', 'Multiple delivery, all by forceps and vacuum extractor', 'ICD10_2010', 'MIGRATION'),
('O84.2', 'Multiple delivery, all by caesarean section', 'ICD10_2010', 'MIGRATION'),
('O84.8', 'Other multiple delivery', 'ICD10_2010', 'MIGRATION'),
('O84.9', 'Multiple delivery, unspecified', 'ICD10_2010', 'MIGRATION'),
('O85', 'Puerperal sepsis', 'ICD10_2010', 'MIGRATION'),
('O86', 'Other puerperal infections', 'ICD10_2010', 'MIGRATION'),
('O86.0', 'Infection of obstetric surgical wound', 'ICD10_2010', 'MIGRATION'),
('O86.1', 'Other infection of genital tract following delivery', 'ICD10_2010', 'MIGRATION'),
('O86.2', 'Urinary tract infection following delivery', 'ICD10_2010', 'MIGRATION'),
('O86.3', 'Other genitourinary tract infections following delivery', 'ICD10_2010', 'MIGRATION'),
('O86.4', 'Pyrexia of unknown origin following delivery', 'ICD10_2010', 'MIGRATION'),
('O86.8', 'Other specified puerperal infections', 'ICD10_2010', 'MIGRATION'),
('O87', 'Venous complications in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.0', 'Superficial thrombophlebitis in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.1', 'Deep phlebothrombosis in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.2', 'Haemorrhoids in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.3', 'Cerebral venous thrombosis in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.8', 'Other venous complications in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O87.9', 'Venous complication in the puerperium, unspecified', 'ICD10_2010', 'MIGRATION'),
('O88', 'Obstetric embolism', 'ICD10_2010', 'MIGRATION'),
('O88.0', 'Obstetric air embolism', 'ICD10_2010', 'MIGRATION'),
('O88.1', 'Amniotic fluid embolism', 'ICD10_2010', 'MIGRATION'),
('O88.2', 'Obstetric blood-clot embolism', 'ICD10_2010', 'MIGRATION'),
('O88.3', 'Obstetric pyaemic and septic embolism', 'ICD10_2010', 'MIGRATION'),
('O88.8', 'Other obstetric embolism', 'ICD10_2010', 'MIGRATION'),
('O89', 'Complications of anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.0', 'Pulmonary complications of anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.1', 'Cardiac complications of anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.2', 'Central nervous system complications of anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.3', 'Toxic reaction to local anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.4', 'Spinal and epidural anaesthesia-induced headache during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.5', 'Other complications of spinal and epidural anaesthesia during puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.6', 'Failed or difficult intubation during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.8', 'Other complications of anaesthesia during the puerperium', 'ICD10_2010', 'MIGRATION'),
('O89.9', 'Complication of anaesthesia during the puerperium, unspecified', 'ICD10_2010', 'MIGRATION'),
('O90', 'Complications of the puerperium, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O90.0', 'Disruption of caesarean section wound', 'ICD10_2010', 'MIGRATION'),
('O90.1', 'Disruption of perineal obstetric wound', 'ICD10_2010', 'MIGRATION'),
('O90.2', 'Haematoma of obstetric wound', 'ICD10_2010', 'MIGRATION'),
('O90.3', 'Cardiomyopathy in the puerperium', 'ICD10_2010', 'MIGRATION'),
('O90.4', 'Postpartum acute renal failure', 'ICD10_2010', 'MIGRATION'),
('O90.5', 'Postpartum thyroiditis', 'ICD10_2010', 'MIGRATION'),
('O90.8', 'Other complications of the puerperium, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('O90.9', 'Complication of the puerperium, unspecified', 'ICD10_2010', 'MIGRATION'),
('O91', 'Infections of breast associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O91.0', 'Infection of nipple associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O91.1', 'Abscess of breast associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O91.2', 'Nonpurulent mastitis associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O92', 'Other disorders of breast and lactation associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O92.0', 'Retracted nipple associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O92.1', 'Cracked nipple associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O92.2', 'Other and unspecified disorders of breast associated with childbirth', 'ICD10_2010', 'MIGRATION'),
('O92.3', 'Agalactia', 'ICD10_2010', 'MIGRATION'),
('O92.4', 'Hypogalactia', 'ICD10_2010', 'MIGRATION'),
('O92.5', 'Suppressed lactation', 'ICD10_2010', 'MIGRATION'),
('O92.6', 'Galactorrhoea', 'ICD10_2010', 'MIGRATION'),
('O92.7', 'Other and unspecified disorders of lactation', 'ICD10_2010', 'MIGRATION'),
('O94', 'Sequelae of complication of pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O95', 'Obstetric death of unspecified cause', 'ICD10_2010', 'MIGRATION'),
('O96', 'Death from any obstetric cause occuring more than 42 days but less than one year after delivery', 'ICD10_2010', 'MIGRATION'),
('O96.0', 'Death from direct obstetric cause', 'ICD10_2010', 'MIGRATION'),
('O96.1', 'Death from indirect obstetric cause', 'ICD10_2010', 'MIGRATION'),
('O96.9', 'Death from unspecified obstetric cause', 'ICD10_2010', 'MIGRATION'),
('O97', 'Death from sequelae of direct obstetric causes', 'ICD10_2010', 'MIGRATION'),
('O97.0', 'Death from sequelae of direct obstetric cause', 'ICD10_2010', 'MIGRATION'),
('O97.1', 'Death from sequelae of indirect obstetric cause', 'ICD10_2010', 'MIGRATION'),
('O97.9', 'Death from sequelae of obstetric cause, unspecified', 'ICD10_2010', 'MIGRATION'),
('O98', 'Maternal infectious and parasitic diseases classifiable elsewhere but complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.0', 'Tuberculosis complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.1', 'Syphilis complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.2', 'Gonorrhoea complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.3', 'Other infections predominantly sexual mode of transmission complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.4', 'Viral hepatitis complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.5', 'Other viral diseases complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.6', 'Protozoal diseases complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.7', 'Human immunodeficiency [HIV] disease complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.8', 'Other maternal infectious parasitic diseases complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O98.9', 'Unspecified maternal infectious parasitic disease complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99', 'Other maternal diseases classifiable elsewhere but complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.0', 'Anaemia complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.1', 'Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.2', 'Endocrine, nutritional metabolic diseases complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.3', 'Mental disorders and diseases of the nervous system complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.4', 'Diseases of the circulatory system complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.5', 'Diseases of the respiratory system complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.6', 'Diseases of the digestive system complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.7', 'Diseases of the skin and subcutaneous tissue complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('O99.8', 'Other specified diseases and conditions complicating pregnancy, childbirth and the puerperium', 'ICD10_2010', 'MIGRATION'),
('P00', 'Fetus and newborn affected by maternal conditions that may be unrelated to present pregnancy', 'ICD10_2010', 'MIGRATION'),
('P00.0', 'Fetus and newborn afected by maternal hypertensive disord', 'ICD10_2010', 'MIGRATION'),
('P00.1', 'Fet and newborn afected by mat renal and urinary tract dis', 'ICD10_2010', 'MIGRATION'),
('P00.2', 'Fetus and newborn affected by mat infect and parasitic dis', 'ICD10_2010', 'MIGRATION'),
('P00.3', 'Fetus and newborn affected oth mat circulatory and resp dis', 'ICD10_2010', 'MIGRATION'),
('P00.4', 'Fetus and newborn affected by maternal nutritional disorders', 'ICD10_2010', 'MIGRATION'),
('P00.5', 'Fetus and newborn affected by maternal injury', 'ICD10_2010', 'MIGRATION'),
('P00.6', 'Fetus and newborn affected by surgical procedure on mother', 'ICD10_2010', 'MIGRATION'),
('P00.7', 'Fetus and newborn affected other medic procs on mother nec', 'ICD10_2010', 'MIGRATION'),
('P00.8', 'Fetus and newborn affected by other maternal conditions', 'ICD10_2010', 'MIGRATION'),
('P00.9', 'Fetus and newborn affected by unspecified maternal condition', 'ICD10_2010', 'MIGRATION'),
('P01', 'Fetus and newborn affected by maternal complications of pregnancy', 'ICD10_2010', 'MIGRATION'),
('P01.0', 'Fetus and newborn affected by incompetent cervix', 'ICD10_2010', 'MIGRATION'),
('P01.1', 'Fetus and newborn affected by premature rupture of membranes', 'ICD10_2010', 'MIGRATION'),
('P01.2', 'Fetus and newborn affected by oligohydramnios', 'ICD10_2010', 'MIGRATION'),
('P01.3', 'Fetus and newborn affected by polyhydramnios', 'ICD10_2010', 'MIGRATION'),
('P01.4', 'Fetus and newborn affected by ectopic pregnancy', 'ICD10_2010', 'MIGRATION'),
('P01.5', 'Fetus and newborn affected by multiple pregnancy', 'ICD10_2010', 'MIGRATION'),
('P01.6', 'Fetus and newborn affected by maternal death', 'ICD10_2010', 'MIGRATION'),
('P01.7', 'Fetus and newborn affected by malpresentation before labour', 'ICD10_2010', 'MIGRATION'),
('P01.8', 'Fetus and newborn affected other maternal comps of preg', 'ICD10_2010', 'MIGRATION'),
('P01.9', 'Fetus and newborn affect by maternal comp of preg unspec act', 'ICD10_2010', 'MIGRATION'),
('P02', 'Fetus and newborn affected by complications of placenta, cord and membranes', 'ICD10_2010', 'MIGRATION'),
('P02.0', 'Fetus and newborn affected by placenta praevia', 'ICD10_2010', 'MIGRATION'),
('P02.1', 'Fetus and newborn affect oth forms placent sepn haemorrh', 'ICD10_2010', 'MIGRATION'),
('P02.2', 'Fetus newborn affect other unsp morph funct abnorm placent', 'ICD10_2010', 'MIGRATION'),
('P02.3', 'Fet and newborn affected by placental transfusion syndr', 'ICD10_2010', 'MIGRATION'),
('P02.4', 'Fetus and newborn affected by prolapsed cord', 'ICD10_2010', 'MIGRATION'),
('P02.5', 'Fetus and newborn affected other compression umb cord', 'ICD10_2010', 'MIGRATION'),
('P02.6', 'Fetus and newborn affect oth unspec conds of umbilical cord', 'ICD10_2010', 'MIGRATION'),
('P02.7', 'Fetus and newborn affected by chorioamnionitis', 'ICD10_2010', 'MIGRATION'),
('P02.8', 'Fetus and newborn affect by oth abnormalities of membr', 'ICD10_2010', 'MIGRATION'),
('P02.9', 'Fetus and newborn affected by abnorm of membranes unsp', 'ICD10_2010', 'MIGRATION'),
('P03', 'Fetus and newborn affected by other complications of labour and delivery', 'ICD10_2010', 'MIGRATION'),
('P03.0', 'Fetus and newborn affected by breech delivery and extraction', 'ICD10_2010', 'MIGRATION'),
('P03.1', 'Fet newborn affect oth malpresent malpos disprop lab deliv', 'ICD10_2010', 'MIGRATION'),
('P03.2', 'Fetus and newborn affected by forceps delivery', 'ICD10_2010', 'MIGRATION'),
('P03.3', 'Fet and newborn affected deliv vacuum extractor ventouse', 'ICD10_2010', 'MIGRATION'),
('P03.4', 'Fetus and newborn affected by caesarean delivery', 'ICD10_2010', 'MIGRATION'),
('P03.5', 'Fetus and newborn affected by precipitate delivery', 'ICD10_2010', 'MIGRATION'),
('P03.6', 'Fetus and newborn affected by abnormal uterine contractions', 'ICD10_2010', 'MIGRATION'),
('P03.8', 'Fetus and newborn affected other spec comps of labour deliv', 'ICD10_2010', 'MIGRATION'),
('P03.9', 'Fetus and newborn affected by comp of lab and deliv unsp', 'ICD10_2010', 'MIGRATION'),
('P04', 'Fetus and newborn affected by noxious influences transmitted via placenta or breast milk', 'ICD10_2010', 'MIGRATION'),
('P04.0', 'Fet newborn affect mat anaesth and analges preg lab del', 'ICD10_2010', 'MIGRATION'),
('P04.1', 'Fetus and newborn affected by other maternal medication', 'ICD10_2010', 'MIGRATION'),
('P04.2', 'Fetus and newborn affected by maternal use of tobacco', 'ICD10_2010', 'MIGRATION'),
('P04.3', 'Fetus and newborn affected by maternal use of alcohol', 'ICD10_2010', 'MIGRATION'),
('P04.4', 'Fetus and newborn affected by mat use of drugs of addiction', 'ICD10_2010', 'MIGRATION'),
('P04.5', 'Fetus and newborn afect by mat use of nutritional chem subs', 'ICD10_2010', 'MIGRATION'),
('P04.6', 'Fet  newborn affect mat exposure to environml chem subs', 'ICD10_2010', 'MIGRATION'),
('P04.8', 'Fetus and newborn affected by other mat noxious influences', 'ICD10_2010', 'MIGRATION'),
('P04.9', 'Fetus and newborn affected by mat noxious influence unspec act', 'ICD10_2010', 'MIGRATION'),
('P05', 'Slow fetal growth and fetal malnutrition', 'ICD10_2010', 'MIGRATION'),
('P05.0', 'Light for gestational age', 'ICD10_2010', 'MIGRATION'),
('P05.1', 'Small for gestational age', 'ICD10_2010', 'MIGRATION'),
('P05.2', 'Fet malnutrit without mention light or small for gestat age', 'ICD10_2010', 'MIGRATION'),
('P05.9', 'Slow fetal growth, unspecified', 'ICD10_2010', 'MIGRATION'),
('P07', 'Disorders related to short gestation and low birth weight, not elsewhere classified', 'ICD10_2010', 'MIGRATION'),
('P07.0', 'Extremely low birth weight', 'ICD10_2010', 'MIGRATION'),
('P07.1', 'Other low birth weight', 'ICD10_2010', 'MIGRATION'),
('P07.2', 'Extreme immaturity', 'ICD10_2010', 'MIGRATION'),
('P07.3', 'Other preterm infants', 'ICD10_2010', 'MIGRATION'),
('P08', 'Disorders related to long gestation and high birth weight', 'ICD10_2010', 'MIGRATION'),
('P08.0', 'Exceptionally large baby', 'ICD10_2010', 'MIGRATION'),
('P08.1', 'Other heavy for gestational age infants', 'ICD10_2010', 'MIGRATION'),
('P08.2', 'Post-term infant, not heavy for gestational age', 'ICD10_2010', 'MIGRATION'),
('P10', 'Intracranial laceration and haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.0', 'Subdural haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.1', 'Cerebral haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.2', 'Intraventricular haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.3', 'Subarachnoid haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.4', 'Tentorial tear due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P10.8', 'Oth intracranial lacerations and haemorrhages due birth inj', 'ICD10_2010', 'MIGRATION'),
('P10.9', 'Unsp intracranial laceration and haemorrhage due  birth inj', 'ICD10_2010', 'MIGRATION'),
('P11', 'Other birth injuries to central nervous system', 'ICD10_2010', 'MIGRATION'),
('P11.0', 'Cerebral oedema due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P11.1', 'Other specified brain damage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P11.2', 'Unspecified brain damage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P11.3', 'Birth injury to facial nerve', 'ICD10_2010', 'MIGRATION'),
('P11.4', 'Birth injury to other cranial nerves', 'ICD10_2010', 'MIGRATION'),
('P11.5', 'Birth injury to spine and spinal cord', 'ICD10_2010', 'MIGRATION'),
('P11.9', 'Birth injury to central nervous system, unspecified', 'ICD10_2010', 'MIGRATION'),
('P12', 'Birth injury to scalp', 'ICD10_2010', 'MIGRATION'),
('P12.0', 'Cephalhaematoma due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P12.1', 'Chignon due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P12.2', 'Epicranial subaponeurotic haemorrhage due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P12.3', 'Bruising of scalp due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P12.4', 'Monitoring injury of scalp of newborn', 'ICD10_2010', 'MIGRATION'),
('P12.8', 'Other birth injuries to scalp', 'ICD10_2010', 'MIGRATION'),
('P12.9', 'Birth injury to scalp, unspecified', 'ICD10_2010', 'MIGRATION'),
('P13', 'Birth injury to skeleton', 'ICD10_2010', 'MIGRATION'),
('P13.0', 'Fracture of skull due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P13.1', 'Other birth injuries to skull', 'ICD10_2010', 'MIGRATION'),
('P13.2', 'Birth injury to femur', 'ICD10_2010', 'MIGRATION'),
('P13.3', 'Birth injury to other long bones', 'ICD10_2010', 'MIGRATION'),
('P13.4', 'Fracture of clavicle due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P13.8', 'Birth injuries to other parts of skeleton', 'ICD10_2010', 'MIGRATION'),
('P13.9', 'Birth injury to skeleton, unspecified', 'ICD10_2010', 'MIGRATION'),
('P14', 'Birth injury to peripheral nervous system', 'ICD10_2010', 'MIGRATION'),
('P14.0', 'Erb''s paralysis due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P14.1', 'Klumpke''s paralysis due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P14.2', 'Phrenic nerve paralysis due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P14.3', 'Other brachial plexus birth injuries', 'ICD10_2010', 'MIGRATION'),
('P14.8', 'Birth injuries to other parts of peripheral nervous system', 'ICD10_2010', 'MIGRATION'),
('P14.9', 'Birth injury to peripheral nervous system, unspecified', 'ICD10_2010', 'MIGRATION'),
('P15', 'Other birth injuries', 'ICD10_2010', 'MIGRATION'),
('P15.0', 'Birth injury to liver', 'ICD10_2010', 'MIGRATION'),
('P15.1', 'Birth injury to spleen', 'ICD10_2010', 'MIGRATION'),
('P15.2', 'Sternomastoid injury due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P15.3', 'Birth injury to eye', 'ICD10_2010', 'MIGRATION'),
('P15.4', 'Birth injury to face', 'ICD10_2010', 'MIGRATION'),
('P15.5', 'Birth injury to external genitalia', 'ICD10_2010', 'MIGRATION'),
('P15.6', 'Subcutaneous fat necrosis due to birth injury', 'ICD10_2010', 'MIGRATION'),
('P15.8', 'Other specified birth injuries', 'ICD10_2010', 'MIGRATION'),
('P15.9', 'Birth injury, unspecified', 'ICD10_2010', 'MIGRATION'),
('P20', 'Intrauterine hypoxia', 'ICD10_2010', 'MIGRATION'),
('P20.0', 'Intrauterine hypoxia first noted before onset of labour', 'ICD10_2010', 'MIGRATION'),
('P20.1', 'Intrauterine hypoxia first noted during labour and delivery', 'ICD10_2010', 'MIGRATION'),
('P20.9', 'Intrauterine hypoxia, unspecified', 'ICD10_2010', 'MIGRATION'),
('P21', 'Birth asphyxia', 'ICD10_2010', 'MIGRATION'),
('P21.0', 'Severe birth asphyxia', 'ICD10_2010', 'MIGRATION'),
('P21.1', 'Mild and moderate birth asphyxia', 'ICD10_2010', 'MIGRATION'),
('P21.9', 'Birth asphyxia, unspecified', 'ICD10_2010', 'MIGRATION'),
('P22', 'Respiratory distress of newborn', 'ICD10_2010', 'MIGRATION'),
('P22.0', 'Respiratory distress syndrome of newborn', 'ICD10_2010', 'MIGRATION'),
('P22.1', 'Transient tachypnoea of newborn', 'ICD10_2010', 'MIGRATION'),
('P22.8', 'Other respiratory distress of newborn', 'ICD10_2010', 'MIGRATION'),
('P22.9', 'Respiratory distress of newborn, unspecified', 'ICD10_2010', 'MIGRATION'),
('P23', 'Congenital pneumonia', 'ICD10_2010', 'MIGRATION'),
('P23.0', 'Congenital pneumonia due to viral agent', 'ICD10_2010', 'MIGRATION'),
('P23.1', 'Congenital pneumonia due to chlamydia', 'ICD10_2010', 'MIGRATION'),
('P23.2', 'Congenital pneumonia due to staphylococcus', 'ICD10_2010', 'MIGRATION'),
('P23.3', 'Congenital pneumonia due to streptococcus, group b', 'ICD10_2010', 'MIGRATION'),
('P23.4', 'Congenital pneumonia due to escherichia coli', 'ICD10_2010', 'MIGRATION'),
('P23.5', 'Congenital pneumonia due to pseudomonas', 'ICD10_2010', 'MIGRATION'),
('P23.6', 'Congenital pneumonia due to other bacterial agents', 'ICD10_2010', 'MIGRATION'),
('P23.8', 'Congenital pneumonia due to other organisms', 'ICD10_2010', 'MIGRATION'),
('P23.9', 'Congenital pneumonia, unspecified', 'ICD10_2010', 'MIGRATION'),
('P24', 'Neonatal aspiration syndromes', 'ICD10_2010', 'MIGRATION'),
('P24.0', 'Neonatal aspiration of meconium', 'ICD10_2010', 'MIGRATION'),
('P24.1', 'Neonatal aspiration of amniotic fluid and mucus', 'ICD10_2010', 'MIGRATION'),
('P24.2', 'Neonatal aspiration of blood', 'ICD10_2010', 'MIGRATION'),
('P24.3', 'Neonatal aspiration of milk and regurgitated food', 'ICD10_2010', 'MIGRATION'),
('P24.8', 'Other neonatal aspiration syndromes', 'ICD10_2010', 'MIGRATION'),
('P24.9', 'Neonatal aspiration syndrome, unspecified', 'ICD10_2010', 'MIGRATION');

-- +migrate Down
DELETE FROM diagnosa;
